CHANGELOG
fileupload.go
fileupload/client.go
fileupload/client_test.go
stripe.go

This should allow you to list file uploads via the go bindings.
r? @cosn

Adding functionality for listing file uploads.

---

fileupload/client_test.go

Fixes a number of bugs introduced by the #59.

Fixing file upload bugs.

---

CHANGELOG
bitcoin_receiver.go
bitcoin_transaction.go
bitcoinreceiver/client.go
bitcoinreceiver/client_test.go
bitcointransaction/client.go
bitcointransaction/client_test.go
card.go
charge.go
charge/client.go
charge/client_test.go
client/api.go
event/client_test.go
payment_source.go
paymentsource/types.go
stripe.go

Added Bitcoin Receiver & Transaction objects

Added Bitcoin Receiver & Transaction objects; support multiple charge sources

---

CHANGELOG
params.go
stripe.go

update NewIdempotencyKey algo

---

CHANGELOG
README.md
balance/client_test.go
bitcoin_receiver.go
bitcoinreceiver/client.go
bitcoinreceiver/client_test.go
card.go
card/client.go
card/client_test.go
charge.go
charge/client.go
charge/client_test.go
client/checkin_test.go
customer.go
customer/client.go
customer/client_test.go
example_test.go
invoice/client_test.go
payment_source.go
paymentsource/client.go
paymentsource/client_test.go
refund/client_test.go
stripe.go
sub/client_test.go

added structure to support for unified customer sources api

---

CHANGELOG
account.go
account/client.go
account/client_test.go
bankaccount.go
bankaccount/client.go
charge.go
charge/client.go
client/api.go
params.go
recipient.go
recipient/client.go
refund.go
refund/client.go
reversal.go
reversal/client.go
reversal/client_test.go
stripe.go
token/client_test.go
transfer.go
transfer/client.go
transfer/client_test.go

r? @bkrausz 
Will ping when everything's done, but figured this way you can review at your leisure

New Accounts style

---

invoice.go
invoice/client.go
invoice/client_test.go
sub.go
sub/client.go
sub/client_test.go

add TaxPercent field to Sub

---

reversal.go

Adds Tx field to Reversal struct
I wasn't sure if/how you'd want tests for this - it doesn't look like you have equivalent tests on charges or transfers - happy to add if you want though

Add balance transaction to reversals

---

customer.go

Fixed formatting

---

charge.go

Charges created with a destination (connect) have these properties.
Named `Dest`, `Fee`, & `Transfer` for consistency with keys used in charge creation.

Add destination, application fee, and transfer to Charge struct

---

stripe.go

Should resolve #97 to expose logger. Retained `LogLevel` for backwards compatibility.

Exposed logging object

---

sub.go
sub/client.go
sub/client_test.go

Add BillingCycleAnchor to SubParams

---

account/client.go
account/client_test.go

Added the ability to delete an account

---

.travis.yml
bitcoinreceiver/client_test.go
bitcointransaction/client_test.go
charge/client.go
charge/client_test.go
dispute.go
dispute/client.go
dispute/client_test.go
fileupload/client_test.go

This is a breaking change and will require a new major version.

Add top level disputes

---

payment_source.go

Fix #118 (code by @imjoshholloway)

Detect nil `c.Card.Customer` during `PaymentSource.MarshalJSON()`

---

sub.go

Add start parameter to Subscriptions

---

params.go
params_test.go

Add expandable parameters to ListParams

---

README.md
client/api.go
stripe.go

Add easier client initialization from HTTP client

---

bankaccount.go
payment_source.go
paymentsource/client.go
paymentsource/client_test.go

Add customer source bank account

---

coupon/client.go
coupon/client_test.go

Fixes #165.
/cc @remistr Mind giving this a quick review pass? Thanks!

Add a method for updating a coupon

---

bankaccount.go

[Reference](https://stripe.com/docs/api#bank_account_object-default_for_currency)

add default to bank account

---

charge.go

Adds "country" to charge shipping details

---

product/client.go
product/client_test.go
sku/client.go
sku/client_test.go

r? @brandur 
cc @jimdanz 
API endpoints: [SKU deletion](https://stripe.com/docs/api#delete_sku), [product deletion](https://stripe.com/docs/api#delete_product)

Support deleting SKUs and products.

---

README.md

Just a few minor clean-ups in the README to make it more consistent and
more friendly when read as plain text.

Nicen the README

---

client/api.go
countryspec.go
countryspec/client.go
countryspec/client_test.go

r? @brandur 
Integrated the comments from the other PR but messed up my git repo and creating a new one was easier, sorry

Added support for country specs in the bindings

---

account/client_test.go
paymentsource/client_test.go

Fix a few broken tests

---

account.go
account/client.go
account/client_test.go

To match the new [Account.reject API](https://stripe.com/docs/api/go#reject_account).
r? @stripe/api-libraries

Add account.reject method.

---

.travis.yml

Test against the current release of the Go language.

Test against Go 1.6

---

account.go
bankaccount.go
bitcoin_receiver.go
customer.go
params.go
payment_source.go
refund.go
stripe.go
token.go

Many of these are just additions of documentation, but many are also
legitimate fixes (largely comments that have drifted out of date with
the naming of the construct that they're commenting).
Unfortunately, this job isn't even close to being done. It fixes many
problems in the top level package (except around Relay resources, which
aren't well documented), but all the client subpackages are still in bad
shape.

Fix collection of miscellaneous linting errors

---

countryspec.go
countryspec/client_test.go

Support default_currency on CountrySpecs

---

bankaccount.go

Add Metadata field to bank account
r @brandur?

add meta to bankaccount

---

transfer.go
transfer/client.go
transfer/client_test.go

Added support for source_transaction and source_type for Transfers

---

account/client_test.go
card.go
token/client_test.go

Add the Currency field to Card objects

---

order/client.go

here is the changes to fix the issue #238

prevent nil exception if the params.Shipping is nil

---

order/client.go

Remove duplicated lines

---

transfer.go

Add missing `Reversed` and `AmountReversed` fields to `Transfer`

---

order.go
order/client.go
order/client_test.go
order_return.go
order_return/client.go
orderreturn/client.go
orderreturn/client_test.go

cc @jimdanz 
Bring our Go libraries up to speed with some of our recent API improvements.

Add order returns, delivery estimates

---

customer.go
customer/client.go
customer/client_test.go

Added support for the business_vat_id property in customers: https://stripe.com/docs/api#create_customer-business_vat_id

Add support for Customer business_vat_id

---

product/client.go
sku/client.go

cc @jimdanz 
Support updating SKU and product attributes after creation.

Support modifying SKU/product attributes.

---

coupon/client.go
plan/client.go

Closes issue https://github.com/stripe/stripe-go/issues/278

Resolves issue with unescaped coupon ids

---

account.go

include meta on accounts

---

transfer.go

This adds support for expanding the polymorphic `destination` property of `Transfer`s.
Addresses #193

support expanding destination on transfers

---

product.go
product/client.go

r? @stripe/api-libraries
Implement https://stripe.com/docs/api#create_product-deactivate_on

Add deactivate_on to products

---

client/api.go

looks like this one was missing

add order returns to client.api

---

address.go
charge/client_test.go
client/api.go
order.go
payment_source.go
paymentsource/client_test.go
source.go
source/client.go
source/client_test.go

Add support for Sources to Go.

Add support for Source objects

---

order/client.go

Small fix to allow updating orders on connected stripe accounts.

Set commonParams on order.Update

---

subitem.go

Ensure Quantity types match for SubItem

---

transfer.go
transfer_test.go

This fixes the type of Transfer.SourceTx to be *TransactionSource

Fix issue #322: Transfer.SourceTx has wrong type

---

applepaydomain.go
applepaydomain/client.go
applepaydomain/client_test.go

Added support for ApplePayDomain as a resource

---

account.go
charge.go
transfer.go

I spotted that a couple fields were missing so added them. They're all in https://stripe.com/docs/api

Add a couple missing fields

---

charge.go
charge/client_test.go

Added support for outcome[risk_level] on Charge

---

application.go
application_test.go
charge.go
example_test.go

Adds `Application` to `Charge`. Added some basic deserialization tests and added an expansion for an existing functional test.
r? @brandur

Add expandable Application to Charge

---

CHANGELOG
source/client.go

Hi,
this merge request fixes some minor issues.
It was created with help of [Feram][repo].
If it helped to improve this repository,
please consider to [star Feram's repo][repo] to show some love! 😊
PS:
The [Feram team][feramhq] is currently working on making this technology
available for everyone. If you want to be one of the first to use it,
please sign up up for the newsletter on [feram.co].
[repo]: https://github.com/feramhq/feram
[feramhq]: https://github.com/feramhq
[feram.co]: http://feram.co

Minor Fixes

---

sub.go
sub/client.go

Add support for trial period days

---

bankaccount/client.go

Currently only supports creating an external bank account.

Add creating a bank account on a customer

---

threedsecure/client.go
threedsecure/client_test.go

cc @stripe/api-libraries @bct 
Adds a method for retrieving 3DS auths.

Added 3DS retrieve endpoint

---

account.go

Fix the Account Update API to support document verification

---

source/client.go
source/client_test.go

r? @will-stripe
Adds support for source update requests.

Adds update source endpoint

---

client/api.go

Added subitem.Client in the main client.API struct

adding subscription items client in main API client

---

customer.go
customer/client.go
customer/client_test.go
sub.go
sub/client.go
sub/client_test.go

pull request for https://github.com/stripe/stripe-go/issues/370

Extended Sub Update with CouponRemove

---

source.go
source/client.go

Token was missing on SourceObjectParams. Also added it to request body when creating new source.

Add Token to SourceObjectParams

---

.travis.yml

Start testing Go 1.8 with Travis.

Start testing Go 1.8

---

dispute.go

Follows up #384.
cc @f2prateek

Alphabetizes fields in `DisputeEvidenceParams`

---

client/api.go
loginlink.go
loginlink/client.go
loginlink/client_test.go

Added support for login_link on the Account resource

---

stripe.go

Hi,
I want to propose this simple change which allows people to specify their own logger. All calls to the logger are already only using Printf, so that's all a logger is required to implement.

Use interface for logger

---

webhook/client.go
webhook/client_handler_test.go
webhook/client_test.go

Fixes #405 based on @froatsnook's excellent work in #413. Added a test suite based on other libraries' tests, refactored the public interface, and updated the godocs.
r? @brandur-stripe @ob-stripe 
I want to add one additional test as I think it's not fully testing multiple signatures behavior.

Add webhook signing

---

client/checkin_test.go
plan.go
plan/client.go
plan/client_test.go

Modified plan/client.go Del functions to accept params.
Modified plan.go struct with Customer String.

Added support to delete a plan on a connected account

---

client/api.go

Client is missing initializer for LoginLinks. So added it

Added missing loginlinks client initializer

---

subitem/client_test.go

Fixes compilation of subitem tests, which is currently broken. The tests
may still not actually run ...

Fix subitem test compilation

---

subitem.go
subitem/client_test.go

subitem: add support for metadata

---

params.go
params_test.go

In Go you can "embed" a struct into another struct [1]:
type ChargeParams struct {
Params
}
Embeds mostly behave like normal fields, except that they have the
special property that they allow the leaf struct to inherit any
functions implemented on the embedded struct.
For `Params`, this means that most parameter structs inherited the
`AppendTo` implementation of basic `Params`, which is where we encoded
our "extra" information.
However, when a leaf declares its own function by the same name, it no
longer inherits its embedded struct's implementation. This means that
any params that declare their own `AppendTo` will not currently encode
extras, because the `AppendTo` of `Params` doesn't get called.
This patch shifts things around a little bit so that we move encoding of
extras into an …

Fix bug where Params.AppendTo not called if leaf had its own implementation

---

form/form.go
form/form_test.go

This fixes #469 which was a problem where concurrent protection in the
caches wasn't working properly, making multiple closely-spaced
simultaneous accesses would result in stored maps throwing an error
because they were being read and written at the same time:
fatal error: concurrent map read and map write
Here we introduce an `RWMutex` which allows unlimited concurrent reads,
but no reads if any single write operation is in progress (see [1] for
details). It also drops the complexity around using `atomic.Value` now
that we have every operation wrapped in a mutex anyway.
I added a simple test case that I found was able to reproduce the
problem ~100% of the time, and these changes see it pass now on every
attempt.
Fixes #469.
[1] https://godoc.org/sync#RWMutex

Introduce extra concurrency safety for `form` package

---

source.go

Adds support for the [`statement_descriptor`](https://stripe.com/docs/api#source_object-statement_descriptor) field on sources.

Adds support for statement_descriptor field

---

payout.go

r? @dpetrovics-stripe  (dev-platform run)

Add support for automatic on Payout

---

plan.go

Add active to the Plan resource

---

coupon.go

Add name to the Coupon resource

---

plan.go

Fixes https://github.com/stripe/stripe-go/issues/594

Add support for listing plans by product

---

product.go

Similar to #595 , this (I hope) allows you to list products by type by adding a Type to the ProductListParams structure

Add support for listing products by type

---

balance.go

This PR adds the ExchangeRate field to the BalanceTransaction struct.

Adds missing ExchangeRate field to BalanceTransaction

---

charge.go
charge/client_test.go

Related to https://github.com/stripe/stripe-dotnet/pull/1216 which is the same for stripe-dotnet.

Add support for Level III data on charge creation

---

Makefile
applepaydomain/client.go
balance/client.go
bankaccount/client.go
card/client.go

Only did a few packages. Minor but I don't think `go test ./...` is able to catch linter errors which makes it easy to miss later. I'm saying this because I added my packages to the whitelist and only saw errors when explicitly using `golint` and not when doing `go test ./...`

Lint a few more packages

---

Makefile
ephemeralkey/client.go
event/client.go
exchangerate/client.go
fee/client.go
feerefund/client.go
fileupload/client.go
invoice/client.go
invoiceitem/client.go
issuerfraudrecord/client.go

More packages properly linted

---

account.go
account_test.go

This fixes https://github.com/stripe/stripe-go/issues/617

Add support for decline_charge_on on Account

---

account.go
account/client_test.go

Fixes https://github.com/stripe/stripe-go/issues/621

Fix decline_charge_on on the Account ressource

---

invoice.go

Add support for auto_advance on the Invoice resource

---

.travis.yml
Makefile
balance.go
client/api.go
issuing/authorization/client.go
issuing/authorization/client_test.go
issuing/card/client.go
issuing/card/client_test.go
issuing/cardholder/client.go
issuing/cardholder/client_test.go
issuing/dispute/client.go
issuing/dispute/client_test.go
issuing/transaction/client.go
issuing/transaction/client_test.go
issuing_authorization.go
issuing_card.go
issuing_cardholder.go
issuing_dispute.go
issuing_transaction.go
testing/testing.go

Add support for the Issuing APIs/resources

---

fileupload/client_test.go

Move fileupload tests to stripe-mock

---

account.go

Added the created field of Account to the relevant model.
https://stripe.com/docs/api/go#account_object-created

Add account.created field

---

.travis.yml
testing/testing.go
topup/client.go
topup/client_test.go

cc @stripe/api-libraries @foresthu-stripe

Add support for cancel on Topup

---

.travis.yml
client/api.go
filelink.go
filelink/client.go
filelink/client_test.go
filelink_test.go
fileupload.go
testing/testing.go

r? @ob-stripe @brandur-stripe 

Add the File Link resource

---

invoice.go

Add support for the forgive parameter on the Pay Invoice API

---

customer.go

Fixes https://github.com/stripe/stripe-go/issues/670

Properly deserialize the tax_id property

---

customer.go

Add support for invoice_prefix on the Customer resource/APIs

---

plan.go

per @remi-stripe, should fix https://github.com/stripe/stripe-go/issues/692.

Support expansion of products in plans

---

CHANGELOG.md

Self approving as it's just a changelog fix.

Fix link to the PR merged in the changelog

---

invoice.go

Fixes https://github.com/stripe/stripe-go/issues/703

Add support for `subscription_cancel_at_period_end` on upcoming invoice

---

countryspec.go

Add support for `supported_transfer_countries` on CountrySpec

---

plan.go

Add support for `flat_amount` on Plan tiers.

---

paymentintent.go
paymentintent/client.go
paymentintent/client_test.go
paymentintent_test.go

The Payment Intent resource had some changes. This PR addresses all the changes. This will be released as a major version and we will automatically return the old shape based on previous stripe-go versions.
cc @danwang-stripe @stripe/api-libraries 

Ship changes to the Payment Intent resource

---

paymentintent.go

Add support for Review on payment intent

---

paymentintent.go

Fixes https://github.com/stripe/stripe-go/issues/726

Add support for `transfer_data` on create/update

---

.travis.yml
refund.go
testing/testing.go

Add missing properties on the Refund resource

---

feerefund.go

Adds support for expanding fee_refund.fee

Use ApplicationFee struct for FeeRefund.Fee

---

invoiceitem.go

Add support for listing invoice items per invoice or pending status

---

issuing_authorization.go

Add support for `wallet_provider` on the Issuing Authorization

---

charge.go

Add support for `transfer_data[destination]` on Charge

---

.travis.yml
accountlink.go
accountlink/client.go
accountlink/client_test.go
testing/testing.go

This API is now considered stable so moving forward with the merge.

Add support for the Account Link resource

---

charge.go

Add receipt_url to Charge

---

.travis.yml
client/api.go
paymentintent.go
paymentintent/client_test.go
paymentintent_test.go
plan.go
sub.go
subschedule.go
subschedule/client.go
subschedule/client_test.go
subschedulerevision.go
subschedulerevision/client.go
subschedulerevision/client_test.go
testing/testing.go

Add support for Subscription Schedule resource

---

account.go
account_test.go

Add support for capabilities on the `Account` resource

---

invoice.go

Quick fix for the package, seems to be what is required for this particular call to work

Make invoice items a slice, as per API spec

---

sub.go

Add `current_period_*` filters when listing Invoices

---

reporting_reportrun.go
reporting_reporttype.go

Related to https://github.com/stripe/stripe-java/pull/689

Add support for columns on Reporting resources

---

terminal/location/client.go
terminal/location/client_test.go
terminal/reader/client.go
terminal/reader/client_test.go
terminal_location.go
terminal_reader.go

Add support for Terminal Location and Reader deletion

---

account.go
person.go

Add support for passing an Account Token on Account or Person creation

---

customer.go

Add support for passing a PaymentMethod id on Customer creation

---

customer.go
invoice.go

cc @stripe/api-libraries @robertcoe-stripe

Add support for address on Customer

---

charge.go

Add ACSS Debit to PaymentMethodDetails

---

issuing_card.go

Add support for replacing an Issuing Card

---

paymentintent.go

Add support for listing PaymentIntents by customer

---

charge.go

Allow listing charges by PaymentIntent id

---

checkout/session/client_test.go
checkout_session.go

Fixes https://github.com/stripe/stripe-go/issues/847

Fix `Items` to be a slice

---

source.go

Fixes https://github.com/stripe/stripe-go/issues/849

Add Customer property on the Source object

---

client/api.go

Fixes https://github.com/stripe/stripe-go/issues/852

Add PaymentMethod to the list of clients

---

customer.go

Add InvoiceSettings to Customer

---

taxid.go

Cf. https://stripe.com/docs/api/customer_tax_ids/object#tax_id_object-type

Add new tax ID types

---

client/api.go

My bad, you added a check specifically for this but I missed it because of the API version mismatch issue :/

Fix earlyfraudwarning client

---

customer.go

Add support for Balance and deprecate AccountBalance on Customer

---

issuing_transaction.go

Add support for `merchant_amount` and `merchant_currency` to Issuing Transaction

---

checkout_session.go

Add support for submit_type to CheckoutSession

---

.travis.yml
client/api.go
creditnote.go
customerbalancetransaction.go
customerbalancetransaction/client.go
customerbalancetransaction/client_test.go
testing/testing.go

Add support for Customer Balance Transaction resource and APIs

---

paymentintent.go

Add CancellationReason to PaymentIntent

---

.travis.yml
invoice.go
invoice/client_test.go
sub.go
sub/client_test.go
subschedule.go
testing/testing.go

* Add support for `CollectionMethod` on `Invoice`, `Subscription` and `SubscriptionSchedule`
* Add support for `UnifiedProration` on `InvoiceLine`

Add support for `CollectionMethod` on Billing resources

---

subschedule.go

Add `DefaultPaymentMethod` and `DefaultSource` to `SubscriptionSchedule`

---

.travis.yml
client/api.go
error.go
paymentintent.go
paymentintent/client_test.go
setupintent.go
setupintent/client.go
setupintent/client_test.go
testing/testing.go

Add support for the `SetupIntent` resource and APIs

---

paymentintent.go
paymentintent/client_test.go

Make sure `OffSession` on `PaymentIntent` can be a bool or an enum

---

paymentintent.go

cc @garrett-stripe @stripe/api-libraries-releasers

Add support for `SetupFutureUsage` on `PaymentIntent` update/confirm

---

checkout_session.go

Add support for SetupFutureUsage on Checkout Session

---

creditnote.go

Add Customer filter when listing CreditNotes

---

paymentintent.go
setupintent.go

Mark challenge_only enum value as deprecated

---

paymentintent.go

Support statement_descriptor on PaymentIntent capture

---

error.go
stripe_test.go

Adding constants for code in https://stripe.com/docs/declines/codes

Add decline code constants

---

issuing_card.go
person.go

Add support for PIN status and Executive on Person

---

checkout_session.go

Add support for `Mode` on Checkout `Session`

---

.travis.yml
invoice.go
invoiceitem.go
plan.go
plan/client_test.go
plan_test.go
testing/testing.go

Add support for decimal amounts on Billing resources

---

issuing_authorization.go

Add support for `Authentication` and `URL` on Issuing `Authorization`

---

.travis.yml
stripe.go
testing/testing.go

r? @brandur-stripe @remi-stripe 
Bump API version to 2019-09-09.

Bump API version to 2019-09-09

---

error.go

Fixes https://github.com/stripe/stripe-go/issues/956
r? @ob-stripe 

Add missing error code

---

source.go

Unmarshalling of Source objects of type `klarna` fail because the `SourceSourceOrder.Items` field is not an array.
Here is an example of a failing json: 
```json
{
"id": "src_1FMulZK5t512iK6Ob6zTJa7u",
"object": "source",
"amount": 2599,
"client_secret": "XX",
"created": 1569495849,
"currency": "gbp",
"flow": "redirect",
"klarna": {
"shipping_first_name": "FirstName",
"purchase_country": "GB",
"client_token": "eyJhbGciOiJSUzI1NiJ9.ewogICJzZXNzaW9uX2lkIiA6ICIwM2ExYzBjZS1mMjNkLTc4YWQtODI1Yy03MjMzOWNjMmIyMDciLAogICJiYXNlX3VybCIgOiAiaHR0cHM6Ly9rbGFybmEtcGF5bWVudHMtZXUucGxheWdyb3VuZC5rbGFybmEuY29tIiwKICAiZGVzaWduIiA6ICJrbGFybmEiLAogICJsYW5ndWFnZSIgOiAiZW4iLAogICJwdXJjaGFzZV9jb3VudHJ5IiA6ICJHQiIsCiAgInRyYWNlX2Zsb3ciIDogZmFsc2UsCiAgImVudmlyb25tZW50IiA6ICJwbGF5Z3JvdW5kIiwKICAibWVyY2hhbnRfbmFtZSIgO …
```

updates SourceSourceOrder Items field to fix unmarshalling errors.

---

terminal_reader.go

Add support for `Status` and `Location` filters when listing `Reader`s

---

taxid.go

Add `TaxIDTypeMXRFC` constant to `TaxIDType`

---

paymentintent.go

Properly pass `Type` in `PaymentIntentPaymentMethodOptionsCardInstallmentsPlanParams`

---

ephemeralkey.go

Addresses feedback from https://github.com/stripe/stripe-go/issues/979
r? @ob-stripe 

Improve docs for ephemeral keys

---

paymentintent.go

Add support for `UseStripeSDK` on `PaymentIntent` create and confirm

---

paymentmethod.go

Add missing constant for PaymentMethod of type FPX

---

bitcointransaction.go
webhook/client_handler_test.go

Hello,
I was just checking out some examples, noticed a couple of typos, and figured I could take a moment to fix them.
Thanks!

Fix comment typos

---

creditnote.go

Related to https://github.com/stripe/stripe-java/pull/907

Add support for `OutOfBandAmount` on `CreditNote` creation

---

refund.go

Adding new refund reason as a valid enum: https://stripe.com/docs/api/refunds/object#refund_object-reason
r? @ob-stripe 

Add new refund reason `RefundReasonExpiredUncapturedCharge`

---

invoice.go

Add support for filtering list of invoices by status

---

mandate.go
paymentmethod.go

@remi-stripe  @ob-stripe
Add AU BECS Debit PaymentMethod Support

Add AU BECS Debit to PaymentMethod

---

taxid.go

Add constant for TaxIDTypeSGUEN on TaxId

---

balancetransaction.go

Add ReportingCategory to BalanceTransaction

---

invoice.go

Fix https://github.com/stripe/stripe-go/issues/1010
r? @ob-stripe 

Add support for `InvoiceItem` and fix `Livemode` on `InvoiceLine`

---

README.md

Move examples to customers

---

account.go

This is currently gated and going out tomorrow

Add support for `Structure` on `Account`

---

taxid.go

Add support for `TaxIDTypeTHVAT` and `TaxIDTypeTWVAT` on `TaxId`

---

paymentintent.go

Add support for `ErrorOnRequiresAction` on `PaymentIntent`

---

file.go

Add `FilePurposeAdditionalVerification` and `FilePurposeBusinessIcon` on `File`

---

checkout_session.go

Add support for `StatementDescriptorSuffix` on Checkout `Session`

---

checkout_session.go

Add support for `Amount` in `CheckoutSessionPaymentIntentDataTransferDataParams`

---

reporting_reportrun.go

Add support for `Timezone` on `ReportRun`

---

issuing_dispute.go

Add new enum values for `IssuingDisputeReason`

---

taxid.go

Add `TaxIDTypeMYSST` for `TaxId`

---

account.go
account_test.go
capability.go
person.go

Add support for `Errors` in `Requirements` on `Account`, `Capability` and `Person`

---

checkout_session.go

Add support for `Shipping` and `ShippingAddressCollection` on Checkout `Session`

---

account.go

Add new capabilities for AU Becs Debit and tax reporting

---

sub.go

Add support for `PauseCollection` on `Subscription`

---

account.go

Add `AccountCapabilityCardIssuing`

---

review.go

Add missing properties on `Review`

---

taxid.go

Add support for `TaxIDTypeSGGST` on `TaxId`

---

.travis.yml
issuing/dispute/client_test.go
testing/testing.go

Fix test suite and latest stripe-mock

---

issuing_card.go

Add support for `CancellationReason` on Issuing `Card`

---

webhookendpoint.go

Add `Description` on `WebhookEndpoint`

---

account.go

Add support for `SecondaryColor` on `Account`

---

charge.go

Add `CardholderName` to `ChargePaymentMethodDetailsCardPresent` on `Charge`

---

issuing_card.go

Fixes https://github.com/stripe/stripe-go/issues/1081
Not sure how I missed that PR, I am sure I wrote it last week 😓 

Add support for expandable `CVC` and `Number` on Issuing `Card`

---

paymentintent.go

Fix wrong comment, no functionality changed.

Fix comment for payment intent constant

---

.travis.yml
client/api.go
invoice.go
invoiceitem.go
price.go
price/client.go
price/client_test.go
price_test.go
sub.go
sub/client_test.go
subitem.go
subschedule.go
testing/testing.go

Adding support for the `Price` resource and APIs

---

balance.go

Add support for `Issuing` in `Balance`

---

account.go

Add `SupportAdress` in `BusinessProfile` on `Account` creation and update

---

issuing_transaction.go

Same as https://github.com/stripe/stripe-java/pull/1030

Add support for `PurchaseDetails` on Issuing `Transaction`

---

checkout/session/client_test.go
checkout_session.go

Fixing `LineItems` to be ` LineItemList` on Checkout `Session`

---

balancetransaction.go
charge.go
invoice.go
issuing_dispute.go
sub.go

Multiple API changes
* Add `issuing_dispute` as a `type` on `BalanceTransaction`
* Add `BalanceTransactions` as a a list of `BalanceTransaction` on Issuing `Dispute`
* Add `Fingerprint` and `TransactionId` in `ChargePaymentMethodDetailsAlipay` on `Charge`
* Add `Amount` in `InvoiceTransferData` and `InvoiceTransferDataParams` on `Invoice`
* Add `AmountPercent` in `SubscriptionTransferData` and `SubscriptionTransferDataParams` on `Subscription`

Multiple API changes

---

charge.go

Add `AuthenticationFlow` to `ChargePaymentMethodDetailsCardThreeDSecure`

---

checkout_session.go

Add support for `ProductData` on `LineItems` for Checkout `Session`

---

account.go

Add support for BACS Debit as a `Capability` on `Account`

---

paymentintent.go
paymentmethod.go

Add support for Bancontact, EPS, Giropay and P24 on `PaymentMethod`

---

checkout_session.go

Add support for `TransferGroup` on Checkout `Session`

---

paymentintent.go
paymentmethod.go

Add support for Cartes Bancaires payments on `PaymentIntent` and `PaymentMethod`

---

charge.go

Add `Mandate`, `InstitutionNumber` and `TransitNumber` to `ChargePaymentMethodDetailsAcssDebit`

---

issuing_dispute.go

Add support for `Transaction` on Issuing `Dispute`

---

lineitem.go

Add support for `Discounts` on `LineItem`

---

file.go

Add `FilePurposeDocumentProviderIdentityDocument` on `File`

---

checkout_session.go

Add support for `AmountTotal`, `AmountSubtotal`, `Currency` and `TotalDetails` on Checkout `Session`

---

accountlink.go

Add support for new constants for `AccountLinkType`

---

lineitem.go

Add support for `Deleted` on `LineItem`

---

person.go

Add support for `PoliticalExposure` on `Person`

---

account.go

Add support for `CartesBancairesPayments` as a `Capability`

---

account.go

Add support for `FPXPayments` as a `Capability` on `Account create and update

---

account.go

Same mistake as https://github.com/stripe/stripe-dotnet/pull/2143

Add support for `FPXPayments` as a property on `AccountCapabilities`

---

.travis.yml
checkout_session.go
client/api.go
coupon.go
coupon/client_test.go
customer.go
discount.go
promotioncode.go
promotioncode/client.go
promotioncode/client_test.go
promotioncode_test.go
sub.go
subitem/client_test.go
testing/testing.go

Add support for the PromotionCode resource and APIs

---

paymentintent.go
paymentmethod.go

Add support for Alipay on `PaymentMethod` and `PaymentIntent`

---

issuing_authorization.go
issuing_transaction.go

Add support for `AmountDetails` on Issuing `Authorization` and `Transaction`

---

account.go
account_test.go

Adding service agreement field to handle limited service agreement in TOS.

add service agreement to TOS

---

checkout_session.go

Add support for `PaymentStatus` on Checkout `Session`

---

bankaccount.go

Add support for `AvailablePayoutMethods` on `BankAccount`

---

discount.go

Add support for `CheckoutSession` on `Discount`

---

charge.go

Add support for `AmountCaptured` on `Charge`

---

balance.go

Add support for `InstantAvailable` on `Balance`

---

stripe.go
stripe_test.go

Currently, the retry logic is written to mostly just be smart about
status codes, like if we see a 409 or 429. We fairly naively retry any
non-Stripe error that comes back from `net/http`.
As pointed out in #1184, we should at the very least handle a context
that's been cancelled or hit its deadline (retries should stop if this
is the case), so I've done that here.
I've also tweaked some of the error logic so that we don't retry on some
types of non-Stripe errors which we know will never succeed. I don't
expect this set to be completely exhaustive, but it gives us a
framework to build on in case we want to add more errors to it in the
future. The current set is inspired by go-retryablehttp.
Fixes #1184.
[1] …

Don't retry requests on context cancellation + a few other errors

---

charge.go
paymentintent.go
paymentmethod.go

Add support for OXXO on `PaymentIntent` and `PaymentMethod`

---

balancetransaction.go

Add support for BalanceTransactionTypeContribution` on `BalanceTransaction`

---

account.go

Add support for new payments capabilities on `Account`

---

README.md

Update version to v72

---

charge.go

Add support for `Description`, `IIN` and `Issuer` on `Charge` for `CardPresent` and `InteracPresent

---

charge.go

Add `PreferredLocales` on `Charge` for payments made via Interac Present transactions

---

account.go

Add support for `RegistrationNumber` in `Company` on `Account`

---

error.go
invoice.go

Add `LastFinalizationError` to `Invoice` and `PaymentMethodType` to `Error`

---

balancetransaction.go

Properly deserialize `IssuingDispute` on `BalanceTransaction`

---

setupattempt.go

Fix bad comments to make the linter happy

---

charge.go
paymentintent.go
paymentmethod.go

Add support for GrabPay as a PaymentMethod

---

invoice.go

Add support for `AccountTaxIDs` on `Invoice`

---

README.md

Add link to YouTube playlist from README

---

.travis.yml
billingportal/configuration/client.go
billingportal/configuration/client_test.go
billingportal_configuration.go
client/api.go
testing/testing.go

Add support for the billing portal configuration API.

add billing portal configuration API

---

account.go

* Add support for `AccountSettingsParams.CardIssuing.TOSAcceptance`
* Add support for `AccountSettingsCardPayments.CardIssuing.TOSAcceptance`

add card_issuing.tos_acceptance to account.go

---

radar_earlyfraudwarning.go

* Add support for `payment_intent` on `RadarEarlyFraudWarning` and `RadarEarlyFraudWarningListParams`.

API Updates

---

account.go

* Add support for `Controller` on `Account`

Add support for account controller

---

checkout_session.go

* Add support for CheckoutSession.URL

Add checkout.Session.URL

---

invoiceitem/client.go

Formatting changes only
cc @dcr-stripe

Make invoiceitem/client.go codegen-able

---

reversal.go

Formatting changes + additional field
cc @dcr-stripe

Make reversal.go codegen-able

---

file.go
file/client.go
filelink.go
price.go
quote.go

Formatting changes and new fields. The first commit is rearranging files manually and the second commit has relevant changes.
Also change formatting for imports in some other resource files.
cc @dcr-stripe
- Add support for `"selfie"` and `"identity_document_downloadable"` as `FilePurpose` options
- Add support for `title` field on `File`

Make File resource and client codegen-able

---

capability.go
sigma_scheduledqueryrun.go

Make the following files codegen-able:
- capability
- sigma_scheduledqueryrun
cc @dcr
- Add support for `disabled` on `CapabilityStatus`

Make more files codegen-able

---

README.md
issuing/cardholder/client.go
payout.go
setupattempt/client.go
transfer.go

r? @yejia-stripe 
Updates various URLs to https://stripe.com/docs/api/go to point to the correct URLs.

Update docs URLs.

---

example/generated_examples_test.go

Add generated tests for payment intent and setup intent verify_microdeposits

Add tests for verify_microdeposits

---

.gitignore
example/generated_examples_test.go
taxid/client_test.go

Use enums in generated samples.

Generate enums in samples

---

.github/workflows/ci.yml

Add feature/** and release/** to PR CI triggers

---

balance.go
checkout/session/client_test.go
checkout_session.go
creditnote.go
financialconnections_account.go
issuing_authorization.go
lineitem.go
reporting_reportrun.go

Update next major branch with generated file updates.
* Remove `Product` on `LineItem`.
* Remove deprecated `CheckoutSessionSubscriptionDataTransferDataParams.items` and `CheckoutSessionSubscriptionDataItemParams`.

Generate files for next major branch

---

checkout/session/client_test.go

Remove deprecated property usage from checkout/session/client_test.go

---

Makefile

Otherwise formatting will crash hard.

Replace import placeholder before running formatting

---

stripe.go

Fixes: https://github.com/stripe/stripe-go/issues/1728
```
BenchmarkInitUserAgent-10    	95851929	        12.20 ns/op
```

Delay calculation of Stripe-User-Agent

---

webhook/client.go

Hi,
I've spotted a minor redundancy in one of the comments.

fix comment

---

Makefile

Right after a major version update when a `master` branch is merged into a `beta` branch we get a mix of versions in imports (master is vN and beta is v(N-1)).
This changes `codegen-format` to replace all version references with the current version.

Update all version in codegen-format

---

stripe.go
stripe_test.go

Would also appreciate a +1 to https://github.com/stripe/stripe-go/pull/1820 as part of this!

Add helper to set beta version

---

README.md

after https://github.com/stripe/stripe-go/pull/1819

Update README to use AddBetaVersion 

---

.github/workflows/ci.yml
Makefile

https://github.com/stripe/stripe-go/pull/1913 for the beta branch

Use pinned version of tools in Makefile and ci.yml (beta)

---

bankaccount.go

to be removed in the next major

Temporarily add payment_method parameter to BankAccountParams

---

justfile

Formatting on a clean repo failed because we couldn't install with invalid go code.
- make sure we normalize imports before formatting

fix justfile ordering bug

---

invoice_test.go
price_test.go

Merge changes from stripe/stripe-go master

---

v2_events.go

Manually creating PRs as automation is currently failing
Re-generating after the latest set of fixes in the codegen around fixing event names and related objects
Re-run code gen

Fix event names and related objects

---

CHANGELOG.md

Update CHANGELOG.md for v82.1.0-beta.3

---

stripe_client.go
webhooks.go

Some comments were missing on exported types.
- Adds comments to some new exported functions.

Improve some comments

---

amount.go

Bug fix, this was causing panic on v2 endpoints that use this type.

Add form information to amount

---

.github/workflows/ci.yml
CHANGELOG.md
README.md
testing/testing.go

- ran `just merge go-beta` and fixed conflicts

Merge go-beta

---

CHANGELOG.md
params.go
params_test.go
search_params.go
search_params_test.go
stripe_context.go

Merge to private-preview

---

example/v2/event_notification_webhook_handler/event_notification_webhook_handler.go
webhook/client.go
webhook/client_test.go
webhooks.go
webhooks_test.go

Merge to beta
