stripe/stripe-go

stripe.go

Fix typo spelling: boudary => boundary

---

recipient.go
recipient/client.go
recipient/client_test.go

This commit adds `Token` support to BankAccountParams.
Fix #62

Add Token support to BankAccountParams

---

invoice/client.go

Upcoming was missing from the end of the URL

modified invoice client to properly use GetNext upcoming url

---

payment_source.go

This PR adds a custom `MarshalJSON` method to `PaymentSource`. Now when the `PaymentSource` object is marshaled, it will represent the same JSON object that it was presented with.
Code:
```
//...
var customer Customer
//...
return json.Marshal(customer)
```
Before Output:
```json
"customer": {
"id": "djndfjkngknjgnkjfnkg",
"sources": {
"data": [
{
"object": "card",
"id": "card_5wey6SaMFjuRx6"
}
]
}
}
```
After Output:
```json
"customer": {
"id": "djndfjkngknjgnkjfnkg",
"sources": {
"data": [
{
"object": "card",
"customer": "djndfjkngknjgnkjfnkg",
"id": "dfjvkjfnknf",
"exp_month": 10,
"exp_year": 2016,
"more_keys": "more_values"
}
]
}
}
```
This fixes #88 
**Edit:** I did some work handling the third case of the switch statement, where the type isn't a `PaymentSourceBitcoinReceiver` or …

Add custom MarshalJSON method to PaymentSource, so it accurately represents the JSON rep. of its type

---

params.go
params_test.go

This adds the ability to include arbitrary key-value parameters in requests using the new `AddExtra` method on the `Params` type. This allows for cases where we're beta testing new parameters in the API but haven't documented them for public release.
A couple explicit decisions that are worth calling out:
* I have no idea if `Extra` is the right name here -- totally open to suggestions.
* We had discussed using a `map[string]interface{}` type for this at one point but I actually don't think this works well. There is no sense of type in URL parameters so short of writing our own serialization (ala https://github.com/google/go-querystring) we can't accept arbitrary types.
* There are no functional tests of this capability since that would either (a) depend on a transient beta feature in the …

Support adding arbitrary key-value params to Stripe requests.

---

customer.go
customer/client_test.go

When you retrieve a customer that has been deleted, the Stripe API returns a property 'deleted' along with a subset of the Customer details. That is missing from Customer struct so I am adding it here along with a test. 
I also fixed an existing test (TestCustomerUpdate) that was failing because no CVC was supplied with CardParams. 
Some formatting fixes too. 
This fixes the issue I raised - https://github.com/stripe/stripe-go/issues/95

Adding Deleted field to Customer

---

customer.go
customer/client.go

The API was updated on [2015-02-18](https://stripe.com/docs/upgrades#2015-02-18) to remove the old Card and DefaultCard
parameters, in favour of Source and DefaultSource.
The codebase was updated in https://github.com/stripe/stripe-go/commit/43e56d28015faea5136409a86cad1664fb321c23 to reflect the new
changes to the API, but the customer params did not get updated at that
time.
This relates to #101.

Rename deprecated customer param value

---

account.go
account/client.go
account/client_test.go

We recently documented a few support/business fields at `/v1/account` (see [here](https://stripe.com/docs/api#update_account)) and this adds a few new fields: `business_primary_color`, `business_url`, `support_email`, and `support_url`. Let me know if any changes need to be made.
r? @cosn

account: Adds new support/business fields

---

CHANGELOG
stripe.go

Follow up from https://github.com/stripe/stripe-go/pull/111, I realized we need to bump the `clientversion`, added pertinent bits to the `CHANGELOG` as well.
r? @cosn

Bump to 6.4.2 and append to CHANGELOG

---

sub.go
sub/client.go

Per the documentation, there's a 'proration_date' field that lets the caller
override the default proration date:
https://stripe.com/docs/api#update_subscription
I wasn't sure what the best way to test this was. If you have any suggestions, I'm happy to update the PR.

Add missing field on subscription params

---

invoice.go

The documentation for the invoice object
https://stripe.com/docs/api#invoice_object
shows that a line may have a subscription (string) and a discountable (bool).
I named the subscription Sub to match the equivalent field on other types in
this package.

Add missing fields to invoice line

---

bankaccount/client.go

Pass **token** or **dictionary** containing a user’s bank account details as
value for `external_account`.
Please see https://stripe.com/docs/api/go#create_bank_account for reference.

Update bank account creation API.

---

client/error_test.go
error.go
stripe.go

While request IDs are never in the Stripe error JSON, I added the
`json:"request_id"` so that the ID will show up when the error is printed.

Add request ID to Stripe errors

---

account/client.go

Pass `country` argument, if provided. This is an optional argument to **POST** `https://api.stripe.com/v1/accounts`.
Please see https://stripe.com/docs/api#create_account.

Send "country" when creating or updating an account.

---

sub/client.go

Originally the proration date got appended to the body of the POST request to create a subscription,
which makes no sense at all.
What we really need, is to add the proration date on the update call.

Move proration date to subscription update

---

charge.go
transfer.go

We have been getting unmarshalling failure on Charges with a Transfer attribute within them.
The "transfer" returned in the Charge response is an ID string, NOT a marshalled Transfer struct.
Example of response from API:
transfer: "tr_16OUxc2pKrqcgQOlXCWTvigk"
Example of unmarshalled stripe.Charge:
stripe.Charge{ID:"\n  \"id\": \"ch_16OUxc2pKrqcgQOlafUGNmP4\",\n  \"object\": \"charge\",\n  \"created\": 1436886284,\n  \"livemode\": false,\n  \"paid\": true,\n  \"status\": \"succeeded\",\n  \"amount\": 1234,\n  \"currency\": \"gbp\",\n  \"refunded\": false,\n  \"source\": {\n    \"id\": \"card_16MzBJ2pKrqcgQOltgAMyQj0\",\n    \"object\": \"card\",\n    \"last4\": \"4242\",\n    \"brand\": \"Visa\",\n    \"funding\": \"credit\",\n    \"exp_month\": 12,\n    \"exp_year\": 2016,\n …

Fix marshalling error of Transfer value, when creating a Charge with Stripe connect.

---

refund.go
refund/client.go
refund/client_test.go

TODO: change `beta_refunds` endpoint before merging, once non-beta endpoints have shipped.
r? @cosn 
cc @kyleconroy 
Note: I added a bunch of error raising because we noticed during debugging that a lot of things wouldn't be caught. If this is too much, let me know and I'm happy to remove.
Also - I wouldn't mind having a test to make sure that the list method works without the charge filter, but this returns a large set of results and I'm not sure verifying the size is straightforward with the returned iterator. Open to suggestions! Or I can leave as is.

Use top level refund endpoints.

---

params.go

in my experience, some stripe accounts have more than 65535 charges.

total_count should be uint32

---

account/client.go
account/client_test.go

Account is correctly updated when I set AccountParams.
However, TOSAcceptance is not updated no matter what is set.
It happens because TOSAcceptance.AppendDetails is not called in the account update.

TOSAcceptance are not updated when account is updated

---

account.go
account/client.go

Updating terms of service, was only supported on Account create, NOT Account update.
Fixes incorrect parameter name on TransferSchedules

Allow TOSAccept on Account update

---

refund/client.go

The refund client was sending `refund_transfer` instead of
`reverse_transfer`. Fixes #133.

Add ability to reverse transfers.

---

error.go

r? @kyleconroy 
cc @cos we want to show the HTTP status code because we now have different ones such as 401, 404, 429, etc. - was there a reason we didn't show this in the first place?

reveal HTTP status code json

---

error.go
stripe.go

r? @cosn Fixes #139 
```go
package main
import (
"log"
"os"
"github.com/stripe/stripe-go"
"github.com/stripe/stripe-go/charge"
)
func main() {
stripe.Key = "sk_live_token"
chargeParams := &stripe.ChargeParams{
Amount:   400,
Currency: "usd",
Desc:     "Charge for test@example.com",
}
chargeParams.SetSource(&stripe.CardParams{
Number: "4000000000000002",
Month:  "12",
Year:   "2020",
CVC:    "123",
})
_, err := charge.New(chargeParams)
if serr, ok := err.(*stripe.Error); ok {
log.Println(serr.ChargeID)
}
}
```

Add charge ID to errors

---

account.go
account/client.go
account/client_test.go

Allows accounts to be updated with an `external_account` as defined in
the API.
I've tried to follow the pattern demonstrated in the "recipient"
resource here, but I'm not totally sure if it's fully correct.
Fixes #144.
/cc @kyleconroy Mind taking a look at this? Thanks!

Add `external_account` parameter for account update requests

---

sub/client.go
sub/client_test.go

When you cancel a subscription it now returns the subscription object
instead of just an error.
r? @brandur 
Fixes #150. Supersedes #151.

Return the resource when canceling a subscription

---

account/client.go

Creating an account with a different country to the platform account causes an error
type: "invalid_request_error"
message: "Address for business must match account country"
param: "legal_entity[address][country]"
This is because the country parameter is not being populated in the API request.

Include country on account requests

---

account/client_test.go
order/client_test.go
plan/client_test.go
sub/client.go

* Properly pass the Currency when creating an ExternalAccount.
* Only attempt to retrieve the plans the test just created
* Create a new product and SKU for each Order test. This might be an issue
over time as you can't delete Product and SKU.
r? @brandur

Fix failing tests

---

bankaccount.go

As mentioned in #164, it's pretty confusing that these parameters
contain both an `Account` and an `AccountID` with neither being
documented. To make matters worse, `Account` was improperly named
and should actually be called `AccountNumber`. This patch adds a small
amount of documentation to help point out the distinction.
/cc @remistr Mind giving this one a quick review?

Provide some nominal documentation for `BankAccountParams`

---

order/client.go

Had an issue creating orders for accounts, the SetAccount would not work. Figured it had something to do with the params not being passed to the request. This PR fixes this issue.

Fix Order.New commonParams issue

---

sub/client.go

This was previously accepted on subscription creations, but not updates.
The [docs][docs] on update indicate that it can be used in both places:
> Unix timestamp representing the end of the trial period the customer
> will get before being charged for the first time. If set, trial_end
> will override the default trial period of the plan the customer is
> being subscribed to. The special value now can be provided to end the
> customer's trial immediately.
Fixes #176.
[docs]: https://stripe.com/docs/api#update_subscription

Support special `now` value for trial end on subscription update

---

order/client.go

This PR adds OrderParams to the order Get call, this way its possible to retrieve orders that have been created on another account. Without the params there is no way to set the account and the order will 404.

Add OrderParams to order Get

---

customer.go

Attempts to update the country of a customer's shipping address were previously setting the country to null.

Allow update of the country field in customer shipping details.

---

recipient/client.go
recipient/client_test.go

As described in #184, we allow a bank account to be referenced by a
token when creating a new recipient, but we currently don't allow the
same when updating a recipient. This patch addresses that problem.
Fixes #184.
/cc @remistr Would you mind taking a review pass on this one? Thanks!

Allow a recipient's bank account to be updated by token

---

card.go
card/client_test.go

You can now update a card's expiration month or year. Added extra tests
to ensure this didn't break existing behaviour.
fixes #186 
r? @brandur

Added the ability to update a card's expiration date

---

account.go
account/client_test.go

The bindings now surface SSNProvided, PersonalIDProvided and BusinessTaxIDProvided
r? @brandur 
Extra fields for Kana and such will be added in a separate PR later

Added support for new fields in LegalEntity

---

README.md

Adds instructions to the `README` for running single tests or tests from
a single subpackage.

Adds instructions for running individual tests

---

invoice.go
invoice/client.go
invoice/client_test.go

Adds a large set of missing parameters to `InvoiceParams` that are
designed to be used to [retrieve an upcoming invoice][docs]. Fixes #198.
A few design justifications here:
* I've continued using the prefix of `Sub` for "subscription" because
this seems consistent with elsewhere in the library.
* The new parameter serializations should really be tested as a unit
somewhere, but because we don't have a pattern for this, I've re-used
the same approach as elsewhere in the suite by just hitting the API.
* I've made the single huge test in the invoices suite even more huge
because as stated in its comments, there's a huge amount of
bootstrapping that's needed in order to properly test any of this.
* I've only made minimal effort to test the invoice which the API
responds with. This is because …

Add missing invoice parameters for use with `GetNext`

---

token.go
token/client.go
token/client_test.go

r? @brandur 
`POST /v1/tokens` needs to be able to accept `pii[personal_id_number]` to create PII tokens
Made the simplest change possible. Open to suggestions.

bindings for PII tokenization

---

account.go
account/client_test.go
account_test.go
stripe.go

Follows the [changelog][changelog] through and makes necessary changes to support the latest Stripe API version.
Important changes:
* `BankAccounts` on `Account` replaced by `ExternalAccounts`.
* `Currencies` on `Account` removed in favor of new `CountrySpec` resource.
There were quite a few other changes in the API too, but they were either already integrated or didn't require any modifications to the bindings.
Fixes #205. Supersedes #169.
/cc @mmcgrana Sorry to be a pain, but would you mind taking a look at this one? Thanks! (And BTW the tests are still broken due to a _still_ in progress test data deletion :/)
[changelog]: https://stripe.com/docs/upgrades

Upgrade to API version 2016-03-07

---

Makefile
scripts/check_gofmt.sh
sub/client_test.go

This changes the CI run so that `go vet` and a `gofmt` check are run.
This will make the process of finding formatting problems on
contributions automatic.

Add `go vet` and `gofmt` check to CI

---

card.go
card/client_test.go

Adds a missing metadata field (Meta) to the Card resource.
Fixes #214.

Add metadata field to Card resource

---

card.go

Adds a set of fields for specialized use that may be available depending on
gating, but which usually are not.
Replaces #220.

Add internal fields for card

---

charge.go
charge/client_test.go

This PR adds `charge.Outcome` which is an embedded struct that contains the outcome pertaining to a particular charge. The motivation is to freshen the Go bindings in preparation for the imminent `outcome` field in the charge responses from the API.
r? @brandur

	charge: add outcome fields

---

invoice.go
invoice/client.go
sub.go
sub/client.go
sub/client_test.go

Introduces a new field for `TaxPercentZero` for invoices in
subscriptions so that an already non-zero value can be zeroed out (the
current check prevents a zero from ever making it to the server because
it's not added to the serialized form of parameters).
This might be a little contentious, but I didn't add any tests for the
new fields. Sub's `QuantityZero` field does have a test, but it's sixty
lines long and tests a single conditional branch, which doesn't seem
sustainable to me from the standpoints of either code quality or the
amount of time that it takes to run the suite (given that all of these
are still doing live API calls). Definitely open for discussion if
anyone has strong opinions on the subject.
Fixes #225.
/cc @tetrakai Would you mind taking a review pass on this one? …

Introduce `TaxPercentZero` field for invoice and subscription parameters

---

plan.go
plan/client.go

Moves the struct used to represent a list of plans into an exported type
to ease mocking of API endpoints.
Fixes #227.

Expose `stripe.PlanList`

---

invoice/client.go
sub/client.go

Follows up #226 by adding `TaxPercentZero` handling to the update
methods for invoices and subscriptions.

Add TaxPercentZero logic to update methods

---

account/client_test.go
bankaccount/client.go

Fixed the ability to create a new external account on a managed account from a token and mark it as default at the same time.
r? @brandur

New external accounts can be marked as default from a token

---

README.md

Google got away with non-qualified names for a long time. See note in
the appengine README here for more details:
https://github.com/golang/appengine#2-update-import-paths
Fixes #232.

Update Google App Engine import paths in README

---

discount/client.go
sub.go
sub/client.go
sub/client_test.go

This PR adds go support for v1/subs - methods on subscriptions that no longer require a customerID
Changes:
DelSub now only takes in a subscriptionID and not a customerID anymore
All URLs are now directed towards v1/subs rather than v1/cus
All functions have been changed to support if params passed in are `nil` - previously params had to include customerID but now it is possible they are `nil` values
List now takes in optional customer and plan parameters 
Added test to ensure both old and new methods still work

Add support for go sub functions not passing in customer

---

card/client.go

We didn't send the `default_for_currency` parameter for cards on managed accounts
r? @stripe/api-libraries

Allows setting Default for cards on managed accounts

---

client/api.go

perhaps this was done on purpose for a good reason, but Sku isn't included on the client API struct and I wanted to be able to use it and would like to think I'm not the first one.  This just adds it real quick
I was not getting all the tests to pass even though I'm quite certain I was setting my test key correctly (and also noticed at least in the client directory that the key is hardcoded anyway).  Hoping this PR is still viable.

add Skus to the client API struct

---

bankaccount/client.go

When tokenizing a bank account, the routing number is only required
for US bank accounts. If using an IBAN for `account_number`, then
this field is optional. Prior to this commit, `routing_number` was
always being sent, even as a an empty string which was causing the
following error to be sent back from the Stripe API:
{
"type":"invalid_request_error",
"message":"Invalid bic",
"param":"bank_account",
"request_id":"req_XXXYYYZZZ",
"status":400
}
Relevant docs URL: https://stripe.com/docs/api/go#create_bank_account_token-bank_account-routing_number
Signed-off-by: Zach Wick <zwick@stripe.com>

Makes routing_number only be sent in POST if set

---

bankaccount.go

Related to pull #247 , also when need to create token for bank account, routing_number is optional according to documentation [https://stripe.com/docs/api#create_bank_account_token](url)

Fix to Pull #247

---

error.go
stripe.go
stripe_test.go

Adds specific types for all specific errors that can be returned by the Stripe API. These types are then grafted onto the common `stripe.Error` under the new field `Err` so that a user can access type-specific information about the error.
Usage looks a little like:
``` go
_, err := // Go library call
if err != nil {
stripeErr := err.(*stripe.Error)
if cardErr, ok := stripeErr.Err.(*stripe.CardError); ok {
fmt.Printf("Card was declined with code: %v\n", cardErr.DeclineCode)
} else {
fmt.Printf("Other Stripe error occurred: %v\n", stripeErr.Error())
}
return nil, err
}
```
The change is designed to overhaul the error system in a way that enables access to important features, conforms to standard library convention (see [`net.OpError`](https://golang.org/pkg/net/#OpError)), and all the while …

Overhaul the errors subsystem

---

README.md

Normalizes all code intentation in the README to use tabs which is Go's
convention. Gets rids of two-space indentation and tab indentation
that's been expanded to four spaces.

Normalize indentation in README

---

params.go
params_test.go

Adds a helper on `RequestValues` to convert it to a `url.Values` map.
This allows objects to be compared in an order-invariant way, which
might be useful in testing.
See #255.

Add `ToValues` to convert `RequestValues` to `url.Values`

---

customer.go
customer/client.go
customer/client_test.go

r? @brandur 
Introduces a new field `BalanceZero` for customers so that an already non-zero value can be zeroed out. It's modeled on the `TaxPercentZero` behavior.
I added a test to the existing `TestCustomerUpdate` subpackage. Let me know if you prefer it to be separated.
Fixes #261

Introduce `BalanceZero` field for customer parameters

---

card.go

It's shown in the API docs but not in the struct. https://stripe.com/docs/api#card_object-tokenization_method

Add Tokenization Method to Card object

---

customer.go
customer/client.go
customer/client_test.go

It seems that this field is missing for the customer create method. This
change reflects the pattern that we already have for `tax_percent` in
`sub.go`.
Fixes #264.

Add `tax_percent` paramter to customer create

---

sku.go
sku/client.go

cc @jimdanz 
A couple of minor fixes for SKUs:
- We don't have a `Name` attribute on SKUs
- We support updating the product of a SKU, and `sku.Update` should support that as well

Fix SKU attributes, send product.

---

order.go

Just bringing this to parity with our API objects: https://stripe.com/docs/api#order_object-returns

Add returns to orders.

---

stripe.go

We're a few versions behind, this PR bumps us to the most recent API version.

Bump API version.

---

sub/client.go
sub/client_test.go

Using the Golang client there isn't a way to update a subscription `Quantity` to `0`. This should hopefully resolve that!
It seems awhile back this functionality was added for creating subscriptions, but never implemented for updating them. Reference: #36

Using SubParams.QuantityZero in subscription update action

---

invoice.go
invoice/client.go
invoice/client_test.go

r? @brandur 
fixes #273 
This commit adds a `NoClosed` parameter to the `InvoiceParams` struct to fix the fact that passing a `false` value to `Closed` would be ignored. You just need to pass `true` to this parameter to reopen the invoice.

adds NoClosed parameter to open an invoice

---

account/client.go

We actually have two of these in `writeAccountParams`. Take one out.
cc @guillaumehenriot

Strip duplicate country conditional

---

account.go
account/client.go
account/client_test.go
recipient.go

r? @brandur 
fixes #281
This commit adds support to allow migrating Recipients to Accounts. It also adds the MigratedTo property to the Recipients so you can retrieve it.

add support to migrate recipients and update debit_negative_balances property

---

invoice.go

Just adds `ReceiptNumber`. Apparently I'm using an older version of the API, feel free to ignore if this field is no longer relevant! I imagine it's not really "secure" to expose any stripe id's though, and this one looks a bit nicer haha.

add missing Invoice.ReceiptNumber

---

refund/client.go

Updated to match the Charge client. Prevents nil pointer exception when passing a nil params argument.

allow nil params when getting a refund

---

fee.go

The diff looks bigger than it is... only added line 30 for the `OriginatingTransaction` property.

include originating transaction on application fee object

---

balance.go

This updates `Transaction.Src` to follow the same pattern as [PaymentSource](https://github.com/stripe/stripe-go/blob/master/payment_source.go#L97) to allow for expanding the polymorphic source property.
Note that there may be other object types that are valid for "source", but because they aren't listed anywhere I only added the ones I was aware of. If an unknown source shows up, it will still fall back gracefully to only having the `ID` field populated.

support expanding transaction sources

---

account.go
account_test.go

Adds a lot of missing fields to account's legal_entity; most focusing on
alternate fields for Kana and Kanji. This also refactors address
encoding so that we can re-use it in a whole bunch of other places.
Fixes #301.
r? @guillaumehenriot Mind taking a quick look at this one when you get a
chance? Thanks!

Add various missing fields from legal_entity

---

account.go
account/client_test.go

It fixes #308.
Prior to that we needed to pass Type and the full DOB to update Legal Entity. These parameters are now checked to see if empty like everything else.
r? @brandur

Removes the need to pass DOB and Type to update Legal Entity

---

bankaccount.go
bankaccount/client.go
bankaccount/client_test.go

Currently, we've got bank account operations tied specifically to
accounts, when they actually should be keyable to a customer as well
(for some reason delete was implemented as expected, but this goes for
list/retrieve/create). This meant that some of the code that we had in
our documentation wasn't valid:
card.List(&stripe.BankAccountListParams{Customer: {CUSTOMER_ID}})
This patch allows the library to switch off of a customer key as well as
an account key.
Fixes #312.

Allow bank account operations to keyed to customer

---

sub.go
sub/client.go
sub/items_test.go
subitem.go
subitem/client_test.go

We were sharing a single struct between two API calls. This made things
confusing, as certain parameters were not allowed. Also remove the
per-item proration parameters, as those are not supported.

Split sub item param structs into two.

---

refund.go
refund_test.go

This flips the type of Refund.Charge to be a *Charge instead of a
string. 'charge' is expandable when querying for refunds, so the type
needs to be the object.
Unfortunately this is a breaking change for people already using
Refund.Charge.

Fix issue #324: Refund.Charge should be a *Charge

---

invoiceitem.go
invoiceitem/client.go

Currently, `Discountable` cannot be explicitly set to `false`, which is
a problem because for certain types of invoice items it will be
implicitly set to true on the server side.
This patch adds `NoDiscountable` which allows an explicit `false`. This
is modeled after current SDK convention (for exmpale `NoClosed` as part
of `InvoiceParams`).
Fixes #329.
r? @kyleconroy Hey Kyle, would you mind taking a look at this? Thanks!

Add `NoDiscountable` to `InvoiceItemsParams`

---

sub.go
sub/client.go

I wanted to be able to request subscriptions that had been canceled (potentially other statuses later) and the docs showed how to do it with the "status" field(https://stripe.com/docs/api/go#list_subscriptions), but that field wasn't present in the Go library, so this adds it.
I tested it out locally on my machine and it works.  I didn't actually run `make tests` though because the last PR I submitted I was told "Unfortunately, a large part of the test suite doesn't currently run in CI and is therefore very prone to failure as it falls out of date for one reason or another. This looks good as is!"

add the status field to the request for listing subscriptions

---

error.go
stripe.go

One note - our error-checking logic doesn't actually look at the HTTP status code, but rather the error code returned by Stripe. Thus we'll need to ensure that `permissions_error` corresponds to 403.
r? @brandur

Support api permissions errors

---

account.go
charge.go
charge/client_test.go
review.go

This pull request adds support for the `Review` resource (available as a `review` parameter in the `/v1/charges` response), the parameter supports both string IDs and expansion as other Stripe resources. The documentation for the resource has been added to the site here: https://stripe.com/docs/api#reviews.
r? @brandur

charge: add Review type, expansion on charge

---

client/api.go

api.Client doesn't provide access to paymentsource.Client and
paymentsource.Client doesn't provide a constructor similar to
api.Client.

Add paymentsource.Client to api.Client

---

customer/client.go
invoice/client.go
sub/client.go

We used to only support two decimals for tax_percent, but realized later
that we needed four. The API was updated to properly support this, but
the Go bindings continued to truncate to two.
This patch fixes that problem.
Fixes #350.
r? @grey-stripe Hey Marc, can you take a look at this? Thanks!

Truncate tax_percent to four decimals instead of two

---

invoice.go

This appears to have been introduced accidentally and not actually used.
Fixes #352.
r? @ob-stripe Would you mind taking a look at this one? Thank you!

Remove the `SubProrationDateNow` parameter

---

sub/client.go

This resolves the typo outlined in the following issue: https://github.com/stripe/stripe-go/issues/355
It seems like this might be a thing to add test coverage for? I'm not familiar enough with the library to know the best way to approach that.

Fix the Subscription TrialPeriod param to use proper value

---

charge.go

I haven't been able to add tests for this because in Test mode that hash seems to always been empty.

Added support for outcome[rule] on Charge object

---

charge.go
charge/client.go
transfer.go
transfer/client.go

Adds [transfer_group](https://stripe.com/docs/connect/transfer-group) support to the api client.
Desired functionality:

add support for transfer_group param

---

payment_source.go

Add support for account debits. In reality it already worked and was close to fine as-is -- the only problem I found was jsonifying the response. This addresses that.
cc @stripe/api-libraries r? @brandur-stripe

Add support for account debits

---

.travis.yml

Start testing Go 1.7 and latest (with failures allowed for the latter).
Also start testing OS X and Linux separately.

Start testing Go 1.7 and latest

---

charge.go
charge/client.go

Don't merge right away.
Changes the calling convention for creating destination charges from specifying a destination string to using a struct that supports `destination[amount]` and `destination[account]` to match the new, public API: https://stripe.com/docs/api#create_charge-destination
Making a Charge with the proposed struct looks like this:
```go
chargeParams := &stripe.ChargeParams{
Amount:        1000,
Currency:      "usd",
TransferGroup: group,
Dest: stripe.DestinationParams{
Amount:  500,
Account: accountId,
},
}
```
Thoughts:  I called it `DestinationParams` and went with a `string`/`uint64` because that matched some of the conventions: I considered just calling it `Destination` and using an `*Account` but we only appear to do that on the serialization side (which I think makes …

support destination hash

---

invoice.go
invoice/client.go
invoice/client_test.go
sub.go
sub/client.go
sub/client_test.go

This PR adds and tests new invoicing related parameters:
Subscription model: billing, days_until_due
Subscription create: billing, days_until_due
Subscription update: billing, days_until_due
Invoice model: billing, due_date, number
Invoice create: billing, days_until_due, due_date
Invoice update: paid
Invoice list: subscription

Add invoicing params

---

sub.go
sub/client.go

From what I can tell, `all` is a valid status value. https://stripe.com/docs/api/go#list_subscriptions-status
Does this seem reasonable?

Add subscription status all as a constant

---

fileupload.go
fileupload/client_test.go

Added support for files to be uploaded from any generic reader so long as a filename can be provided. Also added a test for the new parameters.
The old parameters still work for backwards compatibility, although there is a comment in the code marking them as deprecated.

File upload no longer requires the file to be on disk (#374)

---

account.go
account/client_test.go

I fixed the ability to unset additional owners on managed accounts.

Accounts can be marked with 0 additional owners

---

account.go
account/client_test.go

This follows up the idea #376 that allows additional owners under an
account's legal entity to be emptied, but tweaks the implementation a
little bit to better match some other parts of the code.
We've introduced `CouponEmpty` under `Customer` to enable the same
thing, so lets re-use that convention here.

Introduce AdditionalOwnersEmpty

---

invoiceitem.go

adding missing `InvoiceItem` fields: 
```
diff --git a/invoiceitem.go b/invoiceitem.go
index a8d96b3..c9d3a69 100644
--- a/invoiceitem.go
+++ b/invoiceitem.go
@@ -31,6 +31,8 @@ type InvoiceItem struct {
Currency     Currency          `json:"currency"`
Customer     *Customer         `json:"customer"`
Date         int64             `json:"date"`
+       Period       *Period           `json:"period"`
+       Plan         *Plan             `json:"plan"`
Proration    bool              `json:"proration"`
Desc         string            `json:"description"`
Invoice      *Invoice          `json:"invoice"`
@@ -38,6 +40,7 @@ type InvoiceItem struct {
Sub          string            `json:"subscription"`
Discountable bool              `json:"discountable"`
Deleted      bool …
```

adding InvoiceItem fields

---

account.go

Additional owners for a managed account in a country that requires them can now submit the ID of their identity document.

Add support for manage accounts to send ID documents for additional owners

---

charge.go
dispute.go
stripe.go

Upgrades the pinned API version to [2017-02-14](https://stripe.com/docs/upgrades#2017-02-14) and introduces appropriate changes. This mostly includes adding an `UnmarshalJSON` implementation for dispute and charge outcome's rule, both of which have become fields that are expandable but collapsed by default.
cc @remi-stripe

Upgrade the pinned API version to 2017-02-14

---

balance.go
balance/client.go

This fixes something I missed when doing the Payout/Transfer split. When listing all balance transactions bundled in a payout you need to pass the payout id, po_XXXXX, in the `payout` parameter instead of `transfer.

Balance history can be filtered by Payout and not Transfer

---

order.go
order/client.go
order/client_test.go

Adds support for the `coupon` parameter on order [creation](https://stripe.com/docs/api#create_order-coupon). Also only send the description for an Order Item if it's set. Today, if you don't set it you get an error even though it's [optional](https://stripe.com/docs/api#create_order-items-description).

Coupon allowed on order creation and optional description

---

stripe.go
stripe_test.go

It turns out that the go bindings were not sending our JSON `X-Stripe-Client-User-Agent` like the other bindings. This PR fixes that to put it inline with everything else.
r? @ob-stripe 

Encode and send `X-Stripe-Client-User-Agent`

---

README.md
stripe.go
stripe_test.go

Adds app info the Go libraries (the idea is already in PHP and Ruby).
r? @ob-stripe 
---
~~Note: currently targets the branch in #391 until that's merged.~~

Add app info to stripe-go

---

account.go

Adds DetailsCode to IdentityVerification because it's missing and is expected to be there.
I thought about adding constants for the available values, but they're so long and ugly that I'm not sure people would end up using them anyway. Thoughts?
``` go
IdentityVerificationDetailsCodeFailedKeyedIdentity       IdentityVerificationDetailsCode = "failed_keyed_identity"
IdentityVerificationDetailsCodeFailedOther               IdentityVerificationDetailsCode = "failed_other"
IdentityVerificationDetailsCodeScanCorrupt               IdentityVerificationDetailsCode = "scan_corrupt"
IdentityVerificationDetailsCodeScanFailedGreyscale       IdentityVerificationDetailsCode = "scan_failed_greyscale"
IdentityVerificationDetailsCodeScanFailedOther           IdentityVerificationDetailsCode = …
```

Add DetailsCode to IdentifyVerification

---

Makefile

Right now `STRIPE_KEY` gets pulled from an encrypted Travis variable
which has a few disadvantages:
* It's really opaque. I have to go to Splunk to reverse engineer which
merchant it belongs to every time I need to look at it (the Travis secret
is not reversible, even to us).
* It means there's no easy local testbed. Everyone who tries to run the
Go test suite needs to go find their own merchant to use. This is
painful.
Storing keys in plaintext like this is of course a little weird, but
we're already doing it in pretty much every other library, and it's a
testmode key on an account that's test-only.
r? @ob-stripe

Move STRIPE_KEY into code

---

invoice.go
invoice/client.go
invoice/client_test.go
sub.go
sub/client.go
sub/client_test.go

- Adds `billing` and `due_date` filters to Invoice list parameters.
- Adds `billing` filter to Subscription list parameters.
- Refactors `invoice/client_test.go` to add helper methods to create test objects (for testing list filters).
- Changes `sub/client_test.go` to create both `charge_automatically` and `send_invoice` Subscriptions (for testing list filters).
- Caps the number of results iterated over when testing `List(nil)` for subs, since accounts with lots of test data will try to iterate over everything AFAICT
```
go test ./sub
go test ./invoice
```
both pass.
Note that the Travis CI tests seem to be breaking on this branch due to unrelated (?) reasons.

Add invoicing params to Invoice and Subscription list methods

---

bankaccount/client.go

This ensures that we send extra parameters such as the Account on bank account deletion on a customer saved on a connected account.

Pass extra parameters on bank account deletion

---

params.go
params_test.go

fixes #401 
@brandur-stripe I wasn't able to run the tests so I'm not 100% sure this works, but it seems right :)
the error I get when I do a `make test`:
```
./params_test.go:38: values.Get undefined (type *stripe.RequestValues has no field or method Get)
[a few more of the same]
```
presumably because I'm building against the released version of stripe-go, and not the modified one that has my new method?  Sorry if this is an obvious thing, I'm a Go n00b.

Add 'Get' method to RequestValues

---

plan/client.go
plan/client_test.go

Seems to be missing from the plan update and is supported by rest api 
and is documented as allowed, even though its being ignored - https://stripe.com/docs/api/go#update_plan-trial_period_days

Add trial_period_days to plan update method

---

account.go
account/client.go
account/client_test.go
bankaccount/client_test.go
payout/client_test.go
transfer/client_test.go

When creating an account via the API, you should now pass the `type` parameter explicitly instead of `managed`.
r? @brandur

Add support for the new account type

---

event.go

This field is being renamed on a new API version for tomorrow (and we need to bump the version used by stripe-go before bringing it in).
Given that this is mostly a change in how we map our JSON serialization, I haven't changed any tests for this one.

Rename `user_id` to `account`

---

stripe.go

All the necessary changes are already in master.

Bump the supported API version to 2017-05-25

---

README.md
account/client_test.go
balance/client_test.go
card/client_test.go
charge/client_test.go
client/checkin_test.go
customer/client_test.go
dispute/client_test.go
example_test.go
invoice/client_test.go
order/client_test.go
orderreturn/client_test.go
paymentsource/client_test.go
payout/client_test.go
refund/client_test.go
reversal/client_test.go
sub/client_test.go
sub/items_test.go
subitem/client_test.go
threedsecure/client_test.go
token/client_test.go
transfer/client_test.go

This PR aims to use the new test tokens such as tok_visa instead or hardcoding raw PANs in the test suite.
There's one last PAN we can't remove for disputes as it hasn't been released yet as a token ready-to-use.

Remove raw PANs from our test suite

---

invoice.go
invoice/client.go

This adds support for the `subscription_items` parameter for the upcoming invoice endpoint.
r? @brandur

Support subscription_items on the upcoming invoice endpoint.

---

invoice.go
invoice/client.go

When previewing an upcoming invoice, you can also simulate changes to the subscription. Changing the plan for example works. Setting the `quantity` to 0 was not working because this parameter is ignored in the code.
This adds `SubQuantityZero` as a valid parameter, mimicking what we do for the subscription update in the rest of the library.
r? @brandur

Support setting the sub's quantity to 0 for an upcoming invoice

---

subitem/client.go

1. Update Subitem List client to use the SubItemListParams
2. Pass subscription to the request params directly from the SubItemListParams rather than the Filters.

Subitem List Fix

---

webhook/client.go

Fixes #405.
webhook.ConstructEvent creates a stripe.Event and verifies the signature and timestamp.  Since go doesn't have default parameters, the `tolerance` param is required.  I added two constants `ToleranceDefault` with the suggested 5 minute tolerance, and `ToleranceIgnoreTimestamp` which disables checking the timestamp.

Implement webhook.ConstructEvent.

---

source.go
source/client.go
stripe.go

Adding support for creating sources with customer as shown by the curl
below:
curl -X POST \
https://api.stripe.com/v1/sources \
-H 'authorization: Bearer sk_test_xxxxxxxxxxxxxxxxxx' \
-H 'content-type: application/x-www-form-urlencoded' \
-H 'stripe-account: acct_xxxxxxxxxxxxxxxx' \
-d 'customer=cus_xxxxxxxxxxxxx&usage=single_use'

Support for creating sources on connected accounts with customer

---

bankaccount/client.go

As mentioned in #426, when retrieving a bank account with a customer ID,
it should be passed into the URL, but we are incorrectly passing an
account ID instead.
Fixes #426.

Fix retrieving a bank account with a customer

---

invoice.go
invoice/client.go
invoice/client_test.go

cc @stripe/api-libraries @ark-stripe
Users can now provide a `source` parameter when paying invoices. Previously, the Go library let users pass creation/update params when calling `Pay` which is not what we want. This PR adds a new `InvoicePayParams` struct to handle parameters for this specific API request. Currently, the only accepted parameter is `Source`.

Add parameters when calling `pay` on an invoice

---

Makefile
customer/client_test.go
ephemeralkey/client_test.go
loginlink/client_test.go
refund/client_test.go
reversal/client_test.go
sub/client_test.go
webhook/client_handler_test.go

This patch changes the CI based test command from `./client` to `./...`.
For now, the `TestCheckin*` filter is still applied, meaning that no
additional tests are run, but the change is that at least now we try to
compile every single subpackage in the project.
It turns out that there were quite a few basic syntax errors that had
creeped into various packages, and even on some of our newer ones, which
suggests that people probably aren't even checking tests locally before
sending to CI (meaning that they have never successfully run even one
time).
Anyway, unfortunately this is still far from a perfect fix, but brings
us a step closer to something a little more sane.

Compile all tests in CI (even if they're not run)

---

invoice.go
invoice/client.go
sub.go
sub/client.go

Via Stripe Connect, you can set an `application_fee_percent` on a subscription or an `application_fee` on an invoice. This can be set to 0 but as usual the Go library does not support this.
This PR fixes the bug by introducing `FeePercentZero` and `FeeZero`.
r? @brandur

Application fee can be set back to 0 on Invoice and Subscription

---

stripe.go
stripe_test.go

Use Bearer auth instead of Basic auth for API requests. Similar to https://github.com/stripe/stripe-node/pull/379.

Use Bearer auth

---

charge.go
charge/client.go
sub.go
sub/client.go

Reading the documentation, there is a functionality of adding an OnBehalfOf parameter When creating separate charges:
https://stripe.com/docs/connect/charges-transfers#on-behalf-of
This is also the case for creating subscriptions, however it is not currently documented in the official documentation.

Add missing OnBehalfOf

---

bankaccount.go
bitcoinreceiver.go
card.go
paymentsource.go
source.go

At some point we added a `Displayer` interface that worked with certain
payment sources to display a short human readable string.
This hasn't turned out to be maintained very well, and is a convention
that's so localized to one small part of the library that it's not very
useful in practice. Here we drop `Displayer` and its associated
implementations.
I doubt this has wide use, but it's a breaking change nonetheless.
Fixes part of #449.

Remove Displayer and Display

---

charge.go
charge_test.go

Drop `ChargeParams.Dest` in favor of `ChargeParams.Destination.Account`,
which is aligned with how the API is designed. This also allows us to
completely drop a custom `AppendTo` implementation on `Charge`.
Fixes part of #449.
r? @remi-stripe Sorry about the boatload of reviews, but I'd previously
discussed this one with you as well.

Drop ChargeParams.Dest

---

account.go
form/form.go

Here we optimize the `AppendTo` function of the form package and its
associated helpers. As #446 came in, there was some concerns expressed
around its performance. This implementation might not be as quick as a
bunch of `if` statements, but it's pretty fast.
Before:
$ make bench
go test -bench . -run "Benchmark" ./form
goos: darwin
goarch: amd64
pkg: github.com/stripe/stripe-go/form
BenchmarkAppendTo-4       500000              2767 ns/op
PASS
ok      github.com/stripe/stripe-go/form        1.480s
After:
$ make bench
go test -bench . -run "Benchmark" ./form
goos: darwin
goarch: amd64
pkg: github.com/stripe/stripe-go/form
BenchmarkAppendTo-4      2000000               922 ns/op
PASS
ok      github.com/stripe/stripe-go/form        2.867s
Which shows roughly a 3x speedup. Encoding a fairly …

Build a type encoder caching system for the `form` package

---

charge.go

Unfortunately I forgot about this one before releasing, but it doesn't
appear that `Token` on `ChargeParams` is used anywhere and I can't find
it in any of the charge-related documentation on the API reference.
@remi-stripe Thoughts?

Remove Charge.Token

---

source.go
source_test.go

The TypeData values are specific to each source type. When the parameters are sent, they have to be passed to the API under the source's type's name so for 3DS you pass `three_d_secure[card]` for example while for Sofort you pass `sofort[country]`.
This uses a custom `AppendTo` for `SourceObjectParams` so that the `TypeData` properties are looped over and encoded with the right level based on the current Source's type.
I've confirmed it works for 3DS now but I was not sure if there was an easier way that looping over `p.TypeData` ourselves.
Fixes https://github.com/stripe/stripe-go/issues/460

Fix Source creation so that TypeData is passed properly

---

bitcoinreceiver/client.go
bitcoinreceiver/client_test.go

Like we're doing elsewhere, this removes Bitcoin receiver tests and
marks the package deprecated in favor of using the new sources API.
These tests still work for now, but they'll break the next time we
upgrade stripe-mock which doesn't provide create/update endpoints. I've
left in the get/list tests because those will continue to work for the
time being.

Remove Bitcoin receiver tests and mark package deprecated

---

.travis.yml
testing/testing.go

This pulls us onto the new version of stripe-mock which should be
checking parameters more accurately now that it's on OpenAPI 3.0.

Upgrade stripe-mock to 0.2.0

---

card.go

Adds missing form annotation for `cvc` in CardParams. This isn't used
when creating cards directly (that gets passed through a special
`AppendTo*` that already encodes a `cvc`), but is important when
creating a token with a card.
Fixes #464.

Add form annotation for `cvc` in `CardParams`

---

product/client.go
product/client_test.go
sku/client.go

This properly sends the extra parameters in params.Params for sku and for product
This also adds the ability to pass `ProductParams` to the Get for the product resource
Fixes https://github.com/stripe/stripe-go/issues/466

Properly pass the Params parameters for sku and product

---

form/form.go
form/form_test.go

If a boolean value is meant to be `true` by default, `stripe-go` uses a pointer to a bool, and uses `nil` to render no url parameter, which ends up being `true` to the stripe-api.
Unfortunately, there was no ability to pass a pointer to a boolean of `true`. This attempts to fix it in a non-breaking, non-major change or refactor way.
I made some smaller changes as well to assist in the readability (since I had to do a lot of that -- reading).

Parse zero-val pointers

---

source.go

cc @stripe/api-libraries @stan-stripe 
Adds support for the new [`redirect.failure_reason`](https://stripe.com/docs/api#source_object-redirect-failure_reason) attribute on sources.

Support for redirect.failure_reason attribute

---

source.go
source/client.go
source/client_test.go

cc @stripe/api-libraries @stan-stripe 
Adds support for detaching sources from customers.

Adds support for detaching sources from customers

---

paymentsource.go
paymentsource/client.go
paymentsource/client_test.go
source.go

r? @will-stripe
cc @stripe/api-libraries @stan-stripe @remi-stripe 
This PR adds support for the `/v1/sources/src_.../verify` endpoint.
AFAIK, only `ach_debit` sources use this endpoint at the moment, so I hardcoded `Values` as `[2]uint8`. I guess that in the future, other source types might expect different types for the `values` parameter, and we might want to anticipate on that.
Putting the PR up for review, but I'll leave it to you to decide whether we should merge as-is or wait.

Adds verify source endpoint

---

.travis.yml
testing/testing.go

Includes a new bundled OpenAPI spec that has some fairly nice improvements compared to the last one.

Upgrade stripe-mock to 0.3.0

---

fileupload/client_test.go

We're seeing some intermittent unreliability from this test case right
now (the owning team is looking into it), so let's put in a skip so that
we keep working on getting some of these other Go changesets in.
Note that we still compile the test, so at least we get a baseline
guarantee that things aren't too wildly incorrect.
fyi @remi-stripe

Skip file upload test for now

---

card.go

Before this fix, passing Account and Token triggered the token to be sent both under `external_account` and under `source`.
This fixes https://github.com/stripe/stripe-go/issues/478

Ensure that the token is only passed once

---

params.go
params_test.go
stripe.go
stripe_test.go

Supports the `Context` struct [1] that came in with Go 1.7 on Stripe API
requests. This can be used to carry deadlines, cancelation signals, and
other request-scoped values across API boundaries and between processes.
Fixes #357.
[1] https://golang.org/pkg/context/

Support Context on API requests

---

card/client.go
card/client_test.go

Card-related API calls are a bit of an unusual case because we need to
have an instantiated params struct in order to determine the correct URL
to which to make the request. Previously, if a `nil` was passed to any
of these functions, we'd panic as we tried to access one of its members.
This patch just makes the params requirement a little more explicit by
returning an error if any of card functions is called with `nil` params.
Fixes #483.

Error early when params not specified for card functions

---

bankaccount.go
bankaccount_test.go

When encoding a bank account we shouldn't send `account_holder_name` or
`account_holder_type` unless they're given values. Sending an empty
value will cause an API error in cases where the request would have
otherwise been valid.
Fixes the other part of #485.

Make `account_holder_name`/`account_holder_type` truly optional

---

account.go
account_test.go

When using `AccountExternalAccountParams` for creating a bank account
from an account, sending an `object` field is required. Here we give the
params struct a custom `AppendTo` so that we can comply with this logic.
Partial fix for #485.
r? @ob-stripe

Send `object=bank_account` when using `AccountExternalAccountParams`

---

sourcetransaction.go
sourcetransaction/client.go
sourcetransaction/client_test.go

cc @stripe/api-libraries @stan-stripe
Adds support for the `/v1/sources/src_.../source_transactions` endpoint.
I wrote a test, but as stripe-mock doesn't support this endpoint yet the test is skipped for the time being. Not great, but it doesn't seem like we have an easy way to stubbing requests in stripe-go tests.

Add support for listing source transactions

---

.travis.yml
charge.go
client/api.go
exchangerate.go
exchangerate/client.go
exchangerate/client_test.go
exchangerate_test.go
testing/testing.go

cc @stripe/api-libraries @alixander-stripe
Adds support for the new `/v1/exchange_rates` endpoints as well as passing the `exchange_rate` parameter in charge creation/update/capture requests.
Tests are skipped for now as stripe-mock does not support the new endpoints yet.

Add support for /v1/exchange_rates API requests

---

stripe.go
stripe_test.go

I noticed this as I was looking at a dashboard that @ob-stripe produced today.
Other languages send language and language version as `lang` and `lang_version`
while we were using the fully expanded `language_*` here. I'm changing it here
for consistency with other libraries, but I'm also going to patch the server
because there are so many Go libraries out there that could potentially be
reporting if we supported both styles.
r? @ob-stripe

Rename language fields in Stripe's user agent to start with `lang`

---

bankaccount.go
card.go
source.go
source/client_test.go
token/client_test.go

When using Stripe Connect, you can clone a card/bank account/source form the platform to a connected account. This PR adds support for all of this:
- Creating a new token on a connected account passing the customer id in `customer` and the card id in `card`.
- Creating a new token on a connected account passing the customer id in `customer` and the bank account id in `bank_account`.
- Creating a new Source on a connected account passing the customer id in `customer` and the Source id in `original_source`.
This fixes https://github.com/stripe/stripe-go/issues/499

Support source sharing via Stripe Connect

---

.gitignore
.travis.yml
Makefile
README.md

Adds support for coveralls.io to the Go library.
This requires testing each package separately, because Go cannot create coverage profiles when testing multiple packages (cf. https://github.com/golang/go/issues/6909). We then use [`gover`](https://github.com/sozorogami/gover) to merge the multiple coverage profiles in a single file and [`goveralls`](https://github.com/mattn/goveralls) to send the data to coveralls.io.
I'm annoyed that this requires running the test suite a second time, but can't find a way around it. It looks like the Go issue is fixed in 1.10, so hopefully at some point we will be able to just run the test suite once with `go test -race -covermode=atomic -coverprofile=cover.out`.

Add support for coveralls.io

---

webhook/client_handler_test.go

Go-tip is failing because it looks like `Fprintf` got a little more
picky about the use of inappropriate verbs.
`%t` is meant to be used for booleans (it prints the word "true" or
"false"). I think what we actually wanted here was `%v`.
cc @ob-stripe

Correct `Fprintf` format verb

---

event.go
event_test.go

Modifies `event.GetObjValue` so that when specifying additional keys to
descend into, it's now possible to specify integer keys if the target
object is a slice of type `[]interface{}` (which should be what anything
coming out of event data deserializes to).
I initially expressed some concern about expanding this interface, but
given that the previous behavior would have been an outright panic, I
changed my mind and don't think it's too bad to add support for this
given that it's been requested by a user.
Fixes #503.
r? @ob-stripe

Support slices in `event.GetObjValue` and add tests

---

balance.go
paymentsource.go
payout.go
recipienttransfer.go
stripe.go
transfer.go

We had a user over in #381 wondering why the errors from a
`json.Unmarshal` in `payout.go` wasn't being handled.
I believe the answer is that we've had a convention in here forever
whereby certain unmarshals from JSON blobs that are "low risk" are
assumed to succeed often enough that the error isn't worth handling. In
some of these `Unmarshal` implementations in particular, the `data` has
already been run through a previous `Unmarshal` so it's known that it
contains valid JSON and is unlikely to error on a second run.
Given that we've never had a complain about this before, it's probably
true that these `Unmarshals` are low risk and probably fine as is, but
nonetheless, it's still good practice to make sure that every error is
handled just in case. In this patch I've gone back through to …

Handle all `json.Unmarshal` errors

---

form/form.go
form/form_test.go

Because most parameter fields in stripe-go are non-pointers, we
generally require that a value be non-empty before we encode it, because
otherwise we can't tell whether or not it was explicitly set.
It recently came up in #511 that it's no longer possible to set an empty
value in a map, which is a direct result of this behavior.
This patch tweaks the implementation slightly so that we always encode
all values that we find in maps, even if they're zero values. This makes
sense because unlike a struct which has default fields, we can always
guarantee that anything present in a map *was* explicitly added. This
resolves the problem described above.
Fixes #511.
cc @ob-stripe

Encode empty map values

---

plan.go

This fixes https://github.com/stripe/stripe-go/issues/513

Plan can now have zero amount via AmountZero

---

plan.go

Reverts pull request #514 which accidentally added `AmountZero` to the
wrong struct.
cc @remi-stripe

Revert pull request #514 (add `AmountZero`)

---

plan.go

Follows up #514 and adds `AmountZero` to `PlanParams` so that it's
possible to set amount to a zero value when creating or updating a plan.
Fixes #513.
---
For now this targets the branch in #515 until that's merged to master.

Add `AmountZero` to `PlanParams`

---

sub.go
sub_test.go

Makes the following changes:
* Adds `BillingCycleAnchorUnchanged` to `SubParams` to support the new
`unchanged` value for this field.
* Adds `BillingCycleAnchor` to the `Sub` response (which was previously
not present).
Unfortunately the new fields were just a little bit longer in naming than anything
in there before, so `gofmt` made the diff a bit of a mess. It's much easier to 
view the changes using the "no whitespace" link:
https://github.com/stripe/stripe-go/pull/517/files?w=1
r? @ob-stripe (I'll also ask someone on the Subs team to review as well.)

Update subscriptions with changes to `billing_cycle_anchor`

---

.travis.yml
ephemeralkey/client_test.go
example_test.go
plan.go
plan/client_test.go
plan_test.go
product.go
product/client_test.go

All credit goes to @jhoon-stripe for the original PR: https://github.com/stripe/stripe-go/pull/496
I just rebased and resolved conflicts. From the original PR:
**Summary**
This PR implements upcoming changes to the way in which plan objects are created in the Stripe API. Specifically, it:
- Allows plans to be created with products (with a product ID)
- Allows plans to be created with inline product fields
r? @brandur-stripe @tmaxwell-stripe

Product and plan support

---

paymentsource.go
paymentsource_test.go

This pull request fixes serialization for `PaymentSourceBankAccount`.  `PaymentSource` has a  `MarshalJSON` implementation with custom behavior based on type but there was no implementation for type  `PaymentSourceBankAccount` so bank accounts were being serialized as `null`.

update PaymentSource.MarshalJSON to serialize bank accounts too

---

.travis.yml

Go 1.10 was just released, so let's start testing it!

Start testing Go 1.10

---

.travis.yml
topup.go
topup/client.go
topup/client_test.go

This add standard retrieve, create and update client support for the new `/v1/topups` endpoint.
r? @apakulov-stripe @ccontinanza-stripe @chellman-stripe @kenneth-stripe @miguel-stripe

Add support for /v1/topups endpoints

---

plan.go
plan/client_test.go
plan_test.go
stripe.go

This ensures that you can create plans with the latest API version. We had 2 separate bugs:
* re-using `ProductParams` meant that you could pass invalid parameters when creating a product inside a plan (such as Type which is unsupported).
* not properly enforcing the latest API version which means all requests are currently failing.
This is a breaking change **but** it fixes what we broke in 29.0 so it's likely a better fit for 29.0.2 but unsure.

Fix latest version to properly support Product in plans

---

order/client.go
order/client_test.go

The `Client` code is not currently using commonParams when returning an order. As a result, information (such as setting the StripeAccount) is lost.

returning an Order is not using common params

---

order.go
order_test.go

This PR addresses missing functionality related to shipping attributes of an order.
* The `Shipping` struct was missing attributes for `carrier` and `tracking_number`.
* The `OrderUpdateParams` struct did not allow the shipping carrier or tracking number to be updated. You can workaround it using `AddExtra` but we might as well have typed support for these values.

Support shipping carrier and tracking number in orders

---

account.go

I noticed there are some fields missing on the [Owner type](https://github.com/stripe/stripe-go/blob/master/account.go#L344-L350) that are defined in the API documentation.
- maiden_name
- personal_id_number
- personal_id_number_provided
This PR adds those fields to the Owner type.

Add missing MaidenName, PersonalID, PersonalIDProvided fields to Owner

---

countryspec.go

This PR fixes a wrong type declaration of the  `CountrySpec.SupportedBankAccountCurrencies` field.
The API exposes a `map[Currency][]Country` while the library defined it as a `map[Country][]Currency`.

Fix mixed-up types in CountrySpec.SupportedBankAccountCurrencies

---

transfer.go

This change allows an expanded `transfer.destination_payment` to be accessed via the `DestPayment` field.
It is a small breaking change to the API.

Change Transfer.DestPayment from string to *Charge

---

invoiceitem.go

After updating to recent version I can't make invoiceitems with zero amount (it was possible untill introducing `form` package in v26.0.0). This fix is similar to https://github.com/stripe/stripe-go/pull/516

allow AmountZero in InvoiceItemParams

---

source.go

This PR adds the missing const definition for the "not_required" redirect flow status that was added in API version 2017-08-15.

Add const for redirect flow status "not_required"

---

.travis.yml
form/form.go
plan.go
plan_test.go
scripts/check_gofmt.sh
usage_record.go
usage_record_test.go
usagerecord/client.go
usagerecord/client_test.go

PR ported from internal internal GHE.
Adds flexible billing primitives to the SDK for beta functionality.

Flexible billing primitives

---

source.go

Add support for the `mandate` property on the Source object. Currently only used for SEPA debits as far as I can tell. I could not add tests as stripe-mock does not return such a resource today.
This fixes https://github.com/stripe/stripe-go/issues/540
r? @ob-stripe

Add support for mandate property on Source objects

---

sub.go

This was simpler than I thought it'd be (and it seems to work!) so here is my pull request to implement #545. I don't have a whole lot of time, but let me know if there's anything I missed!

Add SubParams.TrialFromPlan and SubItemsParams.ClearUsage

---

card.go

`CardParams` has a special `AppendTo` implementation that's used in
certain cases to properly massage itself into the calls of certain API
methods.
The default `AppendTo` implementation will recurse into substructs like
`Params`, but this custom one will not. This means that although it was
correctly encoding card data, it wouldn't encode common fields like
`Metadata`.
This patch adds an additional encoding call to make sure that standard
fields in `Params` are also encoded even when calling this custom
implementation.

Append standard `Params` in `AppendToAsCardSourceOrExternalAccount`

---

account/client_test.go
bankaccount/client_test.go
card/client_test.go
coupon/client_test.go
paymentsource/client_test.go
sub/client_test.go

I found a bug recently in stripe-mock which causes it not to actually be
validating that parameters not in the spec are not being sent (the
actual Stripe API does check for this).
After applying a fix, I found that stripe-go's test suite no longer
passes against it, and the reason is that there are some subtle mistakes
throughout. This patch corrects them to be in line with what the API
actually expects.

Fix some parameters being sent in tests

---

fileupload/client_test.go
testing/testing.go

Stripe-mock now supports file uploads, so do the same thing that we did
for the rest of the API and set a backend for it that hits stripe-mock
instead of the live API.

Run file upload tests against stripe-mock

---

README.md
go.mod

Adds a `go.mod` file to the project for aspiring vgo support. As
described in #559, without such a file, vgo will default to the lowest
released major version available, which in our case is `v1.0.3`. The vgo
proposal seems to have been officially accepted, so having support for
it early is a bit of a nicety that we can offer.
The one caveat of this addition is that while vgo users should import
stripe-go like this:
import (
"github.com/stripe/stripe-go/v30"
)
We can't actually recommend this `import` style anywhere in our core
documentation yet (although it's okay to put it in the `README.md` in a
vgo-specific section). This is because the `v30` suffix at the end of
the path isn't a real physical path, but rather just a symbolic one that
vgo knows how to parse and resolve as a tag. …

Add `go.mod` for aspiring vgo support

---

dispute/client.go
dispute/client_test.go

We should accept and pass forward stripe.DisputeParams that will include `StripeAccount` as for any other calls for Connected Accounts
Right now `Close` dispute doesn't work for Connected accounts
```
{
"error": {
"code": "resource_missing",
"doc_url": "https://stripe.com/docs/error-codes/resource-missing",
"message": "No such dispute: dp_***",
"param": "dispute",
"type": "invalid_request_error"
}
}
```
Works fine if i am doing manual call with one more header field `Stripe-Account`

Support stripe.DisputeParams for Close dispute API

---

v32_migration_guide.md

Adds a migration guide for the prospective version 32 of stripe-go which
will include the changes in #544. Some of the breaking changes there are
so sizable that I think we should special-case this with a particular
upgrade guide to help ease user pain somewhat while they're upgrading.
Here we explain some of the background context and make a list of all
the included changes and put in suggestions for remediation.

Add a V32 migration guide

---

webhook/client_handler_test.go

There is no need in closing request body.
From https://golang.org/pkg/net/http/#Request:
// The Server will close the request body. The ServeHTTP
// Handler does not need to.

doc(webhook): cleanup example

---

invoice.go

Add invoice's pdf and hosted url

---

plan.go
plan_test.go

Fixes #575. Not much to explain here, methinks. :)

Fix bucket_size -> divide_by

---

account.go
account/client_test.go

Add support for `document_back` on Account's legal_entity

---

README.md

Looks like the copy+paste of example code lost it's formatting
* Indent example to code to match gofmt

format the example README code

---

account.go

When retrieving a Custom account with additional owners, the legal entity was not deserialized property and was empty. The issue was that `legal_entity[additional_owners][][verification]` is not a string but is instead a hash with various properties. Because of this, the entire deserialization of `LegalEntity` failed and it was just `nil`.
This fixes https://github.com/stripe/stripe-go/issues/580
I tried to add a test for this but stripe-mock returns no `legal_entity` at all so that did not work.

Fix legal_entity[additional_owners][][verification] to be a struct

---

account.go
account/client_test.go
account_test.go

While working on fixing https://github.com/stripe/stripe-go/issues/580, I started improving `TestAccountUnmarshal` to ensure we tried to deserialize a complex account object to catch any issue.
Doing that, I caught a few mistakes that I wanted to fix at the same time:
* `AccountRejectReason` is now a type even though it's only used as a parameter. I should have fixed it when you asked me to, it's cleaner.
* `verification[disabled_reason]` now has its own type: `IdentityVerificationDisabledReason` and related constants
* `verification[due_by]` should not be a pointer so I fixed it back to a normal `int64`
* `PayoutIntervalDay` has been renamed to `PayoutIntervalDaily`.
I think we should merge this one as a major version as it makes enough breaking changes.
If we want to unblock the other …

Add new constants, rename one and fix DueBy

---

dispute.go
fileupload.go
fileupload_test.go

As we discussed in #578, here we unify the `File` and `FileUpload`
models into a single type. We do this by removing `File`, and changing
all instances where it was referenced to `FileUpload`.
These two structs were almost identical already, with the exception of
the `MIMEType` field on `File`, which is called `Type` on `FileUpload`.
Aside from that, the rename should cause very minimal breakage because
most users would have been accessing members without referencing the
struct's name directly like `dispute.Evidence.CustomerSignature.URL`.
Also, just examining the server-side resources, I'm pretty sure that
`MIMEType` didn't even work because it looks like the field is actually
called `Type` for both files and file uploads. So even if a user has
referenced the property, they should fix …

Remove File in favor of FileUpload

---

invoice.go

Add support for new properties on the Invoice object:
- `amount_paid`, `amount_remaining` and `subscription_proration_date`
- add support for `billing_reason` with the new type `InvoiceBillingReason` and the potential values for that property as documented [here](https://stripe.com/docs/api#invoice_object-billing_reason)
- remove comments that listed specific enum values.

Add support for new properties on the Invoice object

---

charge/client.go
charge/client_test.go
countryspec.go
countryspec/client.go
countryspec/client_test.go
event.go
event/client.go
exchangerate.go
exchangerate/client.go
exchangerate/client_test.go
issuerfraudrecord.go
issuerfraudrecord/client.go
issuerfraudrecord/client_test.go
loginlink.go
loginlink/client.go

* `IssuerFraudRecordListParams` now uses `*string` for `Charge`
* `event.Get()` now takes `EventParams` instead of `Params` to be consistent
* The `Get` method for `countryspec`, `exchangerate`, `issuerfraudrecord` now take an extra parameter to be consistent and allow setting the connected account.
* `charge. MarkFraudulent()` and `charge. MarkSafe()` have been removed. You should use `charge.Update()` instead
* `charge.CloseDispute()` and `charge.UpdateDispute()` have been removed. You should use `dispute.Update()` or `dispute.Close()` instead.
* `loginlink` now properly passes the `params`
This fixes https://github.com/stripe/stripe-go/issues/588

Fix all Get methods to support Params and remove deprecated ones

---

iter.go
params.go
stripe.go

This patch organizes some of library's core files (`stripe.go`,
`params.go`, `iter.go`) alphabetically and into sections. Here are the
key changes:
* Introduces "sections" of codes, these are (in order how they actually
appear in the file too):
```
// Public constants
// Public variables
// Public types
// Public functions
// Private constants
// Private variables
// Private types
// Private functions
```
The premise is that symbols which are intended to be more widely
used (because they're exported out of the package) are at the top of
the file for easier access, while unexported symbols are organized
closer to the bottom.
* Within each section, all symbols are organized alphabetically.
* All type-specific functions (e.g. `func (p *Params) GetParams`) are
arranged below the type they're …

Organize core files alphabetically and into sections

---

.travis.yml
Makefile
account/client.go
charge/client.go

This patch brings golint [1] into the Travis build and adds a make
target that will start running it on a few packages that we've expunged
of all linting errors.
I've just added a few packages to this initially because there are
hundreds of linting errors across the entire system, and cleaning them
all up would be an incredibly noisy diff. My recommendation is that we
issue smaller patches with ~1-6 packages converted over at a time to
make reviews easier (and more reliable), and add them to the whitelist
in `Makefile` as we go. After all packages are converted, we change the
call to `golint ./...`, and it'll always just run for everything.
Golint's major advancement will be to help us vet that Godoc comments
are formatted correctly, e.g. they all start with a function name like
`Get …

Activate linting for a few packages

---

invoice.go

When retrieving the upcoming invoice, you can now pass
- a new coupon
- a list of extra invoice items
- billing cycle anchor or trial from plan
- subscription's tax_percent
This fixes https://github.com/stripe/stripe-go/issues/600

Add missing parameters for the upcoming invoice

---

charge.go

@brandur-stripe turns out you were right and those are supported, and the docs are getting updated.

Add extra params/properties for Level III on Charge

---

.travis.yml

Our resolved dependencies aren't cached and we occasionally see
intermittent failures as `go get` runs and temporarily fails to get one
of our dependencies. This fails the build, and someone has to go in and
restart it.
It turns out that Travis provides a handy `travis_retry` helper [1]
which will retry a command up to three times if it returns a non-zero
exit code. I've added it in for all dependency resolution, and we'll see
if it helps.
[1] https://docs.travis-ci.com/user/common-build-problems/#travis_retry

Use `travis_retry` helper when using `go get` for dependencies

---

stripe_test.go

The current tests for "app info" test against `User-Agent`, but don't
test against the `X-Stripe-Client-User-Agent` header. This patch adds a
few extra tests for safety.
Related: #607.

Add some "app info" tests for `X-Stripe-Client-User-Agent`

---

stripe.go
stripe_test.go

This adds support for an optional partner_id attribute in the SetAppInfo hash.

Adds support for 'partner_id' to 'SetAppInfo'

---

error_test.go
order/client_test.go
stripe.go
stripe_test.go
testing/testing.go

Introduces a new system for getting backends with a set of custom
configuration that's a little cleaner than adding a new setter for every
option that we add in the future.
`BackendConfig` is introduced a user configurable struct which is then
passed to `GetBackendWithConfig`, which returns a backend configured to
spec. `GetBackend` remains, is backward compatible, and continues to set
a default backend for either type.
A new option on `BackendConfig` is being able to set a per-backend
`Logger` and `LogLevel`. This is the impetus that sparked this change as
documented in #608.
So the unfortunate part is that `BackendConfig` is confusingly named
similarly to the very poorly named `BackendConfiguration`, which is the
final implementation of a backend. I wanted to keep this patch backward …

Introduce `GetBackendWithConfig` and make logging configurable per backend

---

Makefile
loginlink/client.go
order/client.go
orderreturn/client.go
paymentsource/client.go
payout/client.go
plan/client.go
product/client.go
recipient/client.go
refund/client.go
reversal/client.go
sku/client.go
source/client.go
sourcetransaction/client.go
sub/client.go
subitem/client.go
threedsecure/client.go
token/client.go
topup/client.go
transfer/client.go
usagerecord/client.go

This lint the remaining API packages. It also fixes a missing getter in the `topup` package

Lint remaining packages

---

client/api.go

This PR starts by re-ordering all packages alphabetically to make it easier to maintain. It then adds all the packages that were missing from the list.
This fixes https://github.com/stripe/stripe-go/issues/614

Add missing packages to the list of clients

---

invoiceitem.go

Both these parameters were missing from the params struct, but are
documented in the API [1]. This patch adds them in.
Fixes #619.
[1] https://stripe.com/docs/api/php#create_invoiceitem

Add `Quantity` and `UnitAmount` to `InvoiceItemParams`

---

.travis.yml
Makefile
client/api.go
paymentintent.go
paymentintent/client.go
paymentintent/client_test.go
paymentintent_test.go

This resource is gated but stripe-mock has been updated to support the APIs so tests run as expected.
cc @michelle-stripe @jenan-stripe

Add support for the PaymentIntent resource

---

stripe.go
stripe_test.go

In #611 I accidentally introduced a regression in the `NewBackends`
function in that an `http.Client` passed into the function isn't
actually wired through to the new backends.
Here we fix that problem by changing the invocations to use
`GetBackendWithConfig` like they were supposed to.
Fixes #626.

Wire an `http.Client` from `NewBackends` through to backends

---

.travis.yml
testing/testing.go

Switches the test suite over to use HTTPS and HTTP/2 against stripe-mock
using its new `-https` flag and built-in HTTP/2 support in Go.
Note that this won't quite work until we've merged stripe/stripe-mock#82 which
adds the `-https` option. I've tested it locally though, and verified that it
does indeed use HTTP/2.

Use HTTPS and HTTP/2 from the test suite

---

.travis.yml
testing/testing.go

See stripe/stripe-mock#84 for context, but I'm going to switch to port
`12112` as the new default for stripe-mock running HTTPS. This will
allow us to have a setup where we can run API libraries that use HTTP
and those that use HTTPS with just a single instance of stripe-mock.
Depends on stripe/stripe-mock#84 being merged first, and a new
stripe-mock release being cut.
r? @ob-stripe

Switch to port 12112 as default stripe-mock port for HTTPS

---

bankaccount.go
bankaccount/client.go
bankaccount_test.go
card.go
card/client.go
card_test.go

Fixes a bug discovered in #632 whereby because we were manually adding a
filter like `?object=bank_account` to the end of paths, we'd clash with
the `form` package's attempt at an encoding if both came into play. This
would have the effect of producing an invalid URL like this:
```
/accounts/acc_xxxxxx/external_accounts?object=bank_account?limit=1&starting_after=ba_xxxxxx
```
(Note the multiple `?`s in the query string.)
Here we stop manually adding filters to URL paths and move them into a
custom `AppendTo` override for the `form` package. Bank accounts and
cards were the only places that we were doing this, so only they were
affected.
We also add tests to make sure that we're doing the right thing.
Fixes #632.

Fix encoding of list params for bank accounts and cards

---

charge.go

Add the `RiskScore` field to the `ChargeOutcome` struct

Add RiskScore field to ChargeOutcome struct

---

coupon.go
coupon/client_test.go
product.go
stripe.go
sub.go

This ensures the most recent API version is set in stripe-go as there were a few breaking changes.
* Move to API version 2018-07-27
* Remove SKUs list on the product
* Remove the ability to pass a Source on subscription creation/update
* Change percent_off on the coupon from int to float

Add support for the most recent API version

---

.travis.yml
Makefile
client/api.go
sigma/scheduledqueryrun/client.go
sigma/scheduledqueryrun/client_test.go
sigma_scheduledqueryrun.go
testing/testing.go

Add support for ScheduledQueryRun

---

stripe.go

This one is a variety of improvements to the retry code:
* Fixed one bug whereby for a failed request, we were not reading the
entire response body before trying to log it, which results in an
uninformative output like `&{409....`. Here we add a `ReadAll`.
* I denested some code so that we have less indentation.
* I changed measuring request time to measuring individual requests
around `s.HTTPClient.Do` instead of measuring the entire span
including all the sleeping the retry block is doing.
* I added logging for the amount of time the program is about to go to
sleep before a retry. You can still get the total execution time by
adding the time for all requests plus the time for all sleeps.
* Generally changed some logs around for consistency around format,
casing, and punctuation.
The …

Bug fix + various code/logging improvements to retry code

---

stripe.go
stripe_test.go

This patch changes the interfaces of `NewRequest` and `Do` around a
little so that we can set a new request body with every request.
In the era of HTTP (1), it was safe to reuse a `Request` object, but
with the addition of HTTP/2, it's now only sometimes safe. Reusing a
`Request` with a body will break.
See some more information here:
https://github.com/golang/go/issues/19653#issuecomment-341539160
Fixes https://github.com/stripe/stripe-go/issues/642.

Set request body before every retry

---

stripe.go
stripe_test.go

I recently introduced `BackendConfig` to give users a way of fine-tuning
a backend that's created. Unfortunately, that produced a close name
collision with the existing `BackendConfiguration`, which isn't really a
configuration, but more of the main implementation of the `Backend`
interface.
Here we rename `BackendConfiguration` to `BackendImplementation` to make
this less confusing. It's a breaking change, but I have to do a major
release as part of #648 anyway, so it's not a bad time to do it.

Rename `BackendConfiguration` to `BackendImplementation`

---

webhook/client.go
webhook/client_test.go

Replaces #602 to export `webhook.ComputeSignature` for testing purposes
and resolve #497.
Fixes #497.

Export `webhook.ComputeSignature`

---

stripe.go

In #648 I introduced a new field on `BackendImplementation` which allows
us to disable sleeping between retries in tests. Unfortunately, I forgot
to set this field to `true` by default, and therefore we weren't
sleeping on retries in production.
Here we make sure to enable sleep when generating a new backend.
Fixes #651.

All `BackendImplementation`s should sleep by default on retries

---

fileupload.go

The `Links` field of `FileUpload` struct is currently set to `[]*FileLink`.
This can cause an unmarshalling error when calling for example the Create FileUpload method, as the  `FileUpload` object return as response can include a list of file links:
```
{
id: "file_xxxxxxxx",
object: "file_upload",
created: 1533640021,
filename: "file.jpg",
links: {
object: "list",
data: [ ... ],
has_more: false,
url: "/v1/file_links?file=file_xxxxxxxx"
},
....
}
```
This PR attempts to fix this issue by changing the type of FileUpload's Links fld to `FileLinkList`.
r? @ob-stripe @brandur-stripe

Change the type of FileUpload's Links fld to FileLinkList

---

webhook/client.go
webhook/client_test.go

ConstructEvent and related functions now use the new validatePayload functionality.
This allows consumers of the library to not have to Unmarshal the json
payload in order to validate it. This way a library user can choose to only
validate a signature of a message and pass it to downstream systems as
trusted without being concerned with the actual structure of the events
yet. This is useful because the Event structure is tied to the user's
Stripe-account-wide API version which must be upgraded in an all-or-nothing
fashion. With this commit a library user may choose to write the webhook
event validation portion of their code in a way that will not be broken by
forwards or backwards- incompatible event structure changes

Split webhook payload validation logic into separate ValidatePayload* functions

---

account.go
account/client_test.go
form/form.go
form/form_test.go
invoice.go
order.go
order/client_test.go
params_test.go
plan.go
plan/client_test.go
sub.go
sub/client_test.go

Changes all arrays from classic Rack encoding:
``` sh
arr[]=...&arr[]=...&arr[]=...
```
To integer-indexed encoding:
``` sh
arr[0]=...&arr[1]=...&arr[2]=...
```
See some additional background in: https://github.com/stripe/stripe-ruby/pull/674
cc @stevene-stripe @zanker-stripe

Integer-index encode all arrays

---

issuing_card.go

`eta` is a timestamp, like `created`.

Fix type error in issuing_card.go

---

bitcoinreceiver.go
bitcoinreceiver/client.go
bitcoinreceiver/client_test.go

Removes the ability to use `New` and `Update` for bitcoin receivers. Tests pass!
```
» go test ./...
ok  	github.com/stripe/stripe-go	0.176s
ok  	github.com/stripe/stripe-go/account	0.081s
ok  	github.com/stripe/stripe-go/applepaydomain	(cached)
ok  	github.com/stripe/stripe-go/balance	0.106s
ok  	github.com/stripe/stripe-go/bankaccount	0.129s
ok  	github.com/stripe/stripe-go/bitcoinreceiver	0.086s
ok  	github.com/stripe/stripe-go/bitcointransaction	(cached)
ok  	github.com/stripe/stripe-go/card	0.267s
ok  	github.com/stripe/stripe-go/charge	0.089s
ok  	github.com/stripe/stripe-go/client	0.035s
ok  	github.com/stripe/stripe-go/countryspec	(cached)
ok  	github.com/stripe/stripe-go/coupon	(cached)
ok  	github.com/stripe/stripe-go/customer	0.085s
ok  	github.com/stripe/stripe-go/discount …
```

Remove editable bitcoin receiver actions

---

README.md

Small addition on the readme. It doesn't explicitly mention all the packages needed to run the tests, I added a one liner that'll hopefully help people in the future.

Update readme with instructions on downloading all required deps

---

issuing_card.go

Convention throughout Go and this library is to upcase field names that
are acronyms. Here we do that for "ETA". We are changing its type anyway
in #661, so it's a good time to make this change.

Rename `IssuingCardShipping`'s `Eta` to `ETA` to fit conventions

---

form/form.go
form/form_test.go

Removes the form package's `zero` option, which was previously used to
encode a true zero for an integer value before we introduced pointers
everywhere.
I also looked into removing the `empty` option, but I think we still
need it for now. We could move it into a custom `AppendTo`
implementation specifically on `LegalEntityParams`, but it doesn't seem
like a clear win to me.
r? @remi-stripe (As we discussed a little yesterday.)

Remove the form package's `zero` option

---

card.go

Add AvailablePayoutMethods to card.go

---

subitem.go

Per documentation, adds the subscription field to the SubscriptionItem object.
Fixes https://github.com/stripe/stripe-go/issues/665

Add the Subscription field to subscription items

---

.travis.yml
customer.go
plan.go
plan/client_test.go
plan_test.go
stripe.go
sub.go
sub/client_test.go
testing/testing.go

This PR has multiple major changes due to the move to the latest API version and some new properties/breaking changes.
* Add support for `tax_info` and `tax_info_verification` on the customer
* Remove `business_vat_id` on the Customer
* Rename `amount` to `unit_amount` on Plan's tiers
* Remove the ability to call Cancel on a Subscription with `at_period_end`.
(Flagging that we need a new stripe-mock for tests to pass because of the change to `amount` on Tiers)

Move to API version 2018-08-23

---

charge.go

Note that this property is internal and not usually returned in the API.

Add support for authorization_code on the Charge resource

---

stripe_test.go

Removes a test that's producing racy results in CI. As noted in #672, it
probably became racy as it started using the new HTTP implementation
in Go's HTTP/2 package.
My justification here is that cancellable contexts are already well
tested in Go's core. What we really want to test is just that the
context supplied by our users does indeed make it into the Go `Request`
that we're about to execute -- from there we can expect Go to do the
right thing. We already have a test that checks that just a few lines
above.
r? @remi-stripe What do you think about this approach?
cc @stripe-internal/api-libraries

Remove racy test in favor of simpler one

---

bankaccount/client_test.go
usagerecordsummary.go
usagerecordsummary/client_test.go

* Ensure that `subscription_item` is not sent as a parameter when listing usage record summaries
* Update the test for usage record summary
* Fix the bank account list test for Accounts to pass the right parameter

Fix two issues with List tests

---

paymentintent.go
paymentintent/client.go

* Capture takes a different set of parameters
* application_fee is now called application_fee_amount
(Flagging the latest stripe-mock broke the test suite so also going to fix that in a separate PR in a few minutes)

Fix payment intent parameters

---

bankaccount/client_test.go

Unfortunately the test suite has a few tests that are broken when
running against the latest version of stripe-mock.
Two out of three of them are fixed after we bring in the OpenAPI
specification that exposes the `object` parameter in the customer
sources list endpoint and apply the stripe-mock patch which allows it to
correctly validate query parameters [1].
Unfortunately though, this last test still doesn't work because `object`
is not exposed on `/accounts/:id/external_accounts`. We could look into
enabling that, but given we at least have some working coverage for our
list invocation now, it's probably easier just to remove this test and
rely on the other one.
After this and the changes above are brought in, stripe-go will work with the
latest stripe-mock once again. …

Remove `TestBankAccountGet_ByAccount` test

---

bankaccount/client_test.go

In #676 I accidentally removed the wrong test — I was trying to get the
"list" test for accounts, not the "get" test for accounts.
Here we resurrect the test that was removed accidentally and remove the
right one instead. Oops.
cc @remi-stripe

Remove the right test

---

subitem/client_test.go

When listing subscription items a subscription ID is required. Our test
wasn't previously doing that, so here we add one in.
Caught while testing against a newer version of stripe-mock that
validates query parameters.

Fix subscription item listing test

---

.travis.yml
testing/testing.go

Now that we've got a few more fixes into stripe-mock, OpenAPI (the
addition of the `object` parameter when listing customer sources), and
in stripe-go's test suite, we're ready to take stripe-mock to 0.30.0.

Upgrade stripe-mock to 0.30.0

---

invoice.go

The TaxPercent field is a *float64, the SubscriptionTaxPercent field should match, if not it's impossible to apply something like 6.5% tax on a subscription.

SubscriptionTaxPercent should be a float64, not int64

---

source.go
source/client_test.go

This is a breaking change as `date` was incorrectly categorized as a String.
This fixes https://github.com/stripe/stripe-go/issues/684

Add support for `mandate` and `receiver` hashes on Source creation

---

bankaccount.go
bankaccount_test.go
card.go
card_test.go

`BankAccount` has a special encoding function that's invoked from its
`New` called `AppendToAsSourceOrExternalAccount`. It works quite a bit
differently from any other resource (with the exception of card) because
this special encoding is invoked then the function uses a `CallRaw`
instead of a `Call`, so no general `AppendTo` is ever used.
As described in #685, this caused a problem whereby the standard set of
fields in `Params` were not being included because the function didn't
have any consideration for them (although strangely, we *were* handling
them from card's equivalent). Here we add an allowance for `Params` and
a test to make sure that metadata is being encoded correctly.
Fixes #685.

Encode `Params` in `AppendToAsSourceOrExternalAccount`

---

.gitignore
go.mod

Adds a `go.mod` file to support the new experimental Go module system
which is likely to see full release pretty soon.
See #559 for original context. I originally tried this in #563, but ran
into trouble because Vgo wasn't smart enough to have subpackages in a
module know to use their parent's version, so we'd see problems where
it'd use stripe-go v46 (for example), go on to look at stripe-go/charge,
see that it depended on stripe-go, so it would re-ascend the tree and
default to stripe-go v1 instead of v46! See #563 for details, but it
didn't work at all and I ended up just reverting.
Since then it seems like some major improvements have been made and
subpackages can now resolve their parents version correctly. (I tried
this in a test project and although I'm not 100% sure that it was …

Add `go.mod` to support the new module system

---

order.go
order_test.go

Attempts to fix the unmarshalling error that can occur when expanding `parent` of an Order Item object, when calling `order.List` and expanding on `data.items.parent`. 

Handle unmarshaling OrderItem to account for `parent` expansion

---

order.go

Add `status_transitions` filters to the List Orders params.
Attempts to fix https://github.com/stripe/stripe-go/issues/682  

Add status_transitions filters to the List Orders params

---

client/api.go
reporting/reportrun/client.go
reporting/reportrun/client_test.go
reporting/reporttype/client.go
reporting/reporttype/client_test.go
reporting_reportrun.go
reporting_reporttype.go

cc @stripe/api-libraries @brahn-stripe

Add support for Reporting resources

---

error.go

Not urgent, but noticed this missing when I was trying to isolate 404s looking up plans.

Add resource_missing error code

---

issuing_card.go

Currently the IssuingCardDetails struct returns with a zero value for Number, this is because the json tag in the type declaration is set to 'type' and the API request is returning 'number'.
This pull request simply changes the json tag in the IssuingCardDetails declaration to 'number' to fix this issue.

Updating IssuingCardDetails.Number json tag to 'number'

---

charge.go
sub.go

It seems like `OnBehalfOf` was added to SubscriptionParams but not the subscription objects themselves.

Add "OnBehalfOf" to subscriptions

---

event.go

Add support for the `delivery_success` param on the list event endpoint

---

.travis.yml
Makefile

Unfortunately Go only supports the last two major versions of the
language for Golint, and aren't afraid of making changes that will break
older ones, which they seem to have just done (and thus breaking our
master build).
Here we track which versions of Go Golint can support, and only run it
if the build is happening on one of them.
[1] https://golang.org/doc/devel/release.html#policy

Only run Golint on supported versions

---

client/api.go

Hi,
I am currently working with the Stripe Terminal beta and utilizing a Go backend. At the moment, the terminal bindings are not within the base client API. 
Is this purposeful? If not, I took a stab at adding them into the client.
Thanks!
Matt

Add Terminal bindings to clients

---

.travis.yml
stripe.go

Here we set `Request.GetBody`, which is used under certain circumstances
by the internal `net/http` core like in the case of a redirect. This
will usually not end up being used, but it doesn't hurt to set it in
case it is (it's run lazily, and few additional resources are needed in
case it's not run).
Fixes #710.

Set `Request.GetBody`

---

.travis.yml
bankaccount/client_test.go
issuing/cardholder/client_test.go
issuing_cardholder.go
order/client_test.go
person.go
person/client.go
person/client_test.go
person_test.go
testing/testing.go

Add support for the Person resource

---

client/api.go
webhookendpoint.go
webhookendpoint/client.go
webhookendpoint/client_test.go

Add support for the Webhook Endpoint resource

---

countryspec.go
invoice.go
invoice/client.go
invoice/client_test.go
paymentintent.go
paymentintent/client.go
paymentintent/client_test.go
paymentintent_test.go
plan.go
stripe.go
sub.go

Since we are introducing multiple breaking changes to some resources, we are preparing a new branch to group multiple changes into one release.

Integration branch for v53.0.0 release

---

stripe.go
stripe_test.go

This PR covers the scenario when `res, err = s.HTTPClient.Do(req)` results in `res` that is `nil` (https://github.com/stripe/stripe-go/blob/master/stripe.go#L341 ). This can happen for example in case of timeout.
* a test was added to verify no panic in case of timeout
* in the `Do` function an additional check was added to prevent panic
Closes #713
---
[EDIT] Initial motivation:
Integration tests in the codebase I'm working on are randomly failing with the following stack trace:
```
error_cause=runtime error: invalid memory address or nil pointer dereference 
stack_trace=[
{
"function": "runtime.call32",
"location": "/usr/local/go/src/runtime/asm_amd64.s:573"
},
{
"function": "runtime.gopanic",
"location": "/usr/local/go/src/runtime/panic.go:503"
},
{
"function": "runtime.panicmem", …
```

`Do` function panics when HTTPClient returns a nil response

---

.travis.yml
Makefile

We needed to add this hack so that we could build on Go 1.8 which is no
longer supported by Golint. A while after that we dropped support for Go
1.8 in the build matrix though, so this hack isn't needed any longer.

Remove hack to skip Golint on old versions

---

charge/client_test.go
invoice/client_test.go
paymentintent.go
paymentintent_test.go

cc @stripe/api-libraries @kelvin-stripe

Add `last_payment_error` on PaymentIntent and fix broken tests

---

paymentintent.go

Add support for `transfer_data[destination]` on PaymentIntent

---

error.go
stripe.go

Looking through some of the code, I noticed errors were manually unmarshalled using a ton of type assertions and maps. That's not good. The problem was that the error types don't export their underlying `stripeErr` fields. `json.Unmarshal` uses reflection and tags to find fields that are exported (otherwise it can't set values). I've created an un-exported `rawErr` type that can be used for unmarshalling, and a further type `internalError` that embeds the Error type as it is, and adds the `decline_code` field at the same level (to correspond to the error format).
Ideally, the `decline_code` field should be a part of the main `Error` type, so we don't need that second internal type. The type of `decline_code` was (and is) `string`. I've left it as is to not break any existing code, but if …

Improve error response unmarshalling

---

ephemeralkey.go

We now accept an `issuing_card` parameter in the API when making an ephemeral key; this allows doing so from the Go bindings.

Add IssuingCard param value to ephemeral_key.go

---

.travis.yml
client/api.go
invoice.go
radar/valuelist/client.go
radar/valuelist/client_test.go
radar/valuelistitem/client.go
radar/valuelistitem/client_test.go
radar_valuelist.go
radar_valuelistitem.go
testing/testing.go

While I removed 2 properties from `Invoice`, those were not supported anymore because of the API version change so not sure if it's a breaking change but flagging just in case.

Add ValueList and ValueListItem for Radar and other Invoice changes

---

.travis.yml
review.go
review/client.go
review/client_test.go
testing/testing.go

Add support for the Review resource

---

stripe.go

When testing uploading files using an API client, I found that it would fail consistently with a strange error:
```go
{"code":"invalid_utf8_in_post_body","status":400,"message":"Invalid UTF-8 characters found in POST body: \"application/octet-stream\".  For assistance, please contact support@stripe.com.","type":"invalid_request_error"}
```
Adding some log statements to the `backendImplementation.Do` function, I found that it was trying to send a `files.New` request to `https://api.stripe.com/v1/v1/files`
Eventually I tracked the problem down to the `NewBackends` function. It reused the config object when creating the api and uploads backends. The `GetBackendWithConfig` function then modified the config object. So when it was called again with the same config object, it would already have …

Fix uploads API when using NewBackends

---

error.go

Since there is no such thing as ChargeError, the comment on Error.Err is misleading.

Update Error.Err field explanation.

---

subitem.go

Accoring with the [documentation](https://stripe.com/docs/api/subscription_items/delete?lang=go), we need a ClearUsage parameter.
Right now is not possible to delete subscription items due to error:
> Error encountered from Stripe: {"status":400,"message":"When deleting the subscription item ITEM_ID with a metered plan, all related usage records must be cleared too by setting `clear_usage=true`.","request_id":"REQ_ID","type":"invalid_request_error"}

Add ClearUsage param to SubscriptionItemParams

---

sub.go
sub/client_test.go

Add support for invoice_now and prorate on subscription cancelation

---

issuerfraudrecord.go

Add support for actionable and has_liability_shift on IssuerFraudRecord

---

invoice.go

Related to https://github.com/stripe/stripe-dotnet/pull/1467 and new properties on https://stripe.com/docs/api/invoices/upcoming#upcoming_invoice-invoice_items

Add support for new `invoice_items[*]` params on the Upcoming Invoice API

---

charge.go

Add support for `application_fee_amount` on Charge

---

README.md

Modifies the intro of the README to add explicit instructions on how to
use stripe-go with and without Go modules, including commands that need
to be run and what imports should look like.
I've also removed the "versioning" section because I don't think this
information is that all that novel, and certainly isn't useful enough to
occupy prime real estate at the front of the file.
[Link to rendered version](https://github.com/stripe/stripe-go/blob/brandur-readme-modules/README.md).
r? @remi (Going to wait a little longer before merge just in case I have
to revert the Go modules PR, but this should be reviewable now.)

Add section in README on Go modules + simplify lead-in

---

issuing_transaction.go

The amount field of the issuing transaction object is described in the api documentation (https://stripe.com/docs/api/issuing/transactions), returned by the API, but not parsed by this library.

missing amount on the IssuingTransaction struct

---

README.md

Annoyingly, the major version has to be included twice in the require line, otherwise you'll get something like this:
```
go: finding github.com/stripe/stripe-go v55.9.0
go: github.com/stripe/stripe-go@v0.0.0-20190115230412-fc4981293b86: go.mod has post-v0 module path "github.com/stripe/stripe-go/v55" at revision fc4981293b86                                                                                                    
go: error loading module requirements
```

Fix module require line in readme

---

invoice.go

Add support for https://stripe.com/docs/api/invoices/create#create_invoice-custom_fields and https://stripe.com/docs/api/invoices/create#create_invoice-footer

Add support for `custom_fields` and `footer` on `Invoice`

---

README.md

Go module support will be reverted in #774. Here, we update the README
with some information about the status of Go modules in stripe-go, and
how to use the library with them for the time being.
r? @brandur ~~(WIP.)~~

Update README with information on Go modules

---

invoice.go
sub.go
subitem.go

This one is a bit complex as it's across multiple resources and no specific test was added for it so we need to make sure it matches OpenAPI.
cc @clintonb-stripe Could you double check that I added the right set of properties too and I'm not missing any? (Java only lists properties, not parameters).
Docs: https://stripe.com/docs/billing/subscriptions/metered-billing/thresholds
Internal PR with gate removal: #126799

Add support for billing thresholds

---

stripe.go
stripe_test.go

Follows https://github.com/stripe/stripe-ruby/pull/696, https://github.com/stripe/stripe-php/pull/549, and https://github.com/stripe/stripe-python/pull/518 in adding telemetry metadata to request headers. 
The telemetry is disabled by default, and can be enabled per-client like so:
```go
backend := stripe.GetBackendWithConfig(
stripe.APIBackend,
&stripe.BackendConfig{
URL: "https://api.stripe.com/v1",
EnableTelemetry: true,
},
)
```
or globally by setting
```go
stripe.EnableTelemetry = true
```
cc @dcarney-stripe @bobby-stripe

Add Stripe client telemetry to request headers

---

stripe.go
stripe_test.go

Alphabetizes a few more lists of things in `stripe.go` and
`stripe_test.go`. This is just for cleanliness and produces no
functional changes.
r? @brandur (Very minor change.)

Alphabetize more things in `stripe.go`

---

.travis.yml
Makefile
scripts/test_with_stripe_mock.go
testing/openapi/README.md

Very similar to the recent feature implemented in other languages (for
example [1]), this wraps test runs in a script which will detect a
custom OpenAPI spec and fixture in `testing/openapi/` and start a local
version of stripe-mock pointing to them. The test suite is then executed
against that stripe-mock and it's shut down afterwards.
If there isn't a custom OpenAPI spec, we continue to fall back to the
system stripe-mock to keep test runs as fast as possible.
This differs a little from implementations in other languages in that we
had to start stripe-mock from a script (as opposed to a `before` block
or the like) because Go's testing tools don't give us a place where we
can do anything before any test runs. Therefore, we start stripe-mock
then execute `go test ./...` as a subprocess. …

Detect custom OpenAPI spec file and start stripe-mock from test suite

---

reversal.go

Add support for `destination_payment_refund` and `source_refund` on `TransferReversal`.
NOT asking for review yet as those properties are not expandable and I want to make sure it's expected to avoid a future breaking change.

Add new properties to `TransferReversal`

---

README.md
scripts/test_with_stripe_mock.go
testing/openapi/README.md

Allows stripe-mock startup to be disabled by passing
`STRIPE_MOCK_AUTOSTART` in the env with a value of `false` or `0`. This
may be useful for debugging problems where the automatically started
stripe-mock is not showing logging.
~~Allows stripe-mock startup to be disabled by passing
`STRIPE_MOCK_DISABLE` in the env with any value. This may be useful for
debugging problems where the automatically started stripe-mock is not
showing logging.~~
r? @ob-stripe Thoughts on this?

Allow stripe-mock to be suppressed with `STRIPE_MOCK_AUTOSTART=false`

---

invoice.go
sub.go

* Add `transfer_data[destination]` to both `Invoice` and `Subscription`
* Add `application_fee_amount` to `Invoice` and deprecate `application_fee`
NOT asking for review yet as I want to double check that we don't need `on_behalf_of` for now.

Add support for new properties and params on Invoice and Subscription

---

charge.go

We decided to support `transfer_data[amount]` on Charges for 2/19, at least for a few months. We think developers should use `application_fee_amount` instead but many integrations already used `destination[amount]` and would be quite blocked if we removed this.

Add support for `transfer_data[amount]` on Charge

---

form/form.go
form/form_test.go

Allows API arrays like `additional_owners` to be emptied by setting
their value to an explicit empty array. To accomplish this we need to
rework parts of the form-encoding library to detect this specific
condition.
I also had to rework a fair bit of the form package's test suite because
the existing code was making no distinction between an actual value
being set an empty in the generated form versus one that's not present.
Fixes #788.

Allow API arrays to be emptied by setting an empty array

---

.travis.yml
paymentintent.go
paymentintent/client_test.go
paymentintent_test.go
stripe.go
testing/testing.go

We are going to ship some changes to the Payment Intent APIs in the next API version. Though are fairly self-contained and pave the way for future changes. Changes are:
* `status`: remove `require_source` and `require_source_action` and add `requires_payment_method` and `requires_action`
* `next_source_action` renamed to `next_action`
* `allowed_source_types` renamed to `payment_method_types`
* `authorize_with_url` renamed to `redirect_to_url` both in the type of next action and in the hash that describes that next action.
cc @stripe/api-libraries @danwang-stripe

Changes to the Payment Intent APIs for the next API version

---

paymentintent.go

This fixes the issue where `save_payment_method` was not added for the latest API version
r? @ob-stripe 

Add support for save_payment_method on PaymentIntent

---

.travis.yml
account.go
account/client_test.go
account_test.go
countryspec.go
paymentintent.go
person.go
person/client_test.go
testing/testing.go

This PR contains the changes related to the new API version `2019-02-19`:
* Move stripe-go to API version `2019-02-19`
* Change the shape of `Account`
* The `legal_entity` property on the Account API resource has been replaced with `individual`, `company`, and `business_type`.
* `LegalEntityType` is now `BusinessType`.
* The verification hash has been replaced with a requirements hash.
* Multiple top-level properties were moved to the `settings` hash.
* The `keys` property on `Account` has been removed. Platforms should authenticate as their connected accounts with their own key via the `Stripe-Account` [header](https://stripe.com/docs/connect/authentication#authentication-via-the-stripe-account-header).
* The `requested_capabilities` property on `Account` creation is now required for …

Add support for API version 2019-02-19

---

stripe.go

Something went wrong on https://github.com/stripe/stripe-go/pull/782 and the API version was never upgraded, making that version broken unfortunately.

Fix API version which should be pinned to 2019-02-19 instead

---

client/api.go

Fixes https://github.com/stripe/stripe-go/issues/799

Add usagerecordsummary to the list of clients

---

invoice.go

Technically the List Invoice API does not yet take `created` but will tomorrow or the day after. I want the PR to be ready/approved and I'll only merge once it works.

Add support for `created` and `status_transitions` on `Invoice`

---

sub.go

This fixes https://github.com/stripe/stripe-go/issues/801
r? @rattrayalex-stripe 

Add support for `latest_invoice` on `Subscription`

---

webhookendpoint.go

Add support for `api_version` on `WebhookEndpoint` and fix a test.

---

event.go

Fixes https://github.com/stripe/stripe-go/issues/797

Prevents `Object` from being serialized on the `Event` resource

---

README.md

Adds a new README subsection that describes how to enable automatic
retries for network or other non-deterministic problems. This reflects
information that's available in other client libraries like stripe-ruby.
As discussed in #804.

Add README section on configurable retries

---

sub.go

Add support for `backdate_start_date` and `cancel_at` on `Subscription`. This is gated but many users have access to it and I missed it while releasing `SubscriptionSchedule`.
@stripe/api-libraries

Add new fields to Subscription

---

.travis.yml
charge.go
error.go
paymentintent.go
paymentmethod.go
paymentmethod/client.go
paymentmethod/client_test.go
testing/testing.go
token/client_test.go

Add support for PaymentMethod

---

.travis.yml
charge.go
ephemeralkey/client_test.go
invoice.go
stripe.go
sub.go

The changes in the library itself look minor. But this API version changes the behavior of Subscriptions entirely under the hood. If the charge fails, you still get a Subscription back instead of an exception and it's on you to check the Subscription status.
This is now fully ready to be reviewed. It also changes the `apiversion` internal-only constant to a public one.
Related to https://github.com/stripe/stripe-dotnet/pull/1552

Add support for API version 2019-03-14

---

stripe.go

While testing the `strict-version-check` flag, I discovered that we were incorrectly overriding the version forced in the request creating ephemeral keys.
This fixes the issue by calling `Set` instead of `Add`. I've confirmed it works, but I'm not sure this is the right approach here.
Marking as a breaking change since Ephemeral Keys would suddenly be created with the correct API version, which is what people would likely want, but still a dangerous change. There's also another major version going out anyway.

Properly override API version if it's set in the request

---

README.md
log.go
stripe.go
stripe_test.go

Implements leveled logging for the Stripe library which has two main
benefits:
1. Greatly cleans up our logging call sites and makes them more
readable.
2. Allows standard loggers seen in the Go ecosystem to be easily plugged
into the library. [Logrus][logrus] for example.
See the additions in the README for usage information and other details.
Fixes #813.
r? @brandur (WIP.)
[logrus]: https://github.com/sirupsen/logrus/

Implement leveled logging

---

log.go
log_test.go

Adds level prefixes to the default `LeveledLogger` which will look
something like:
[DEBUG] A debug message
[INFO] An informational message
[WARN] A warning message
[ERROR] An error message
I also included a log test suite which I actually wrote for the last
leveled logging patch, but apparently completely forgot to commit.

Add log prefixes + test suite

---

charge.go
customer.go
invoice.go
invoiceitem.go
issuerfraudrecord.go
issuing_authorization.go
issuing_card.go
issuing_cardholder.go
issuing_dispute.go
issuing_transaction.go
loginlink.go
order.go
paymentintent.go
payout.go
plan.go
product.go
refund.go
reversal.go
sub.go
subschedule.go
token.go
token/client_test.go
topup.go
transfer.go

cc @mickjermsurawong-stripe who found all of those for us.

Add a long list of missing params and properties

---

charge/client_test.go
paymentintent/client_test.go

- This adds non-null params for capture endpoint to the existing test-suite.
- Capture endpoints for charge/payment intent actually doesn't have any required params, but adding the existing params here allow me to generate the fully-populated params to schema of the params for comparison with OpenAPI. 
- From completeness of test standpoint, I think this PR does add value. Although if people use this for examples, it can be misleading.

Add non-null params for capture in test

---

usagerecordsummary/client.go

I noticed the userrecordsummary package was using stripe.Charge which seemed like a simple copy-paste bug.

userrecordsummary: replace stripe.Charge with stripe.UserRecordSummary

---

.travis.yml
customer.go
invoice.go
paymentintent.go
sub.go
testing/testing.go

This is now ready to be released. Those fields will be public later this week and are stable. Having this out ahead of time is likely the best approach.

Add support for payment_intent on invoice and default_payment_method

---

paymentintent.go

cc @stripe/api-libraries @garrett-stripe

Add support for `confirmation_method` on PaymentIntent

---

issuing_card.go
issuing_cardholder.go

cc @stripe/api-libraries @zacht-stripe

Add support for `spending_limits` with Issuing Card and Cardholder

---

stripe.go
stripe_test.go

As mentioned in #830, we occasionally have a situation where non-JSON
data comes back to a client even though this is not supposed to happen.
Unfortunately, when it does, the error message produced by Go isn't very
good and doesn't help much with debugging.
Here we add a new helper function for unmarshaling JSON in standard or
error responses that behaves normally in the normal cases, and in case
of a failure, adds more context to the standard library's error and
logs.
Fixes #830.

Add more context when failing to unmarshal JSON

---

charge.go

This PR adds the fields we just approved for the `payment_method_details[card][three_d_secure]` hash on `Charge`. In the future we will add more information but we want to get those out quickly for users to be able to identify 3DS-based Charges on PaymentMethod.
cc @stripe/api-libraries @asolove-stripe

Add basic fields in Charge's PMD 3DS field

---

checkout/session/client.go
checkout/session/client_test.go
checkout_session.go
client/api.go

This resource is now ready to be released. The PR has been updated to match the latest spec.

Add support for the Checkout Session resource

---

issuing/card/client_test.go
issuing_card.go

This fixes an issue where `spending_limits` was assumed to be a struct instead of a slice of structs as documented [here|https://stripe.com/docs/api/issuing/cards/object#issuing_card_object-authorization_controls-spending_limits]
cc @zacht-stripe

Fix `spending_limits` to be a slice as there

---

account/client_test.go
checkout/session/client_test.go
issuing/card/client_test.go
paymentintent/client_test.go
paymentsource/client_test.go
product/client_test.go
stripe.go
stripe_test.go
webhookendpoint/client_test.go

I ran into a [common mistake in golang](https://developmentality.wordpress.com/2014/02/25/go-gotcha-0-why-taking-the-address-of-an-iterated-variable-is-wrong/) when writing my own code to go from a `[]string` to `[]*string` for use in the `PaymentMethodTypes` field.
This adds a helper function to do it correctly. If we want to merge this PR, I also think that we should update the examples in the documentation to use it.

Add helper to go from []T to []*T for string, int64, float64, bool

---

.travis.yml
client/api.go
customer.go
invoice.go
taxid.go
taxid/client.go
taxid/client_test.go
testing/testing.go

Add support for TaxID resource and APIs

---

client/api.go
customer.go
invoice.go
invoiceitem.go
sub.go
sub/client_test.go
subitem.go
subschedule.go
taxrate.go
taxrate/client.go
taxrate/client_test.go

This PR adds support for the `TaxRate` resource and APIs. It also modifies all relevant objects that are impacted by this new ship.
cc @vihari-stripe @george-stripe

Add support for TaxRate

---

file.go
file/client_test.go
file_test.go

Add support for [`file_link_data`](https://stripe.com/docs/api/files/create#create_file-file_link_data) in file creation requests.
The implementation is a bit of a hack: it uses `form` to flatten and stringify the contents of `file_link_data`, then parses the resulting query string to add the key/value pairs to the multipart buffer.
I've manually checked the contents of the request:
```
--554f676cf198d9e32740e881eb8cf161d311586da9b3cceaea7fcbe06135
Content-Disposition: form-data; name="purpose"
dispute_evidence
--554f676cf198d9e32740e881eb8cf161d311586da9b3cceaea7fcbe06135
Content-Disposition: form-data; name="file"; filename="test_data.pdf"
Content-Type: application/octet-stream
<snip> …
```

Add support for file_link_data in file creation requests

---

stripe.go

Just a minor thing I noticed while trying to update a Stripe client to specify `MaxNetworkRetries`, since the default is 0. Apologies if this is somehow intentional.
---
The `SetBackend` method updates one of the members of the package-level variable `backends`. Since it's a pointer, it's probably safe on most architectures. But the `Backends` struct already has a `sync.RWMutex` field, and earlier in the file the `GetBackend` function goes through the trouble of explicitly acquiring a read and possibly a write lock. See:
https://github.com/stripe/stripe-go/blob/d94ce0ed857fb1571b9b30bd24430bdac3d50c0f/stripe.go#L666
So to be safe, and consistent with the rest of the code, it makes sense to acquire a write lock before updating the `backends` value.

Lock before changing field of backends

---

terminal_connectiontoken.go
terminal_location.go
terminal_reader.go

Same as https://github.com/stripe/stripe-dotnet/pull/1610
cc @stripe/api-libraries @daz-stripe

Mark OperatorAccount as deprecated across Terminal endpoints

---

Makefile
client/api.go
scripts/check_api_clients/main.go
scripts/test_with_stripe_mock/main.go

When adding a new package with a `Client` struct, it's really easy to
forget to add it to the big list of clients in `client.API`, and we
often have to rely on user reports to tell us that we forgot about it.
Here we add a script to run with CI which looks for packages with a
`Client` and compares that list against what's in `client.API`, then
errors if any are missing from the latter.
Also adds a few clients that were missing from the list.
---
A note on design: I wrote the script in Go because (1) it doesn't make a
bad scripting language, (2) we get a lot of typing safety that some Ruby
thing wouldn't give us, and (3) it allowed me to leverage Go's built in
AST parser for its own syntax so we don't have to do as much fuzzy
matching against …

Add test script to check that all clients are included in `client.API`

---

invoice.go

Just through bad copy/paste this ended up using camelcase instead of
snakecase.
Fixes #856.

Fix invoice's `PaymentIntent` to its JSON tag uses snakecase

---

sub.go

This field just got added: https://stripe.com/docs/api/subscriptions/object#subscription_object-start_date

Add StartDate on Subscription

---

.travis.yml
capability.go
capability/client.go
capability/client_test.go
client/api.go
testing/testing.go

Add support for the Capability resource and APIs

---

paymentintent.go

r? @brandur @remi-stripe 
Adds `off_session` parameter [0] to PaymentIntent create and confirm.
[0] https://stripe.com/docs/api/payment_intents/confirm#confirm_payment_intent-off_session

Add OffSession parameter to PaymentIntent

---

.travis.yml
radar/earlyfraudwarning/client.go
radar/earlyfraudwarning/client_test.go
radar_earlyfraudwarning.go
testing/testing.go

Add support for `radar.early_fraud_warning` resource

Add support for radar.early_fraud_warning resource

---

.travis.yml
stripe.go
testing/testing.go

Like https://github.com/stripe/stripe-java/pull/781. I'd rather release this after #862 in order to avoid forcing people to upgrade, but lmk what you prefer.

Pin library to API version 2019-05-16

---

terminal_connectiontoken.go

Add support for `location` on `ConnectionToken`

---

stripe.go

As discussed in #869, breaks apart how Stripe errors are logged so that
status 402 errors go to info instead of error. This is meant to signal
that those errors are probably prompted by user data (as opposed to
sending invalid parameters or something), and handling them differently
allows integrations to avoid filling their error logs with messages that
they can't really prevent.
Fixes #869.
r? @ob-stripe

Log only to info on 402 errors from Stripe

---

account.go

Add missing Account settings

---

README.md
stripe.go

Cf. https://github.com/stripe/stripe-ruby/pull/800.

Enable request latency telemetry by default

---

invoice.go
sub.go

* Slight modifications to documentation for the `collection_method` field (replaces `billing`).

Doc changes for Collection Method

---

.travis.yml
client/api.go
error.go
paymentintent.go
paymentintent/client_test.go
setupintent.go
setupintent/client.go
setupintent/client_test.go
testing/testing.go

New attempt at adding `SetupIntent` to stripe-go

Add support for the `SetupIntent` resource and APIs

---

setupintent.go
setupintent_test.go

Quick fix as `NextAction` is its own resource on `SetupIntent`.
r? @remi-stripe (going to self-approve as we need to release)

Separate NextAction as its own for SetupIntent

---

card.go

This is supported https://stripe.com/docs/api/cards/object#card_object-address_zip_check but was missing

Add `unavailable` as possible value on `CardVerification`

---

invoice.go
sub.go
subitem.go

Those features are shipping on Monday 7/15 to support SCA for Billing
* Add `payment_behavior` and `off_session` when creating or updating a `Subscription`
* Add `off_session` when paying an `Invoice`.
* Add `pending_setup_intent` on `Subscription.
Do not review yet as there might be more fields after all

Add support for SCA features for Billing

---

paymentintent.go
setupintent.go

Add support for PaymentMethodOptions on PaymentIntent and SetupIntent. Also adds `Confirm` and `ReturnUrl` on SetupIntent creation.
r? @ob-stripe 

Add support for PaymentMethodOptions on PaymentIntent and SetupIntent

---

creditnote.go

This adds `VoidedAt` on `CreditNote`
r? @ob-stripe 

Add support for VoidedAt on CreditNote

---

subitem.go

Add OffSession to SubscriptionItem update

---

stripe.go

See #866, but once in a while when using HTTP/2, stripe-go sends an
empty request body which then results in a 400 back from the server.
We tracked the issue down to this one open on the Go language's HTTP/2
implementation:
https://github.com/golang/go/issues/32441
For now, the best thing we can do is disable HTTP/2 by default for new
integrations. When the bug is fixed, we can turn it back on again.
r? @dcarney-stripe

Disable HTTP/2 by default

---

charge.go

Add support for the missing `Authenticated` field for 3DS `Charge`.

Add missing Authenticated field for 3DS charges

---

charge.go
source.go

Putting up for naming review, this was kinda a gnarly one for naming.
I saw another reference of `...ItemsParams` so I used `SourceOrderItemsParams` not sure if that's better as `SourceOrderItemParams` (single item param, technically.)
Also, for the deserialized json object having SourceSourceOrder... everywhere seems a little odd :)

Add support for Klarna and SourceOrders

---

paymentintent.go
setupintent.go

Fix the issue that @yep found in https://github.com/stripe/stripe-go/pull/908 but across both resources and in a non-breaking way.

Fix typo in property name for PaymentMethodOptions

---

charge.go
checkout_session.go
paymentintent.go
setupintent.go

* support for `payment_method_details[card][moto]` on `Charge`
* support `statement_descriptor_suffix` on `Charge` and `PaymentIntent`
* support `subscription_data[application_fee_percent]` on Checkout `Session`
r? @ob-stripe 

Add various changes to the API

---

webhook/client_handler_test.go

Updates the webhook handler example to use `http.MaxBytesReader` to
protect against a malicious client streaming an endless request body.
We're making a similar change in our server side documentation examples,
so I'm updating this spot as well for consistency.
r? @rattrayalex-stripe

Update webhook handler example to use `http.MaxBytesReader`

---

.travis.yml
account.go
account_test.go
error.go
paymentintent.go
paymentintent/client_test.go
paymentintent_test.go
person.go
setupintent.go
stripe.go
stripe_test.go
testing/testing.go

* Pin to API version 2019-08-14
* Rename AccountCapabilityPlatformPayments to AccountCapabilityTransfers
* Add `Executive` in `PersonRelationship`
* Remove `PayentMethodOptions` as there was a typo which was fixed.
* Make `OffSession` only support booleans on `PaymentIntent`
* Remove `PaymentIntentLastPaymentError` and use `Error` instead
* Move `DeclineCode` on `Error` to the `DeclineCode` instead of `string`
r? @ob-stripe @brandur-stripe (tagging you both are there are multiple changes

Move to API version 2019-08-14 and other changes

---

issuerfraudrecord.go
radar/earlyfraudwarning/client.go

Fixes https://github.com/stripe/stripe-go/issues/917
r? @ob-stripe 

Properly use /v1/radar/early_fraud_warnings as the API

---

paymentmethod.go

Fix issue reported in https://github.com/stripe/stripe-go/issues/920
r? @ob-stripe 

Fix parameter on PaymentMethod creation that does not exist

---

invoice.go
sub.go
subschedule.go

* Add `Schedule` to `Subscription`
* Add missing parameters for the Upcoming Invoice API
* `Schedule`
* `SubscriptionCancelAt`
* `SubscriptionCancelNow`
* Add missing properties and parameters for a `SubscriptionSchedule` phase:
* `BillingThresholds`
* `CollectionMethod`
* `DefaultPaymentMethod`
* `InvoiceSettings`
r? @ob-stripe 
(Looks like we also need to fix the List Lines on upcoming invoices here in the future)

A few Billing changes

---

CHANGELOG.md

r? @remi-stripe (self-approving)

Fix the changelog to properly say what changed

---

stripe_test.go

Moves `stripe_test.go` out of the `stripe_test` package and into
`stripe`. This makes it consistent with all other `*_test.go` files in
the top-level package. The upside of the change is that it will allow
us to test certain unexported functions without having to export them.
The downside is that the hygiene isn't quite as good because we're no
longer just testing against the package's public interface which may
reduce flexibility in future changes.
Go standard library convention seems to use both methods. Just looking
through the `net/http` source code for example, you can find tests in
the `http` package _and_ in the `http_test` package depending on the
file.
I've been wanting to making this change for a while because it'd give us
a route to making internal-ish structures like …

Put `stripe_test.go` into main `stripe` package

---

stripe.go
stripe_test.go

Brings stripe-go's retry code in-line with what we currently understand
to be the best practices as already implemented in stripe-node and
stripe-ruby. Basically has the effect of adding some 500s and 503s to
results that will be retried.
r? @ob-stripe

Bring retry code in-line with current best practices

---

refund.go

Fixes https://github.com/stripe/stripe-go/issues/929
r? @ob-stripe 

Add `FailureReason` to `Refund`

---

subschedule.go

Add support for `EndBehavior` on `SubscriptionSchedule`

---

stripe.go

While looking in #936 I accidentally realized that in #935 I'd
inadvertently duplicated error logging -- I add a log statement in `Do`
for API errors, but `ResponseToError` was already logging them.
Here I've resolved #936 and re-arranged logging somewhat so that we're
more consistent _where_ the logging happens. Most logs are now produced
directly in `Do` so it's easier to follow what's getting logged.
I haven't actually changed our previous policy around 402s -- just moved
it up a function. The previous idea (which I'd forgotten about) was that
because 402s are often induced by the _users of integrations_ instead of
integrations themselves, we just do an `Infof` log for it. Other errors
get an `Errorf` because they're more likely to be the integration's
fault, and actionable.
Fixes …

Rearrange error logging so that 402 doesn't log an error

---

stripe.go

In a few cases it's possible for `ResponseToError` to return an error
that's not a `*stripe.Error`. This should never happen, but could occur
if say the Stripe API returned a mangled JSON blob, but somehow managed
to close the connection properly. It's an unlikely scenario, but even
so, it's better not to let it slip through the cracks.
I also moved one more logging statement out of `ResponseToError` so we
can log everything of this type in one place.
r? @ob-stripe (Sorry, one more tweak on the last patch.)

Also log error in case of non-`stripe.Error`

---

.travis.yml
account.go
account/client_test.go
person.go
testing/testing.go

This adds new properties and parameters to reflect the verification state of an `Account` and a `Person`:
* `company[verification]` on `Account` to support passing a document to verify a business entity.
* `verification[additional_document]` on `Person` for cases where a second document might be required for identity verification.
r? @ob-stripe

Changes to Account and Person to represent identity verification state

---

error.go

The `Error` object has most properties top-level but we didn't have `DeclineCode`. Instead, it was inside `Err` if it was a `CardError`.
While it works, I think it might be easier to just make it top-level which is what this PR is introducing.
Fixes https://github.com/stripe/stripe-go/issues/948

Add support for `DeclineCode` on `Error` top-level

---

balancetransaction.go
payout.go
recipienttransfer.go
transfer.go
transfer_test.go

See #946 for context, but we're removing some `MarshalJSON`
implementations that are "lossy" in that they throw out information that
might be useful to somebody.
Note that we don't actually marshal API resources as part of normal
operations in stripe-go, so the only users that this will affect are
those that are manually re-marshaling resources to JSON in their
integrations.
Fixes #946.
---
Targets the V64 integration branch in # instead of `master`.

Remove lossy "MarshalJSON" implementations

---

stripe.go
stripe_test.go

As seen in stripe-node, adds support for the `Stripe-Should-Retry`
header which is sent by the API when it explicitly would like us to
either retry or _not_ retry.
I'll add `Retry-After` separately at some point, but I punted it on it
for now given that we're not using it yet.
See: https://github.com/stripe/stripe-node/pull/692
r? @ob-stripe

Support `Stripe-Should-Retry` header

---

paymentmethod.go

Related to https://github.com/stripe/stripe-go/issues/958
r? @ob-stripe 

Mark `Customer` on `PaymentMethodDetachParams` as deprecated

---

paymentmethod.go

Fixes the previous incorrect PR as the wrong parameter was marked as deprecated.
r? @ob-stripe 

Properly tag `Customer` as deprecated in `PaymentMethodDetachParams`

---

balance/client.go
balance/client_test.go
charge.go
customer.go
invoice.go
paymentintent.go
paymentmethod.go
sub.go
subschedule.go
terminal_connectiontoken.go
terminal_location.go
terminal_reader.go

Remove TODOs and deprecated parts
* Removed `GetBalanceTransaction` and `List` from the `balance` package. Prefer using `Get` and `List` in the `balancetransaction` package.
* Removed `ApplicationFee` from the `charge` and `paymentintent` packages. Prefer using `ApplicationFeeAmount`.
* Removed `TaxInfo` and related fields from the `customer` packager. Prefer using the `customertaxid` package.
* Removed unsupported `Customer` parameter on `PaymentMethodParams` and `PaymentMethodDetachParams` in the `paymentmethod` package.
* Removed `Billing` properties in the `invoice`, `sub` and `subschedule` packages. Prefer using `CollectionMethod`.
* Removed the `InvoiceBilling` type from the `invoice` package. Prefer using `InvoiceCollectionMethod`.
* Removed the `SubscriptionBilling` type from the …

Remi remove todos

---

charge.go
source.go
source/client_test.go

@remi-stripe  @ob-stripe 
I am adding AUBECS Support here. Have tested locally and running fine. 

Add AU BECS Debit Support

---

bankaccount.go

This change adds the already present (network-wise) Account field to the BankAccount struct, and allows the BankAccount to become self contained --no longer needing to tuple an Event struct alongside the BankAccount when handling webhooks.
Tested working for `sc.BankAccounts.New` and when responding to a `account.external_account.updated` event in a webhook.

Add the Account field to BankAccount

---

charge.go
paymentmethod.go

@remi-stripe @ob-stripe
Add Fpx PaymentMethod Support

Add FPX PaymentMethod Support

---

.travis.yml
account_test.go
person.go
stripe.go
testing/testing.go

- Rename `AccountOpener` to `Representative` on `Account` and `Person`
- Update to latest API version `2019-10-08`
r? @ob-stripe 

Update to latest API version 2019-10-08

---

terminal_reader.go

Add `DeviceType` filter when listing Terminal `Reader`s

---

order.go

The field Fulfilled had a misspelled JSON tag

JSON tag spelling mistake

---

charge.go
checkout_session.go
issuing_cardholder.go
sub.go
subitem.go
taxid.go

r? @ob-stripe 
This PR adds multiple changes
- `Requirements` on Issuing `Cardholder`.
- `PaymentMethodDetails.AuBecsDebit.Mandate` on `Charge`.
- `PaymentBehavior` on `Subscription` creation can now take the value `pending_if_incomplete`.
- `PaymentBehavior` on `SubscriptionItem` creation is now supported.
- `SubscriptionData.TrialFromPlan` is now supported on Checkout `Session` creation.
- New values for `TaxIDType`.

Various API changes

---

.travis.yml
README.md
stripe.go
subschedule.go
subschedule/client_test.go
testing/testing.go

r? @ob-stripe 
* Pin to the latest API version `2019-10-17`
* Remove `RenewalBehavior` on `SubscriptionSchedule`
* Remove `RenewalBehavior` and `RenewalInterval` as parameters on `SubscriptionSchedule`

Move to API version 2019-10-17

---

sub.go

Add support for `PendingInvoiceItemInterval` on `Subscription`

---

charge.go
paymentintent.go

* Add support for `PaymentMethodOptions` on the read side on `PaymentIntent`
* Add support for installments on `PaymentIntent` and `Charge`
r? @ob-stripe 

Add support for installments on `PaymentIntent` and `Charge`

---

paymentmethod.go

I incorrectly removed this parameter in a recent PR. Adding it back and making it explicitly why it's here
r? @ob-stripe 
cc @stripe/api-libraries  @XplittR

Add support for cloning saved PaymentMethods

---

.travis.yml
stripe.go
subschedule.go
testing/testing.go

Updates API version to: `2019-11-05`
Updates stripe-mock minimum version to `0.71.0`
Adds: `DefaultSettings` with `BillingThresholds`, `CollectionMethod`, `DefaultPaymentMethod`, `InvoiceSettings` to `SubscriptionSchedule`
Removes:  `BillingThresholds`, `CollectionMethod`, `DefaultPaymentMethod`, `DefaultSource`, `InvoiceSettings` from `SubscriptionSchedule`

Add DefaultSettings to Subscription Schedules

---

.travis.yml
client/api.go
mandate.go
mandate/client.go
mandate/client_test.go
paymentintent.go
paymentmethod.go
setupintent.go
testing/testing.go

Multiple API changes
* Add support for the `Mandate` API Resource
* Add support for SEPA Debit and iDEAL on `PaymentMethod`
* Add support for `mandate` on `SetupIntent`
* Add support for `mandate` on `PaymentIntent`
r? @ob-stripe 

Adding support for iDEAL and SEPA debit on PaymentMethod

---

.travis.yml
charge.go
dispute.go
refund.go
refund/client_test.go
testing/testing.go

Multiple API changes
* Add `Disputed` to `Charge`
* Add `PaymentIntent` to `Refund` and `Dispute`
* Add `Charge` to `DisputeListParams`
* Add `PaymentIntent` to `RefundListParams` and `RefundParams`

Add disputed to charge and allow listing disputes by charge

---

.travis.yml
issuing/cardholder/client_test.go
issuing_cardholder.go
paymentmethod.go
testing/testing.go

Adds `Individual` and `Company` to `IssuingCardHolder`
Adds `PaymentMethodSepaDebitParams` for `PaymentMethodParams`
Bumps `stripe-mock` version to `0.74.0`

Add `individual` and `company` to IssuingCardholder

---

issuing_authorization.go

Add support for ViolatedAuthorizationControls on Issuing Authorization

---

dispute.go

Adds support for filtering the list of disputes by a `PaymentIntent`.
I noticed that the Charge & PaymentIntent are mutually exclusive, but wasn't sure if we have a mechanism for that in the bindings. 

Add payment_intent filter for listing disputes

---

subschedule.go
subschedule/client_test.go
subschedule_test.go

Added support for `start_date: "now"` on Subscription Schedule creation similarly to how we do it for trials for example.

Support for the `now` on `StartDate` on Subscription Schedule creation

---

.travis.yml
creditnote.go
creditnote/client.go
creditnote/client_test.go
testing/testing.go

Add the new preview endpoint on `CreditNote`. Also rename `OutOfBandAmount` which had a typo.
r? @ob-stripe 

Add support for `CreditNote` preview

---

.travis.yml
creditnote.go
invoice.go
paymentintent.go
setupintent.go
stripe.go
subschedule.go
terminal_location.go
testing/testing.go

Multiple API changes as we release a new major version
* Pin to API version `2019-12-03`
* Rename `InvoiceBillingStatus` to `InvoiceStatus` for consistency
* Remove typo-ed field `OutOfBankdAmount` on `CreditNote`
* Remove deprecated `PaymentIntentPaymentMethodOptionsCardRequestThreeDSecureChallengeOnly` and `SetupIntentPaymentMethodOptionsCardRequestThreeDSecureChallengeOnly` from `PaymentIntent` and `SetupIntent`.
* Remove `OperatorAccount` on `TerminalLocationListParams`
r? @tomer-stripe @richardm-stripe 

Pin to API version 2019-12-03 and remove deprecated fields

---

charge.go
paymentmethod.go

Similar to the java one but not touching `SourceTransaction` as stripe-go doesn't support the hash specific for now and since this is low usage I want to avoid adding features that will go away in the future.

Add support for `Network` on `Charge`

---

terminal_location.go
terminal_reader.go

Adds support for `metadata` and `livemode` on `TerminalReader` and `TerminalLocation` 

Add `metadata` and `livemode` to Terminal Reader and Location

---

account.go

Adds `executives_provided` to `AccountCompany`

Adds `executives_provided` to AccountCompany

---

issuing_card.go

r? @ob-stripe 
cc @stripe/api-libraries @zacht-stripe

Fix issues with Issuing spending limits

---

.travis.yml
creditnote.go
creditnote/client.go
creditnote/client_test.go
testing/testing.go

Add support for `CreditNoteLineItem`

---

invoice.go
sub.go
subitem.go

Think I should re-use the existing SubscriptionItem for subscription_items like this? or create a whole new `SubscriptionPendingUpdateSubscriptionItem` etc.

Adds PendingUpdate to Subscription

---

checkout_session.go

Only add support on the resource as `metadata` is automatically supported on all params class via the nested `Params` (even on resources that don't support it).

Add `Metadata` support on Checkout `Session`

---

taxid.go

Add new values for `TaxIDType` and fix `TaxIDTypeCHVAT`

---

issuing_card.go

Also noticed we were missing tracking_url so added that to the Shipping struct. LMK if that was left off intentionally :) Also, I'm pretty sure it's `TrackingURL` in Go and not `TrackingUrl` but wanted to point out incase I got that wrong.

Add support for shipment speed for issuing cards

---

taxid.go

Add support for `TaxIDTypeESCIF` on `TaxId`

---

balance.go
balance_test.go
payout.go
transfer.go

Hi folks,
Closing https://github.com/stripe/stripe-go/pull/1025 in favor of this one per Remi's latest comment.
Have incorporated Remi's new test file (💯) as well as the `connect_reserved` addition, consolidated here into a single PR off this branch rather than a fork.
---
Summary of changes once more for posterity:
- Support the `source_types` hash on the pending/available top-level balance object:
https://stripe.com/docs/api/balance/balance_object#balance_object-available-source_types
- Support the `connect_reserved` top-level object on the `/v1/balances` endpoint:
https://stripe.com/docs/api/balance/balance_object#balance_object-connect_reserved
- Support the new `fpx` source type constant as a developer affordance in preparation for Stripe's broader FPX rollout (currently in private …

Support `source_types` and `connect_reserved` from `/v1/balances` and add `fpx` source_type string constants

---

invoice.go

Fixes https://github.com/stripe/stripe-go/issues/1032
r? @ob-stripe 

Make `Subscription` expandable on `Invoice`

---

subschedule.go

Add support for `ProrationBehavior` on `SubscriptionSchedule`

---

.travis.yml
checkout/session/client.go
checkout/session/client_test.go
checkout_session.go
testing/testing.go

Add support for listing Checkout `Session` and passing tax rate information

---

.travis.yml
customer.go
stripe.go
testing/testing.go

Multiple API changes:
* Move to latest API version `2020-03-02`
* Add support for `NextInvoiceSequence` on `Customer`
r? @ob-stripe 

Move to latest API version `2020-03-02` and other API changes

---

issuing_authorization.go

Multiple API changes:
* Add new values for `IssuingAuthorizationRequestHistoryReason`
* Add `ExpiryCheck` in `VerificationData`
r? @ob-stripe 

Add new reason values and `ExpiryCheck` for Issuing `authorization

---

issuing_authorization.go

Docs: https://stripe.com/docs/api/issuing/authorizations/object#issuing_authorization_object-verification_data-three_d_secure
r? @ob-stripe 

Add support for `ThreeDSecure` on Issuing `Authorization`

---

issuing_authorization.go
issuing_card.go
issuing_cardholder.go

Multiple changes for Issuing APIs
* Rename `Speed` to `Service` on Issuing `Card`
* Rename `WalletProvider` to `Wallet` and `AddressZipCheck` to `AddressPostalCodeCheck` on Issuing `Authorization`
* Mark `IsDefault` as deprecated on Issuing `Cardholder`
r? @ob-stripe 

Multiple changes for Issuing APIs

---

issuing_authorization.go
issuing_card.go

Multiple API changes for Issuing:
* Add `Amount` and `AmountCurrency` to `Authorization`
* Add `MerchantAmount` and `MerchantCurrency` to `Authorization`
* Add `PendingRequest` to `Authorization`
* Add `ReplacedBy` to `Card`
* Add `Amount` and `Metadata` to `AuthorizationApproveOptions`
* Add `Metadata` to `AuthorizationDeclineOptions`
r? @ob-stripe 

Add new fields to Issuing `Card` and `Authorization`

---

.travis.yml
issuing/card/client_test.go
issuing/cardholder/client_test.go
issuing_authorization.go
issuing_card.go
issuing_cardholder.go
testing/testing.go

Multiple API changes for Issuing
* Add support for `SpendingControls` on `Card` and `Cardholder`
* Add new values for `Reason` on `Authorization`
* Add new value for `Type` on `Cardholder`
* Add new value for `Service` on `Card`
* Mark many classes and other fields as deprecated for the next major
r? @ob-stripe

Multiple API changes for Issuing

---

.travis.yml
issuing/authorization/client.go
issuing/authorization/client_test.go
issuing/card/client.go
issuing/card/client_test.go
issuing/cardholder/client_test.go
issuing/dispute/client_test.go
issuing_authorization.go
issuing_card.go
issuing_cardholder.go
issuing_dispute.go
issuing_transaction.go
testing/testing.go

This PR removes all the deprecated features from the Issuing API and renames all relevant classes to ensure we have the right structure for codegen.
r? @richardm-stripe @ob-stripe 
---
Note: Targets major version integration branch in #1055.

Remove all beta features from Issuing APIs

---

charge.go
subschedule.go
taxrate.go

Multiple breaking API changes:
* `PaymentIntent` is now expandable on `Charge`
* `Percentage` was removed as a filter when listing `TaxRate`
* Removed `RenewalInterval` on `SubscriptionSchedule`
* Removed `Country` and `RoutingNumber` from `ChargePaymentMethodDetailsAcssDebit`

Multiple breaking API changes

---

README.md
log.go
log_test.go
stripe.go
stripe_test.go
testing/testing.go

For a very long time, stripe-go logged by way of the `Printfer`
interface:
``` go
type Printfer interface {
Printf(format string, v ...interface{})
}
```
`Printfer` had a few problems: it didn't allow any kind of granularity
around logging levels, didn't allow us to behave well by sending errors
to `stderr` and other output to `stdout`, and wasn't interoperable with
any popular Go loggers (it was interoperable with the one in the
stdlib's `log`, but serious programs tend to move away from that).
A while back, I introduced the new `LeveledLogger` interface, which
corrected the deficiencies with `Printfer`.
We made quite a bit of effort to stay compatible with the existing
configuration options around logging like the `Logger` and `LogLevel`
globals, while also adding new ones for the …

Clean up logging for next major

---

README.md
error_test.go
oauth/client_test.go
order/client_test.go
stripe.go
stripe_test.go
testing/testing.go

Currently, it's possible to have the library retry intermittently failed
requests by configuring `MaxNetworkRetries` on a `BackendConfig`.
Because this is a pretty useful feature that many users will never
discover because it's off by default, we've been mulling around the idea
internally to change that default on the next major so that more people
get access to it. We're about to release V71, so now is an opportune
moment.
The slight complication is that `BackendConfig.MaxNetworkRetries` is
currently a simple `int`, which means that it's hard for us to recognize
an unset value versus an explicitly set 0 (the same problem we had with
fields on parameter structs for years). So by example, this code is
problematic:
``` go
if conf.MaxNetworkRetries == 0 {
backend.MaxNetworkRetries = 2
}
``` …

Default number of network retries to 2

---

v71_migration_guide.md

V71 has a few non-trivial breaking changes bundled in, so add a guide
with more lengthy explanations on how to handle each one (as we've done
previously on occasion like for the big V32 major).
r? @ob-stripe
---
Note: Targets the branch in #1055 for V71 integration.

Add V71 migration guide

---

.travis.yml
Makefile

Unfortunately, the confluence between Go 1.13+ (which I recently added
to CI) and the change to use Go Modules is failing our coverage
pipeline. The addition of a major version in require paths seems to
confuse the scripts:
```
$ make coverage
go list ./... | xargs -n1 -I {} -P 4 go run scripts/test_with_stripe_mock/main.go -covermode=count -coverprofile=../../../{}/profile.coverprofile {}
open ../../../github.com/stripe/stripe-go/v70/accountlink/profile.coverprofile: no such file or directory
```
There's a comment on the `make coverage` task that implies that we
shouldn't need to do our `go list ./...` trick anymore because Go can
now create a full coverage report from just a single `go test ./...`
invocation. This seems to work for me locally, so I'm trying it here.
The only build this …

Fix code coverage toolchain in CI

---

invoice.go

Even though this is not documented this exists and we should support it now. This was requested by a developer and I filed the doc issue internally.

Add `Deleted` on `Invoice`

---

.travis.yml
billingportal/session/client.go
billingportal/session/client_test.go
billingportal_session.go
client/api.go
testing/testing.go

Add support for the `BillingPortal` namespace and the `Session` API and resource

---

checkout_session.go

Add support for `Coupon` when for subscriptions on Checkout

---

stripe.go

Spotted some empty lines in the logs when using this library, like so:
```
2020/04/22 22:59:25 Requesting POST api.stripe.com/v1/customers
2020/04/22 22:59:25 Request completed in 207.541611ms (retry: 0)

remove spurious newline in logs

---

account.go

Similar to https://github.com/stripe/stripe-node/pull/876 and adding the missing `CardIssuing` property.

Add support for `JCBPayments` and `CardIssuing` as a `Capability`

---

error_test.go
stripe_test.go

There are a few tests in the top-level package (especially in
`stripe_test.go`) that produce either (1) a lot of logging, or (2) error
logging even on a successful run. This normally isn't a problem because
Go captures output by default when `go test .` is run, but it can be a
little alarming when a test case fails and a swath of unrelated logging
is produced.
Here we still keep most test logging on by default (so you will still
see output when a test case fails), but turn off logging specifically
for tests that produce either lots of output or error output that we
expect to happen. My selection methodology was basically to go through
with a `-test.v` and eyeball for anything in either of these categories.

Clean up logging in some noisier tests

---

bankaccount.go

According to the [docs](https://stripe.com/docs/api/customer_bank_accounts/object), object is an attribute of the bank account object but the struct does not have such a field.

Add `Object` on `BankAccount`

---

taxid.go

Add support for Brazilian tax ids on `TaxID`

---

subitem.go

This fixes some parameters shipped recently in `price_data[recurring]` even though they are not supported. This applies across the API but the main class is shared.
While technically breaking, this has never worked so we should do a minor version.
This mirrors https://github.com/stripe/stripe-java/pull/1025
r? @ob-stripe 

Fix parameters supported in `Recurring` for `PriceData` across the API

---

checkout/session/client_test.go
checkout_session.go

Fixes https://github.com/stripe/stripe-go/issues/1092
r? @ob-stripe 

Add support for `Metadata` for `PaymentIntentData` and `SubscriptionData` on Checkout `Session`

---

.travis.yml
checkout/session/client.go
checkout/session/client_test.go
checkout_session.go
lineitem.go
lineitem/client.go
testing/testing.go

Add support for the `LineItem` resource and APIs

---

README.md

Previous to Go Modules, it was often necessary to manually fetch
dependencies with `go get` before using them.
With Go Modules, the much more standard way now is to make sure a
project is initialized with Go Modules (`go mod init`), then just start
including modules in your `import` paths. Go will resolve them
automatically.
This came up in #1098 because our instructions still recommend `go get`.
Here, we change them to recommend using `go mod init` + `import`
instead.

Fix misleading install instructions for stripe-go

---

charge.go

Add support for `Result` and `ResultReason` on `ChargePaymentMethodDetailsCardThreeDSecure`

---

taxid.go

Add support for `TaxIDTypeAETRN`, `TaxIDTypeCLTIN` and `TaxIDTypeSAVAT` on `TaxId`

---

topup.go

Fix https://github.com/stripe/stripe-go/issues/1107

Add `Metadata` and `Object` on `Topup`

---

account.go
charge.go
mandate.go
paymentmethod.go

Add support for BACS Debit as a `PaymentMethod`

---

account.go

Add support for reading SEPA and BACS debit settings on `Account`

---

error.go
stripe.go
stripe_test.go

Issue #1114 reveals a bug with `DeclineCode` on the top-level error
object.
In #949, we added `DeclineCode` on the top-level error object in
addition to where it was before on the specific `CardError` type as a
minor quality of life improvement.
It seemed like a very simple change, so we didn't put in a test, but
what we forgot about at the time was that we were already doing some
weird stuff in order to extract `DeclineCode` for `CardError`.
Specifically, we'd added this special wrapper type that extended
`Error`:
``` go
// rawErrorInternal embeds Error to deserialize all the standard error fields,
// but also adds other fields that may or may not be present depending on error
// type to help with deserialization. (e.g. DeclineCode).
type rawErrorInternal struct {
*Error
DeclineCode …
```

Fix top-level `DeclineCode` deserialization in errors

---

paymentmethod.go

This PR adds the missing `ideal` parameters to the `PaymentMethodParams`.
This parameters are referenced on the stripe [documentation](https://stripe.com/docs/api/payment_methods/object#payment_method_object-ideal) but it was not available to use it when creating a payment method with the go client.

Add `PaymentMethodIdealParams` to `PaymentMethodParams`

---

paymentmethod.go

cc @stripe/api-libraries @grahamhealy

Add missing information for BACS Debit in `PaymentMethod`

---

stripe.go

If a resource has a custom `UnmarshalJSON` file like `Charge` does, we lose the `LastResponse` property of the `APIResource` due to ordering.
Additionally—there's a guard here which doesn't make much sense which I've removed. If `v` is ever nil here, we'd panic before hitting the guard.
I found it kind of awkward to write a test for this behavior—the existing test in `stripe_test.go` doesn't expose it because it has no custom UnmarshalJSON defined; if you look at the definition for `Charge` you can see it completely overwrites the object (as do several others).

Attach LastResponse after unmarshaling

---

paymentintent.go

Similar to https://github.com/stripe/stripe-java/pull/1023
cc @stripe/api-libraries @ln-stripe

Add support for `PaymentMethodData` on `PaymentIntent`

---

.travis.yml
accountlink.go
accountlink/client_test.go
testing/testing.go

Add support for `RefreshURL` and `ReturnURL` on `AccountLink`

---

subschedule.go

* Adds `billing_cycle_anchor` to `default_settings` and `phases` for `SubscriptionSchedules`

Adds billing_cycle_anchor to default_settings and phases for SubscriptionSchedules

---

sigma_scheduledqueryrun.go

This morning while parsing a received webhook I noticed that the title field is not included within the the golang struct: https://stripe.com/docs/api/sigma/scheduled_queries/object#scheduled_query_run_object-title

The title property is missing from the SigmaScheduledQueryRun object

---

.travis.yml

Unfortunately, Testify introduced use of `errors.As` and `errors.Is`
[1], which are only available in Go 1.13+, and therefore broke use on
all older versions of Go. Speaking in a purely technical sense only,
they're in the right because only the last two Go minors are supported
at any given time (currently, 1.13 and 1.14).
We still want to support older versions of Go for now though, so here we
modify the build to only test on 1.13+. We still build the older
versions of Go which gives us decent assurance they still work. It's not
perfect, but is a decent compromise given the circumstances in that at
least they're still in our build matrix.
[1] https://blog.golang.org/go1.13-errors#TOC_3.2.

Test only on Go 1.13+

---

account.go

Add support for `Capabilities` on `Account` create and update

---

subschedule.go
subschedule/client_test.go

This parameter was always expecting a float but it's been `*int64` since we introduced this API in stripe-go. I went with `interface{}` since it is technically a breaking change, mirroring what we did for `off_session` on `PaymentIntent` in https://github.com/stripe/stripe-go/pull/887 We will move to the expected `*float64` in the next major instead. 
Can you confirm this is safe and okay despite also being a breaking change technically?

Fix `ApplicationFeePercent` on `SubscriptionSchedule` to support floats

---

ephemeralkey.go

The godoc of json.Unmarshaler says:
> https://golang.org/pkg/encoding/json/#Unmarshaler
> UnmarshalJSON must copy the JSON data if it wishes to retain the data after returning.
This code comes from the implementation of RawMessage.UnmarshalJSON.
https://github.com/golang/go/blob/074f2d800f2c7b741a080081cfcc5295b375b23d/src/encoding/json/stream.go#L275

Copy the JSON data of EphemeralKey

---

.travis.yml
account/client_test.go
accountlink/client_test.go
coupon.go
creditnote.go
discount.go
invoice.go
invoice_test.go
invoiceitem.go
testing/testing.go

Add support for multiple coupons on Billing APIs
* Add support for arrays of expandable API resources otherwise returning an array of strings by default
* Add custom deserialization to `Discount` to support expansion of the object
* Add support for `Id`, `Invoice` and `InvoiceItem` on `Discount`.
* Add support for `Discounts` on `Invoice`, `InvoiceItem` and `InvoiceLineItem`
* Add support for `DiscountAmounts` on `CreditNote`, `CreditNoteLineItem`, `InvoiceLineItem`
* Add support for `TotalDiscountAmounts` on `Invoice`
* Add `Object` to `Invoice`, `InvoiceLine`, `Discount` and `Coupon`

Add support for multiple coupons on Billing APIs

---

README.md

Adds a note to the `README.md` that mentions how it's also possible to fetch the project using `go get`.

Add a note on using `go get` to get the package

---

charge.go

That one is an enum while the previous one for `interac_present` was a string so I went and did the constants!

Add support for `AccountType` in `ChargePaymentMethodDetailsCardPresentReceipt`

---

stripe.go
stripego115.go

[Go 1.15](https://blog.golang.org/go1.15) fixes a [long-standing bug](https://github.com/golang/go/issues/32441) in the HTTP/2 client that led to HTTP/2 being disabled by default in stripe-go as part of https://github.com/stripe/stripe-go/pull/903.
This PR modifies the default HTTP/2 client for those users running Go 1.15 or above to remove the restriction against using HTTP/2.  It accomplishes this via the use of a `+build` tag (aka conditional compliation) of the new source file `stripego115.go`.
The bug is scheduled to be backported to [1.13.16](https://github.com/golang/go/issues/39278) and [1.14.8](https://github.com/golang/go/issues/39279), but even once those backports are complete, we can only conditionally compile against a _major_ release of Go, per …

Re-enable H/2 on the default HTTP client for Go 1.15+

---

charge.go

Add support for `BankName` on `ChargePaymentMethodDetailsAcssDebit`

---

file.go

Also added `Object` which is more internal.

Add support for `ExpiresAt` on `File`

---

.travis.yml
accountlink.go
charge.go
checkout_session.go
customer.go
invoice.go
stripe.go
sub.go
sub/client_test.go
subitem.go
subschedule.go
subschedule/client_test.go
testing/testing.go

Multiple API changes
* Move to latest API version `2020-08-27`
* Remove `Prorate` across Billing APIs in favor of `ProrationBehavior`
* Remove `TaxPercent` across Billing APIs in favor of `TaxRate`-related parameters and properties
* Remove `DisplayItems` on Checkout `Session` in favor of `LineItems`
* Remove `FailureURL` and `SuccessURL` on `AccountLink` in favor of `RefreshURL` and `ReturnURL`
* Remove `AccountLinkTypeCustomAccountUpdate ` and `AccountLinkTypeCustomAccountVerification ` on `AccountLink` in favor of `AccountLinkTypeAccountOnboarding ` and `AccountLinkTypeAccountUpdate `
* Remove `Authenticated` and `Succeeded` on `ChargePaymentMethodDetailsCardThreeDSecure`
* Remove `Plan`, `Quantity`, `TaxPercent` and `TrialEnd` from `Customer` creation or update in favor of the …

Multiple API changes

---

paymentintent.go

Remove deprecated parameters `SavePaymentMethod` and `Source` on `PaymentIntent`

---

.travis.yml
issuing/dispute/client.go
issuing/dispute/client_test.go
issuing_dispute.go
testing/testing.go

Add support for the Issuing Dispute APIs

---

bankaccount.go

Fixes the issue introduced in https://github.com/stripe/stripe-go/pull/1177

Fix the constant names for `BankAccountAvailablePayoutMethod`

---

paymentintent.go
paymentmethod.go

Same as https://github.com/stripe/stripe-go/pull/1125 but it was missing the `payment_method_options` changes

Add support for Sofort on `PaymentMethod` and `PaymentIntent`

---

webhookendpoint.go

Fixes https://github.com/stripe/stripe-go/issues/1181

Add `Metadata` on `WebhookEndpoint`

---

stripe.go
stripe_test.go

This patch follows up #1187 by having `shouldRetry` return a second
string value when no retry should be attempted which contains a short
informational message as to why there should be no retry. A caller can
use this for logging/informational purposes to make the retry system
less opaque.
r? @ctrudeau-stripe For review.
Also cc @remi-stripe who requested this feature.

When not retrying a request, log reason at info level

---

.travis.yml
client/api.go
product/client_test.go
setupattempt.go
setupattempt/client.go
setupattempt/client_test.go
setupintent.go
testing/testing.go

Manually implemented based on the dotnet PR: https://github.com/stripe/stripe-dotnet/pull/2211
r? @paulasjes-stripe

Add support for the `SetupAttempt` resource and List API

---

params.go

reading from rand can return an error and fail to read bytes, this
leads to the second component not being random.
This solution panics in that case, similar to getting a new uuid
https://github.com/google/uuid/blob/master/version4.go#L13-L15
the side effect is, in the case the second component is not random (an
error happened) we are now panicing instead of continuing
alternatives: 
- continue as before (maybe leave a comment)
- change the function signature to return an error, more invasive 
change and makes the function API less nice to work with
Signed-off-by: Andrew Klotz <agc.klotz@gmail.com>

handle idempotence key randomness error

---

balance.go

Fixes #1202 
> [ERROR] Couldn't deserialize JSON (response status: 200, body sample: '{\n "object": "balance",\n "available": [\n {\n "amount": 118300,\n "currency": "usd",\n "source_types": {\n "card": 118300\n }\n }\n ],\n "instant_available": [\n {\n "amount": 118300,\n "currency": "usd",\n "source_types": {\n "card": 118300\n }\n }\n ],\n "livemode": false,\n "pending": [\n {\n "amount": 0,\n "currency": "usd",\n "source_types": {\n "card": 0\n }\n }\n ]\n}\n'): json: cannot unmarshal array into Go struct field Balance.instant_available of type stripe.BalanceDetails
It needs to be `[]*Amount` instead of `*BalanceDetails`

Use correct Amount type for InstantAvailable

---

charge.go

Fixes https://github.com/stripe/stripe-go/issues/1204
r? @paulasjes-stripe 

Add support for `Mandate` in `ChargePaymentMethodDetailsSepaDebit`

---

checkout_session.go

Add support for `Discounts` to `CheckoutSessionParams`

---

params.go

We still have `TotalCount` in a list's meta information. So as to not
make a breaking change, I'm going to leave it in, but add a `Deprecated`
notice on it.
I also reword the comment because the note to "see tests" is no longer
accurate (we don't have a `total_count` sample in the suite anymore).
Replaces #1213.

Put a `Deprecated` notice on `TotalCount`

---

sub.go
subschedule.go

Support passing `TaxRates` when creating invoice items through `Subscription` or `SubscriptionSchedule`

---

paymentmethod.go

While reviewing a PR for code examples in the docs, I realized we didn't have a constant in go for the EPS payment method type and then noticed I just missed a bunch of them.
I added what was missing based on the list here: https://stripe.com/docs/api/payment_methods/object#payment_method_object-type and I also kept `card_present` and `interac_present` which should really be in that list.

Add missing constants for existing types on `PaymentMethod`

---

paymentmethod.go

Add support for passing `Bank` for P24 on `PaymentIntent` or `PaymentMethod`

---

account.go

Add support for `GrabpayPayments` as a capability on `Account`

---

token.go
token/client_test.go

Fixes #1226
Tested using Golang Testing tool and with my own project
Log of my project, I correctly get my account token
```sh
2020/11/19 12:21:43 token: &{{0xc000108ba0} <nil> <nil> <nil> 1.2.3.4 1605788503  ct_1HpC8xCMhQMU3AqAy65DO2ku false account false}
2020/11/19 12:21:43 token.ID: ct_1HpC8xCMhQMU3AqAy65DO2ku
2020/11/19 12:21:43 token.TYPE: account
```

Add support for Account and Person Tokens creation

---

account.go
file.go

Add support for `BankAccountOwnershipVerification` in `Documents` on `Account`

---

.travis.yml
account.go
account/client_test.go
testing/testing.go

re-r? @brandur-stripe 
Adds support for passing `company_registration_verification`, `company_ministerial_decree`, `company_memorandum_of_association`, `company_license` and `company_tax_id_verification` on `Documents` in `AccountParams`, [recently released](https://github.com/stripe/openapi/commit/383c876178bce75266c9abddcb65f355bacfe86b) to the Stripe API.

Add support for more verification documents

---

charge.go
paymentintent.go
paymentmethod.go
subschedule.go

cc @stripe/api-library-reviewers 
Add support for `Bank` for eps and p24 on Charge and PaymentMethod.
Add support for `TOSShownAndAccepted` on `PaymentMethodP24Params`

Add support for bank on eps/p24

---

error.go

I found that decline code 'invalid_expiry_month' is missing in error.go which I would like to refer to in my project. Please kindly consider to add it.
'invalid_expiry_month' is listed as one of decline code in the official documentation.
https://stripe.com/docs/declines/codes

Added missing decline code 'invalid_expiry_month'

---

checkout_session.go
person.go
taxid.go

* Add `nationality` to `Person` and `PersonParams` 
- (TokenParams includes PersonParams, so this also allows it to be specified on token.Create)
* Add `gb_vat` as a member of `TaxIDType` and `CheckoutSessionCustomerDetailsTaxIDsType`

API Updates

---

invoice.go

The Stripe API supports passing a `subscription_start_date` to the `invoices/upcoming` endpoint. This is missing in the `InvoiceParams` struct.

Add SubscriptionStartDate to InvoiceParams (to use with GetNext)

---

invoice.go

Adds support for `payment_settings` on the `Invoice` resource, from a recent [API Release](https://github.com/stripe/openapi/releases/tag/v16). (Skipping the "capability" part of that release for now, until that feature is fully released)

Add payment_settings to invoice

---

stripe.go
stripe_test.go

This PR fixes panic in `stripe.ParseID`, which could happen for a particular input (`"`):
```
panic: runtime error: slice bounds out of range [1:0]
```
I highly doubt that this is a real-world case, but since panic is a pretty bad thing I believe it's worth to fix it.
Also added a test case for it.
Found this with the help of [go-fuzz](https://github.com/dvyukov/go-fuzz).

Fix edge case panic in ParseID

---

lineitem.go

This fixes this property: https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-line_items-data-taxes-rate

Fix `LineItemTax` to deserialize `Rate` properly

---

billingportal_session.go

I added the new configuration resource in [the previous release](https://github.com/stripe/stripe-go/pull/1254/files), but neglected to ship the corresponding updates to billingportal_session.go. Realized this while working on codegen. Compare to [stripe-node](https://github.com/stripe/stripe-node/commit/a80a93e3cd3cfc9709042a37d52ac8d023a87f48#diff-caa95f00428a023bac8606e7a9103678ebdb7f5cc781e6af0fda0ee165f38203).

Add configuration API to billingportal_session.go

---

error.go
stripe.go

Hi Stripe folk 👋
**This PR adds the `ErrorType` `ErrorTypeIdempotency`**
As a consumer of your go SDK I ran into some idempotency errors and while trying to gracefully handle them on my end I noticed the error type `idempotency_error` wasn't mapped to your other `ErrorType`s
All the other main errors seem to be mapped:
Adding this as an error type will allow consumers to cleanly do stripe error type assertions in their code, eg.
```go
pi, err := stripe.somePaymentIntentThing(paymentIntentID)
if err != nil {
if se, ok := err.(*stripe.Error); ok {
switch se.Type {
case stripe.ErrorTypeAPIConnection:
// handle this kind of error
case stripe.ErrorTypeIdempotency:
// handle this kind of error
case ....    
}
} 	
```
Currently you instead have to do something like: 
```go
pi, err := …
```

Adds ErrorType idempotency_error

---

invoice.go
invoice_test.go

While we don't document this well in the API Reference, `subscription_trial_end: 'now'` is supported. It's present in stripe-java [here](https://github.com/stripe/stripe-java/blob/master/src/main/java/com/stripe/param/InvoiceUpcomingParams.java#L610)
cc @stripe/api-libraries @ksinder-stripe

Support `SubscriptionTrialEndNow` on the Retrieve Upcoming Invoice API

---

.github/workflows/ci.yml
billingportal_configuration.go

r? @ob-stripe 
Introduces github actions for CI.
- skips goveralls
- skips testing on "tip" which isn't supported (yet) by the setup-go action: https://github.com/actions/setup-go/issues/21
- Unfortunately GHA seems to lack an exact analog to "allowed failures" in Travis, so testing on tip wouldn't really work as desired anyway.
Also fixes some linter errors. Travis isn't failing when golint fails, for some reason, and so there were some lingering lint problems that need to be fixed.

CI: github actions

---

coupon.go
loginlink.go
product.go
radar_valuelist.go
webhookendpoint.go

We are beginning to automatically generate parts of `stripe-go`. This PR adds five of the files that were simplest to support.
- Adds a comment to the top of these files.
- Adds `Object` and `Deleted` properties. These properties are present on many stripe resources and should be present, but in the past it appears we occasionally omit them as the user need for them is quite rare.
- Rearranging contents.
- variable renaming in UnmarshalJSON method. We don't really follow consistent conventions with these methods today and kind of abbreviate things arbitrarily. Codegen will have to change this.

Begin codegenning 5 files

---

applepaydomain.go
application.go
billingportal_configuration.go
customerbalancetransaction.go
feerefund.go
promotioncode.go
taxrate.go
terminal_connectiontoken.go
terminal_location.go
usagerecord.go
usagerecordsummary.go

r? @remi-stripe - removed the potential breaking change, this is ready for a real review
- `applepaydomain.go`
- Add a missing `DomainName` field to the ListParams.
https://github.com/stripe/stripe-go/pull/1264/files#diff-cbfd212f7ddc855ea5f8d193fa576a280cc362cd76c23e619917129eaffbbdf3R18
- Add missing `Object` field
- `application.go`
- Add missing `Object` field
- `customerbalancetransaction.go`
- Add two missing members to `CustomerBalanceTransactionType` enum
- `feerefund.go`
- Add missing `Object` field
- `loginlink.go`
- Add missing `Object` field
- `product.go`
- Add missing `Object` and `Deleted` field
- `terminal_location.go`
- ~Corrected `*AccountAddressParams` reference in resource, should have been `*AccountAddress`. https://github.com/stripe/stripe-go/pull/1264/files#diff-1cec …

Codegen 10 more files

---

checkout_session.go

* Add support for `ShippingRates` on `CheckoutSessionParams`
* Add support for `AmountShipping`on `CheckoutSessionTotalDetails`
[typescript diff](https://github.com/stripe/stripe-node/pull/1132/files#diff-f684ac17bf6ba3c816191ac9bb75357e7a6d6fdea74b5c686bb57b0dd952e3dd)
[openapi release](https://github.com/stripe/openapi/releases/tag/v23)

Add ShippingRates and AmountShipping

---

checkout_session.go

Corresponds to openapi [v26](https://github.com/stripe/openapi/releases/tag/v26), analog to [this commit on stripe-node]( https://github.com/stripe/stripe-node/commit/0960599bf2bae4a9f38a2558f04b0807858f4856)
* Add support for `transfer_data` on CheckoutSessionSubscriptionDataParams

Add support for CheckoutSessionSubscriptionDataParams.transfer_data

---

accountlink.go
billingportal_session.go
countryspec.go
filelink.go
filelink_test.go
invoiceitem.go
issuing_transaction.go
radar_earlyfraudwarning.go
radar_valuelistitem.go
reporting_reporttype.go
subitem.go
taxid.go
terminal_reader.go
topup.go

cc @stripe/api-library-reviewers 
Contains changes for 13 files to be compatible with codegenned output, bringing the total to 28/74 resource files (`client.go` files and index files are still outstanding).
None of these changes should be breaking. See conversation about `string -> enum` being the non-breaking addition of a type alias.
* accountlink.go - noop
* billingportal_session.go - noop
* countryspec.go
* Add support for `Object` to `CountrySpec`
* filelink.go
* Add support `ExpiresAtNow` to `FileLinkParams`
* invoiceitem.go
* Add support for `Object` and `SubscriptionItem` to `InvoiceItem`
* issuing_transaction.go - noop
* radar_earlyfraudwarning.go - noop
* rader_valuelistitem.go - noop
* reporting_reporttype.go - noop
* subitem.go
* Add support for `Object` to …

codegen: 13 more files

---

accountlink/client.go
applepaydomain/client.go
balancetransaction/client.go
billingportal/configuration/client.go
billingportal/session/client.go
countryspec/client.go
coupon/client.go
event/client.go
filelink/client.go
invoiceitem/client.go
issuing/card/client.go
issuing/cardholder/client.go
issuing/transaction/client.go
mandate/client.go
orderreturn/client.go
plan/client.go
price/client.go
product/client.go
promotioncode/client.go
radar/valuelistitem/client.go
setupattempt/client.go
sigma/scheduledqueryrun/client.go
sku/client.go
terminal/connectiontoken/client.go
terminal/location/client.go
token/client.go
transfer/client.go
usagerecordsummary/client.go
webhookendpoint/client.go

Converts several `client.go` files to the codegenned format. This should be a complete noop. Most of the diff is changing variable names, arbitrary comment content, and some whitespace/ordering changes.

codegen: add several client.go files

---

subschedule.go

This PR updates the names of the `SubscriptionScheduleStatusPastDue` and `SubscriptionScheduleStatusTrialing` constants to match their underlying values. For some reason these are off, which caused some slight confusion when working with them.

Fix names of SubscriptionScheduleStatus constants

---

account.go
checkout_session.go
mandate.go
paymentintent.go
paymentmethod.go
setupintent.go

* Add support for `acss_debit` as value for `PaymentMethodType`.
* Add support for `ACSSDebit` on `PaymentMethod`, `PaymentMethodParams`, `PaymentIntentPaymentMethodOptions`,  `PaymentIntentPaymentMethodOptionsParams`, `MandatePaymentMethodDetails`, `SetupIntentPaymentMethodOptions`, and `SetupIntentPaymentOptionsParams`.
* Add support for `ACSSDebitPayments` on `AccountCapabilities`
* Add support for `PaymentMethodOptions` on `CheckoutSession`
* Add support for `verify_with_microdeposits` and `use_stripe_sdk` on `PaymentIntentNextAction` and `SetupIntentNextAction`

Add support for ACSS debit payment method

---

capability/client.go
customerbalancetransaction/client.go
feerefund/client.go
loginlink/client.go
person/client.go
reversal/client.go
taxid/client.go
usagerecord/client.go
usagerecordsummary/client.go

Codegens nine more `client.go` files.
All changes except for two are formatting/ordering/variable naming/docstring changes that have no behavior effect.
Those two are:
* I replaced one `errors.New(...)` with `fmt.Errorf(...)` -- shouldn't make a difference -- these functions behave essentially identically
* In `usagerecordsummary/client.go` I move the assignment of `path := ...` outside of the inner `Iter` to be consistent with how the other Iter methods are written. This is technically a behavior change: with the previous code, if you mutated `listParams.SubscriptionID` halfway through pagination, things would switch to making requests on a different subscription -- in the new code mutating listParams will have no effect. I can't imagine anybody actually desires the old behavior.

Codegen more client.go files

---

billingportal_configuration.go
capability/client.go
customer.go
customer/client.go
customerbalancetransaction/client.go
discount.go
discount/client.go
feerefund/client.go
invoice/client.go
loginlink/client.go
person/client.go
reversal/client.go
sub/client.go
taxid/client.go
usagerecord/client.go
usagerecordsummary/client.go

(Note: the base of this is #1276 for now, since this is progress on top of that one)
Codegens `customer.go`, `customer/client.go`, `discount.go`, `discount/client.go` and `invoice/client.go`.
This PR contains the first codegenned `custom` methods.
The diff for `invoice.go` is annoying because a lot of methods were rearranged. To make it easier to review, I broke that file up into two commits:
* https://github.com/stripe/stripe-go/pull/1277/commits/99320ad715af41a79ad9f1c5a28ec6bbe2886096 just rearranges things and does nothing else.
* https://github.com/stripe/stripe-go/pull/1277/commits/a828c5ef6c1071259ec8ff3e6debe46cccb8f010 introduces codegen.

Codegen 6 more files

---

payout.go
transfer.go

Codegens `payout.go` and `transfer.go`, after the pattern of  [`balancetransaction.go`](https://github.com/stripe/stripe-go/pull/1287).

codegen: payout.go, transfer.go

---

transfer.go

Fixes small errors introduced by https://github.com/stripe/stripe-go/pull/1289. CI didn't run properly on this branch because  it wasn't based off of master, and I forgot this and merged them all together.

Fix transfer.go

---

ephemeralkey.go

Integrations for Mobile SDKs now expect to only return the raw secret and not the whole JSON anymore so we should stop suppressing the `Secret` property.

Add Secret to EphemeralKey as it now should be accessed directly

---

charge.go
checkout_session.go
invoice.go
paymentintent.go
paymentmethod.go

* Add support for `WechatPay` on `ChargePaymentMethodDetails`, `CheckoutSessionPaymentMethodOptionsParams`, `PaymentIntentPaymentMethodDataParams`, `PaymentIntentPaymentMethodOptionsParams`, `PaymentIntentPaymentMethodOptions`, `PaymentMethodParams`, and `PaymentMethod`
* Add support for new value `wechat_pay` on enums `InvoicePaymentSettingsPaymentMethodType` and `PaymentMethodType`
* Add support for `WechatPayDisplayQRCode`, `WechatPayRedirectToAndroidApp`, and `WechatPayRedirectToIOSApp` on `PaymentIntentNextAction`

Add support for Wechat Pay

---

stripe.go
stripe_test.go

r? @dcr-stripe 
Implements support for streaming requests.
How this will be used
```go
// In foo/client.go, something like:
func (c Client) PDF(id string, params *stripe.FooPDFParams) (*stripe.APIStream, error) {
path := stripe.FormatURLPath("/v1/foo/%s/pdf", id)
stream := &stripe.APIStream{}
err := c.B.CallStreaming(http.MethodGet, path, c.Key, params, stream)
return stream, err
}
```
and then the user can
```go
stream, err := stripe.foo.PDF("foo_xyz", nil)
if err != nil {
return err  
}
writer, err := os.Create("/tmp/foo.pdf")
defer writer.Close()
io.Copy(writer, stream.LastResponse.Body)
```
It might help to review this commit-by-commit. There's some refactoring into helper functions.

Add streaming requests

---

sigma_scheduledqueryrun.go

Fixes https://github.com/stripe/stripe-go/issues/1307
This is a breaking change, but the library would crash on any case of a `ScheduledQueryRun` that has `Error` set so maybe it's worth releasing a patch? We could otherwise shelve until the next major.

Fix deserialization of Error on Sigma ScheduledQueryRun

---

staticcheck.conf

r? @dcr-stripe 
We are beginning to generate docstrings based on the Openapi specification. These docstrings don't begin with the name of the Go struct representing what they describe, so the Golang convention of starting your docstrings this way isn't going to fly. This PR removes that linter rule from the `staticcheck` (our linter) config.
See https://staticcheck.io/docs/checks#ST1021

Remove too-opinionated docstring linter rule

---

checkout/session/client.go
checkout_session.go
dispute.go
dispute/client.go
ephemeralkey.go
ephemeralkey/client.go
fee.go
fee/client.go
issuing_cardholder.go
lineitem.go
lineitem/client.go
payout/client.go
refund.go
refund/client.go
subitem/client.go

r? @stripe/api-library-reviewers 
Makes 14 more files eligible for codegen. This includes adding a number of missing fields (see below).
The most involved thing here is the type alias `LineItemItem` introduced in `checkout/session/client.go`, the type alias ensures that this will not be a breaking change.
There is a go vet error that I will fix in a follow-up, please don't block on that.
* Add support for `BillingAddressCollection` to `CheckoutSession`
* Add support for `NetworkReasonCode` to `DisputeReason`
* Add support for `Object` to `EphemeralKey`, `ApplicationFee`, and `DisputeReason`
* Add support for `Description` to `Refund`
* Add const definition for value `blocked` on enum `IssuingCardholderStatus`
* Bugfix: add support for `Rate` on `CheckoutSessionTotalDetailsBreakdownTax` -- …

codegen: 14 more files

---

stripe.go

Move to using `files.stripe.com`. While both point to the same location, all other SDKs use the newer `files.stripe.com`. This also removes some confusion in this code - both constants were defined but we were using the older constant.

Stop using uploads.stripe.com for the files backend.

---

address.go
charge.go
charge/client.go
quote.go
quote/client.go
taxrate/client.go

r? @stripe/api-library-reviewers 
* Updates `charge.go`, `charge/client.go` `taxrate/client.go` so that they are subject to codegen.
* Move ShippingDetailsParams from `charge.go` into `address.go`. This should be a no-op -- they are both package `stripe`.
Small, formatting changes to `quote.go` and `quote/client.go`.
* Add support for `ApplicationFee` on (Charge) `CaptureParams`
* Add support for `PreferredLanguage` on `ChargePaymentMethodDetailsSofort`
* Bugfix: correctly deserialize `amount` on `ChargeTransferData`

codegen: charge, taxrate

---

client/api.go

r? @stripe/api-library-reviewers 
Changes `client/api.go` to be compatible with codegen.
Alphebetization is now consistent, and "namespaced" resources are now consistently given qualified imports.

codegen: api.go

---

example/example_generated_test.go

```
st-etsai1:stripe-go etsai$ go test ./example
ok  	github.com/stripe/stripe-go/v72/example	0.360s
```
In addition to the API spec used to generate most of this SDK, Stripe also
maintains a corpus of example requests that are expected to work consistently
across all supported languages.
This introduces a new functional test, generated from the spec and example
corpus, to increase confidence that critical flows and use-cases work as
expected in Go.
See similar PRs in [stripe-java](https://github.com/stripe/stripe-java/pull/1256)
This PR introduces a codegenned test suite based off examples similar to the ones in the [Stripe API Reference](https://stripe.com/docs/api)

Generated go test suites

---

token.go

Formatting changes + additional field
cc @dcr-stripe 
* Add support for `Object` to `Token`

Make token.go codegen-able

---

balance.go
balance/client.go
mandate.go
radar/valuelist/client.go
reporting/reportrun/client.go
reporting_reportrun.go

Make the following files codegen-able:
- mandate.go
- balance.go + balance/client.gi
- reporting_reportrun + reporting/reportrun/client.go
- radar/valuelist/client.go
Formatting, comment, and variable name changes only.
cc @dcr

Make more files codegen-able

---

issuing_card.go

Had to do this one manually, issuing_card isn't codegenned yet.
Also (yikes) I accidentally committed this [to master](https://github.com/stripe/stripe-go/commit/81488607bf545b9000862fee74a150de056bb7b2) instead of this branch, without review -- this PR is off the previous commit of master, hence the weird base.
* Add support for `Wallets` on `IssuingCard`

Add support for `Wallets` on `IssuingCard`

---

event.go
sub.go

Make sub.go and event.go codegen-able.
The first commit is rearranging files and the [last is the codegen changes](https://github.com/stripe/stripe-go/commit/a509a9ede361152d9f9b3cbb753b2dc15fc0c1cf).
cc @dcr
* Add support for `APIVersion` and `Object` on `Event`
* Add support for `Metadata` on `SubscriptionItemsParams`

Make sub.go and event.go codegen-able

---

invoice.go
invoicelineitem.go
person.go

Make person.go and invoice.go codegen-able, and move InvoiceLine into its own file (invoicelineitem.go)
The first commits are rearranging files moving InvoiceLine(Item) into its own file and the [last is the codegen changes](https://github.com/stripe/stripe-go/commit/97f420d983ec2e3980bf3575393f3962a55fa1ff).
cc @dcr
* Add support for `'automatic_pending_invoice_item_invoice'` option for `InvoiceBillingReason`
* Add support for `'deleted'` option for `InvoiceStatus`
* Add support for `metadata` on `InvoiceUpcomingCustomerDetailsParams`
* Add support for `schedule` on `InvoiceParams`
* Add support for `created` on `Person`

Make person.go and invoice.go codegen-able

---

client/api.go
source/client.go
sourcetransaction.go
sourcetransaction/client.go

r? @yejia-stripe 
Formats `sourcetransaction.go`, `sourcetransaction/client.go`, and `source/client.go` to be consistent with the code generator.
The most substantive change is in https://github.com/stripe/stripe-go/pull/1388/commits/1a2e463e2fb338ad824c911b341d9b75a5ac6a94 -- this should be a no-op, but is slightly involved.
* Add support for `Object` and `Status` on `SourceTransaction`.

Codegen: `sourcetransaction.go` and `sourcetransaction/client.go`

---

error.go
error_test.go

Currently, I have to do this to handle different kinds of errors:
```go
if stripeErr := new(stripe.Error); errors.As(err, &stripeErr) {
switch typedErr := stripeErr.Err.(type) {
case *stripe.InvalidRequestError:
return nil, errors.WithStack(herodot.ErrBadRequest.WithReason(typedErr.Error()))
}
}
```
As the `Error` type literally wraps the typed error, it makes a lot of sense IMO to expose that typed error through `errors.As`:
```go
if reqErr := new(stripe.InvalidRequestError); errors.As(err, &reqErr) {
return nil, errors.WithStack(herodot.ErrBadRequest.WithReason(reqErr.Error()))
}
```

Add unwrap capability to Error

---

bankaccount.go
bankaccount/client.go
card.go
card/client.go
example/generated_examples_test.go

Make bankaccount.go and card.go and related client.go codegen-able.
The first commit is rearranging files and the last is the codegen changes.
r? @dcr-stripe
cc @richardm-stripe 
* Add support for `address_city`, `address_country`, `address_line1`, `address_line2`, `address_state`, `address_zip`, `exp_month`, `exp_year`, and `name` on `BankAccountParams`
* Add support for `account_holder_name`, `account_holder_type`, and `owner` on `CardParams`
* Add support for `account` on `Card`

Make bankaccount and card codegen-able

---

bankaccount/client.go
card/client.go
paymentsource.go
paymentsource/client.go

Make paymentsource.go and paymentsource/client.go codegen-able. 
Also make some formatting changes for bankaccount/ and card/client.go.
The first commit is rearranging files and the last is the codegen changes.
cc @dcr-stripe
* Add support for `account_holder_name`, `account_holder_type`, `address_city`, `address_country`, `address_line1`, `address_line2`, `address_state`, `address_zip`, `exp_month`, `exp_year`, `name`, `owner` on `CustomerSourceParams`
* Add support for `PaymentSourceOwnerParams`
* Add support for `Object` on `SourceListParams`

Make paymentsource.go and client codegen-able

---

source.go
source/client.go

Make source.go and source/client.go codegen-able.
The first commit is rearranging files and the last is the codegen changes.
cc @dcr-stripe
* Add support for `object` on `Source` (value is the string "source")
* Add support for `client_secret` on `SourceObjectParams`
* Add support for `parent` on `SourceSourceOrderItems`

Make source.go and client codegen-able

---

README.md

Since godoc has been decommissioned in favor of pkg.dev.go, the readme should reflect this change

godoc is no more

---

error.go

Add comments to indicated deprecated error types. The only valid [error types](https://stripe.com/docs/api/errors) are `api_error`, `card_error`, `idempotency_error`, `invalid_request_error`.

Add comments for deprecated error types

---

subschedule.go

With this tag in place it causes unmarshalling error.
Backend return a number, tag expects string and field is a float64

Remove `,string` struct tag from ApplicationFeePercent

---

README.md

I often forget the syntax for `stripe.StringSlice`, so wanted an easy to find example in the README.

Add StringSlice example to readme

---

search_params.go
search_params_test.go

r? @yejia-stripe 
cc @pakrym-stripe 
Adds support for settting `expand` parameters in `SearchParams`. This is necessary for expanding `total_count`.
Implementation is essentially the same as list parameters.
Added tests similar to `ListParams`.

Add support for passing expansions in SearchParams.

---

testhelperstreasury_receivedcredit.go
testhelperstreasury_receiveddebit.go
treasury_outboundtransfer.go
treasury_receivedcredit.go
treasury_receiveddebit.go

Codegen for openapi v154.
r? @dcr-stripe
Add support for NetworkDetails properties on resource ReceivedCredits/ReceivedDebits

API Updates for beta branch

---

stripe_test.go

The user-agent test uses regex to assert the format, adjust it to allow for beta versions.

Fix test assert to allow beta versions

---

webhook/client.go
webhook/client_test.go

r? @dcr-stripe 
Exports fields of ConstructEventOptions struct
Fixes: https://github.com/stripe/stripe-go/issues/1516

Export ConstructEventOptions fields

---

stripe.go
stripe_test.go
webhook/client.go
webhook/client_test.go

Allows APIVersion value to be modified. Trims beta headers before using them in WebHook event version check.
r? @dcr-stripe

Allow setting APIVersion

---

README.md

r? @ramya-stripe 
Adds a section to README.md mentioning beta packages and how to set the `Stripe-Version` header.

Add beta readme.md section

---

.github/workflows/ci.yml
Makefile
README.md

r? @yejia-stripe 
Add coveralls CI step that is conditionally executed for Go 1.16. Test coverage data will be published to https://coveralls.io/github/stripe/stripe-go and displayed as a badge in the README.
Example: https://coveralls.io/jobs/105039169

Add test coverage using coveralls

---

README.md
webhook/client.go
webhook/client_test.go

r? @pakrym-stripe 
Export `UnsignedPayload` and `SignedPayload` fields so they can actually be used for webhook testing
Fixes #1544

Export UnsignedPayload/SignedPayload fields

---

.github/workflows/ci.yml
README.md

Update supported runtime versions for next major release. The changes include:
* Add 1.17, 1.18 and 1.19 to test matrix
* Remove 1.13 and 1.14 from the test matrix
* Remove 1.10, 1.11, 1.12 compile-only tests
* Update README to indicate that we support 1.15 and above

Update supported runtime versions

---

README.md

The link to the Go reference docs https://pkg.go.dev/github.com/stripe/stripe-go/ shows v70 by default, instead of the latest version. This fixes the link to be https://pkg.go.dev/github.com/stripe/stripe-go/v74 (verified that running `make update-version` updates this README link with the major version).

Add version to go reference path

---

form/form.go
form/form_test.go

Closes #1606 
As described in the issue, currently payloads are not encoded deterministically. This PR is a proposal to fix that.

fix: deterministic encoding

---

Makefile

Our generator used to run `goimports` on the generated test suite file separately from calling `make codegen-format`. This is no longer the case, and the past few releases have required manually running goimports on this file. This PR causes `make codegen-format` to run goimports on this file.

Run goimports on generated test suite

---

Makefile

Otherwise CI runs fail because of missing dependencies.

Install goimports before trying to run it

---

error.go
error_test.go

The error message can be returned in a developer_message field, add this to the `Error` type.

Handle developer message in preview error responses

---

README.md

We accidentally put "Custom Requests" in the middle of the "Beta SDKs" section.

Consolidate Beta SDKs section in README

---

balancetransaction.go
platformtaxfee.go
reservetransaction.go
taxdeductedatsource.go

These types are rarely used but exist in other Stripe libraries. We have changed our generator to correctly include them.

Add suppressed balancetransaction types

---

example/generated_examples_test.go
file/client.go
file/client_test.go

Fixes #1734.
This regressed in #1699 (go v75).

Bugfix: point files.New back to files.stripe.com

---

invoice.go

Codegen was not producing correct output for some beta-only fields on `Invoice`. This correctly merges the fields.

Beta: fix incompatible combination

---

README.md
params.go
stripe.go
stripe_test.go

- Adds infrastructure for reporting `usage` to `X-Stripe-Client-Telemetry`, without breaking changes to the public interface.
- Reports usage for `raw_request` in the beta branch.
The first commit [Usage infrastructure](https://github.com/stripe/stripe-go/commit/7527cae42f2f4ed8a0f97300ea83267de7b86cf6) I intend to merge into master in a follow-up, after discussion.
The second commit [Usage for raw_reuest](https://github.com/stripe/stripe-go/commit/4c4da88ee14835faeec4d4dec96c0c61c11155ae) is only applicable to the beta branch. I've opened the PR against beta showing both for a more holistic review.
The tricky part about all this is: we have a struct `BackendImplementation` with public `Do` and `Call` methods (`Call` invokes `Do`). Only the `Do` method has access to `Params` which is …

Track usage of `raw_request`

---

stripe.go
stripe_test.go

This PR udpates the retry behavior in the Go SDK to be the same as rest of our languages in terms of when to retry for errors with code >=500
From @richardm-stripe who lead this investigation previously
> The additional restrictions in stripe-go/stripe-ruby (don't bother retrying POST status=500) is a sensible optimization but the logic also misses some statuses (503/504/502) that possibly could succeed on retry. It's better for cases more granular than `>=500` to be captured in the logic that produces `x-stripe-should-retry` rather than to be hardcoded/maintained across 7+ official server SDKs, Terminal SDKs, direct integrations, etc.
Related Jira: https://jira.corp.stripe.com/browse/DEVSDK-1711
* When no `x-stripe-should-retry` header is set in the response, the library now retries all …

Retry for all error codes >= 500

---

confirmationtoken.go
issuing/authorization/client.go
paymentintent.go
paymentmethod.go
setupintent.go

This PR adds Go SDK support for automatically marking methods and params as deprecated. 
- Mark as deprecated the `Approve` and `Decline` methods on `issuing/authorization/client.go`.  Instead, [respond directly to the webhook request to approve an authorization](https://stripe.com/docs/issuing/controls/real-time-authorizations#authorization-handling).
- Mark as deprecated the `persistent_token` property on `ConfirmationTokenPaymentMethodPreviewLink.persistent_token`, `PaymentIntentPaymentMethodOptionsLink`, `PaymentIntentPaymentMethodOptionsLinkParams`, `PaymentMethodLink`, `SetupIntentPaymentMethodOptionsCard`, `SetupIntentPaymentMethodOptionsLinkParams`. This is a legacy parameter that no longer has any function.

Deprecate Go methods and Params

---

bankaccount.go
card.go

The list method on BankAccount/Card takes a param called "object" as seen in https://docs.stripe.com/api/external_account_bank_accounts/list?lang=node
This has been missing in the Go SDK
* Add support to `object` in `BankAccountListParams` and `CardListParams`

Add object param to list method for BankAccount/Card

---

.github/workflows/ci.yml
Makefile

Context:
go tools new release requires a later version of go than what we support.  Use of @latest in the Makefile and ci.yml file causes us to always fetch the latest which will cause CI builds to fail.
Changes:
changed Makefile codegen format to install tools v0.24.0 (which is the last version before the breaking change) instead of latest
changed ci.yml in linter step to use v0.24.0 instead of latest

Use pinned version of tools in Makefile and ci.yml

---

README.md
api_version.go
params.go
rawrequest/client.go
rawrequest/client_test.go
stripe.go
stripe_test.go

As the v2 API is releasing soon, we want Go to be able to make requests against the new endpoints despite not having generated types.
This is a copy/paste of https://github.com/stripe/stripe-go/pull/1648 with a few key differences:
- updated README with a more modern example
- changed the `APIMode` constants from `"preview"` and `"standard"` to `"v1"` and `"v2"`
- ❗inferred API mode from path prefix instead of letting user specify it
- removed some assertions in tests that cared about the API version
Because we no longer needed to supply default values for API mode, I could remove the function that handled that.  I also adjusted tests that assumed you could set `content-type` and `v1` / `v2` independently (given that all v1 requests are form encoded and all v2 request are json).
1. Create …

add support for RawRequest

---

README.md
rawrequest/client.go
rawrequest/client_test.go

The `rawrequests` functions for Post, Get, and Delete methods rely on global configuration which can be cumbersome when using these methods to call `/v2/` APIs. Instead, the recommendation is to use the client model (introduced in https://github.com/stripe/stripe-go/pull/1929) which allows local configuration of backend and api key, which enables more flexible calls to new/preview/unsupported APIs.  
- removes rawrequest `Post`, `Get`, and `Delete`
- updates tests
- updates README.md
This is a follow up to https://github.com/stripe/stripe-go/pull/1929
The individual `rawrequests` functions for Post, Get, and Delete methods are removed in favor of the client model which allows local configuration of backend and api key, which enables more flexible calls to new/preview/unsupported APIs.

Remove  rawrequest Post, Get, and Delete

---

example/v2/meter_event_stream/meter_event_stream.go
example/v2/thinevent_webhook_handler/thinevent_webhook_handler.go

In our recent SDK release we added a couple new examples along with a template to make it easy for us to create new examples.  Our documentation around examples was lacking.  This PR adds comments to explain each new example.
- added comment to meter_event_stream.go describing the example, and changed the event_name to match documentation
- added comment to thinevent_webhook_handler.go describing the example

Added comments to v2 examples

---

README.md

A user may want to install the beta version of the Stripe Go SDK in order to access unreleased functionality.  The URL in the readme was incorrect after our latest release.  This PR updates it to use the branch name so that only the base version changes on each major release.
- change specific beta version to "beta" in the beta go get url

Fixes Beta SDK url in go get command

---

webhook/client.go
webhook/client_test.go

[Stripe API versions now contain two parts](https://stripe.com/blog/introducing-stripes-new-api-release-process): a date part (as before) and an identifier.  The SDKs validate that webhook events received are in the shape expected by the pinned version in the SDK but going forward, that will be true for different versions with the same identifier.  For example, the September API release was 2024-09-30.acacia, and we expect that webhook events sent with version 2024-09-30.acacia will be compatible with an SDK pinned to 2025-10-28.acacia.  This PR updates the version checking logic to make sure we don't reject webhook events incorrectly.
- replaced api version check in webhook/client with isCompatibleApiVersion which will test if the release identifier of the webhook event matches the …

Update webhook API version validation

---

README.md
stripe.go
stripe_test.go
webhook/client.go
webhook/client_test.go

When we introduced beta SDKs, we allowed users to directly update the global configuration for API Version since they needed to pass beta headers in #1529. We soon realized that was not safe and was error prone if users didnt pass in the right format and so introduced a helper method in #1819 and advertised that as the right way of doing things in the README
Proper deserialization of classes from Events can be guaranteed only when the Webhook API version matches the API version used to generate the SDKs. Therefore, in this PR we are dropping the ability to directly update the API version.
- Resolving merge conflicts coming from running the auto merge tool after #1940
- Rename the public variable `APIVersion` to a private variable `apiVersionWithBetaHeaders` and add a new constant for …

Do not allow setting API Version directly 

---

stripe_test.go

Follow up to https://github.com/stripe/stripe-go/pull/1941.  After fixing https://github.com/stripe/stripe-java/pull/1913, I double checked the other SDKs that were modified as part of that work.  The golang SDK is implemented correctly but it did not have unit tests for the edge cases in `AddBetaVersion`.  This PR implements the tests for these edge cases.
- added tests to ensure AddBetaVersion returns an error when called with the same beta version twice, and allows AddBetaVersion to be called multiple times for different beta versions

Add tests for AddBetaVersion edge cases

---

.github/workflows/ci.yml
Makefile
README.md
justfile

In an effort to modernize and simplify our local tooling, we're moving our dev commands from makefiles to [justfiles](https://github.com/casey/just). This is intended to be mostly a drop-in replacement, but some command names may change per standardization efforts.
- add justfile
- tweak CI to use justfile
- remove coveralls from CI
[DEVSDK-2325](https://go/j/DEVSDK-2325)

add justfile, update readme, remove coveralls

---

.github/workflows/ci.yml
example/generated_examples_test.go
justfile

We want to pin our CI ubuntu version to the latest possible so it doesn't auto-update on us, but we stay current ish.
We also fix a bug in generating the SDK where we install too early.
- pin ubuntu version in CI
- fix `just format` bug

pin CI and fix formatting

---

account/client_test.go
charge/client_test.go
client/api.go
coupon/client_test.go
params.go
stripe.go
testing/testing.go

We would like to get a better sense of how many users are using Stripe Clients (aka. `client.API`) vs the global client. This will help us better inform how to update documentation and consider possible changes to the Stripe Client going forward.
This sends the string `stripe_client` to telemetry statistics when they are enabled when a Stripe Client was used for that request. It does this by wrapping the existing `Backend`s with a `usageBackend` that sets the string `stripe_client` on requests. This string is not sent on the global client, so we can distinguish the two.
I also updated a few random tests to use the Stripe Client to add some additional test coverage for this change.
* Add telemetry for usage of the Stripe Client

Add usage data for stripe client usage

---

example/generated_examples_test.go

In order to have a stronger set of tests on the Stripe Client before any upcoming changes to support V2.
For each resource-based example test of the form `TestFoo`, this adds a corresponding service-based test of the form `TestFooService`.

Add Stripe Client to example tests

---

README.md

The README was confusing with `$resource$`.
- Replace `$resource$` with `Customer` in the code snippets in the README
- Also replace the explicit `client.API{}` and `sc.Init` call with `client.New()` in the README

Replace "$resource$" with "Customer" in README code snippets

---

stripe.go
stripe_test.go

We decided to let users pass in the same beta header multiple times.
- AddBetaVersion will use the highest version number used for a beta feature instead of return an `error` on a conflict as it had done previously.
- AddBetaVersion will use the highest version number used for a beta feature instead of return an `error` on a conflict as it had done previously.

Update behavior of AddBetaHeader

---

coupon/client_test.go

The coupon change made in https://github.com/stripe/stripe-go/commit/89f7daa9e504eee8e51bade30637545d77917f24#diff-a7914a23e2b39d1496fef46a29de8797daf070921d3f80fee80cd230ad15d73d but for master

Fix coupon test for field that was removed

---

webhook/client.go
webhook/client_test.go

We decided that beta SDKs should exactly match the API version for events they're deserializing to minimize the chances of accidental breaking changes. This PR tweaks the version matching function to accommodate that change
- updated `isCompatibleAPIVersion` signature and implementation
- added tests
- [RUN_DEVSDK-1556](https://go/j/RUN_DEVSDK-1556)
- ⚠️ Public Preview SDKs now require an exact API version match when deserializing webhooks

require beta SDKs match event versions exactly when deserializing

---

client/api.go
externalaccount/client.go

Stripe recently added a `/v1/external_accounts` endpoint that used to be under `/v1/account/%s/external_accounts`. The endpoint returns a union type of either `Card` or `BankAccount`. Go does not have a great way to deal with union types, so in the past for the child endpoints, we created separate `Card` and `BankAccount` services. For the top-level External Account service, we decided to have a single service with mirrored methods (e.g. both `GetCard` and `GetBankAccount`).
- Adds `externalaccount/client.go` with separate CRUDL operations for each of Card and BankAccount.
- Add support for top-level External Account CRUDL calls by adding separate `GetCard`/`GetBankAccount`, `NewCard`/`NewBankAccount`, etc. calls.

Handle top-level External Account service

---

webhook/client_test.go

Backports a skipped test from https://github.com/stripe/stripe-go/pull/2017
- skips a GA-only test in preview SDKs (which won't affect the GA sdk, but it's nice to have everything line up)

Backport beta fixes

---

iter.go
iter_test.go

For V2 support, we offer pagination using Go's `iter.Seq2` interface, so iterating over V2 accounts looks like this:
```go
for acct, err := range sc.V2Accounts.All(params) {
// do something
}
```
This compares to V1 where it looks like this:
```go
i := sc.Accounts.List(params)
for i.Next() {
acct := i.Account()
// do something
}
if err := i.Err(); err != nil {
// handle
}
```
With the new `stripe.Client` type in a future PR, we will be providing the former style pagination for both V1 and V2.
This PR paves the way by introducing the mechanism for V1 to cleanly paginate in `List` methods.
- Adds an unexported (i.e., internal-only) type `v1List` with an `All` method for pagination. This is not currently used anywhere, but will be leveraged by `stripe.Client` in a subsequent PR.

Support cleaner pagination for V1 in stripe.Client

---

iter.go
search_iter.go
search_iter_test.go

This is a follow-up to https://github.com/stripe/stripe-go/pull/2027 in which we laid the groundwork for cleaner `List` pagination for V1 services. This PR does the same for `Search` pagination.
- Adds an unexported (i.e., internal-only) type `v1SearchList` with an `All `method for pagination. This is not currently used anywhere, but will be leveraged by `stripe.Client` in a subsequent PR.
- Also made a minor simplification to `iter.go` that I noticed while re-implementing the same logic in `search_iter.go`. That is, I replaced `new(T)` with `nil` when calling `yield` on an `error`.

Add auto-pagination for search

---

.vscode/settings.json
v2/core/event/client_test.go
v2_events.go

Currently, we are not correctly unmarshaling V2 event `Data`, and the resulting event will have an empty `Data` struct.
- Fixes V2 event data unmarshaling

Fix event data unmarshaling

---

v2/core/eventdestination/client_test.go

In an upcoming change, the ping event will get its own `Event` object, which will have a related object. The `TestEventDestinationPing` will fail once we pull that change.
- Adds `RelatedObject` data to the `TestEventDestinationPing` unit test

Add related object to ping test

---

.vscode/settings.json

I no longer need the Go-specific VS code setting, so it's best to keep things as clean as possible
- Removes   "go.alternateTools" from settings.json

Remove Go VS Code setting

---

v2/core/event/client_test.go
v2_events.go

Tests are failing on `master` because we have a few conflicting in-flight changes for Events coming from codegen. This PR picks out the changes that are needed to get tests passing again.
- Updates events to embed `V2BaseEvent` instead of `V2RawEvent`
- Adds `json` tags to V2 events
- Updates a test to reflect the above

Embed `V2BaseEvent` in V2 events instead of `V2RawEvent`

---

stripe_client.go
stripe_client_test.go
webhooks.go
webhooks_test.go

During our bug bash, we found that the Go SDK segfaults on a `nil` ClientOption. We also found that `stripe.Client` was missing `ConstructEvent` functionality. This PR kills two birds with one stone.
- Makes `...ClientOption` parameter in `stripe.NewClient` `nil`-safe
- Adds `ConstructEvent` method on `stripe.Client`
- Adds a `nil`-safe options pattern to both `ParseThinEvent` and `ConstructEvent` methods
Note that neither `stripe_client.go` nor `webhooks.go` has been released yet, so there are no actual backwards incompatible changes in this PR.

Improved options patterns for stripe.Client

---

error.go
v2/core/eventdestination/client_test.go
v2_event.go
v2_events.go

* The `GetBaseEvent` method on `V2Event` is confusing because the user shouldn't be using it--instead they should type-cast to the appropriate concrete event. Therefore, we shouldn't even expose it.
* The `V2ErrorCode` looks like something that should be handled programmatically, but shouldn't. Therefore, we will just treat it as a `string` to avoid that footgun. 
- Unexport `GetBaseEvent` method.
- Remove `V2ErrorCode` type.
* Unexported `GetBaseEvent` --> `getBaseEvent`. This function should not be called. Instead, type-cast the `V2Event` to a concrete Event struct.
* Removed the `V2ErrorCode` type. Error codes should not be handled programmatically for V2 errors.

Unexport GetBaseEvent and V2ErrorCode

---

README.md

The current README only has resource-based and `client.API`-based patterns. We are deprecating the latter, and will soon deprecate the former.
- Replaces code snippets in the README with `stripe.Client`-based examples
- Adds a secion linking to the new https://github.com/stripe/stripe-go/wiki/Migration-guide-for-Stripe-Client

Update README to reflect new stripe.Client pattern

---

.github/workflows/rules.yml

Our merge script requires that PRs be merged with a merge commit to maintain git history and avoid conflicts in the future.  Our normal PR process is to squash before merging, usually with auto-merge enabled.  Since Github defaults to the last merge method selected, its very easy to accidentally enable auto-squash in this one situation where we really need a merge commit.
Neither Github's branch rulesets nor branch protection rules let us define rules in the context of the HEAD ref, so this PR adds a CI that can.
- add rules.yml to define PR/branch rules that we cannot define in the Github UI
- added Merge script PRs must create merge commits rule to run when auto merge is enabled and when the branch contains `/merge-`, and check that the auto merge method is 'merge'
When auto-merge is …

Require merge commit for merge PR (+ new rules.yml file)

---

params.go
params_internal_test.go

It was previously possible, and occasionally seen in real usage, that a telemetry string could be duplicated when sent to Stripe (e.g. `stripe_client,stripe_client,stripe_client`). This could lead to very long usage strings that could eventually affect performance and hit payload limits.
* Deduplicates usage arrays
* Fixes a bug where telemetry strings could have duplicate values

Deduplicate telemetry strings

---

stripe_test.go

This is a follow-up to https://github.com/stripe/stripe-go/pull/2068 which caused a unit test depending on the order of telemetry arrays to intermittently fail.
- Fixes the telemetry test to no longer depend on the order of usage strings

Fix failing telemetry test

---

api_version.go
v2payments_offsessionpayment.go
v2payments_offsessionpayment_params.go

Changes were done to OffSessionPayment API in the May release which did not make it to the SDKs. Pulling those changes in now and making another SDK release for the `2025-05-28.preview` API version
- Pull protos in codegen for `2025-05-28.preview`
- Generate the SDK

Pull in OffSessionPayment changes for the May release

---

README.md

In https://github.com/stripe/stripe-go/pull/2117 we added the ability to access `RawJSON` while iterating. This PR adds those instructions to the `README.md`.
- Updates `README.md` to include instructions for accessing the `RawJSON` in a `List` or `Search` method

Update README.md with instructions for accessing LastResponse in a List method

---

event_notification.go
stripe_client_test.go
v2/core/event/client_test.go
v2/core/eventdestination/client_test.go
v2_events.go

The type `stripe.RelatedObject` should be namespaced to `stripe.V2CoreEventRelatedObject` like our other Event-related types.
- Changes the name of the `stripe.RelatedObject` struct to `stripe.V2CoreEventRelatedObject`.
- ⚠️ Changes the name of the `stripe.RelatedObject` struct to `stripe.V2CoreEventRelatedObject`.

Change RelatedObject to V2CoreEventRelatedObject
